// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (C) 2026 Alexander Grec
 *
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: generators/generate_ccu.py
 * Source data:  generators/data/ccu-main.json
 */

#include <linux/clk-provider.h>
#include <linux/io.h>
#include <linux/module.h>
#include <linux/platform_device.h>

#include <dt-bindings/clock/sun60i-a733-ccu.h>
#include <dt-bindings/reset/sun60i-a733-ccu.h>

#include "../clk.h"
#include "ccu_common.h"
#include "ccu_reset.h"
#include "ccu_div.h"
#include "ccu_gate.h"
#include "ccu_mp.h"
#include "ccu_nkmp.h"

static const struct clk_parent_data osc24M[] = {
	{ .fw_name = "hosc" }
};

static SUNXI_CCU_M_HWS(pll_periph0_2x_clk, "pll-periph0-2x",
		       pll_periph0_hws, 0x020, 16, 3, 0);

static SUNXI_CCU_GATE_HWS(apb1_clk, "apb1",
				pll_periph0_2x_hws,
				0x000, 0, 0 | CLK_IS_CRITICAL);

static SUNXI_CCU_GATE_HWS(uart0_clk, "uart0",
				apb1_hws,
				0x000, 1, 0);

static struct clk_hw_onecell_data a733_hw_clks = {
	.hws	= {
	[CLK_PLL_PERI0]	= &pll_periph0_clk.common.hw,
	[CLK_PLL_PERI0_2X]	= &pll_periph0_2x_clk.common.hw,
	[CLK_APB1]	= &apb1_clk.common.hw,
	[CLK_UART0]	= &uart0_clk.common.hw,
	},
	.num	= CLK_NUMBER,
};

static struct ccu_reset_map a733_ccu_resets[] = {
	[RST_BUS_UART0]	= { 0x000, 0 },
};

static int sun60i_a733_ccu_probe(struct platform_device *pdev)
{
	void __iomem *reg;
	struct clk_hw_onecell_data *hw_data;
	int ret;

	reg = devm_platform_ioremap_resource(pdev, 0);
	if (IS_ERR(reg))
		return PTR_ERR(reg);

	hw_data = devm_kmemdup(&pdev->dev, &a733_hw_clks,
			       sizeof(a733_hw_clks), GFP_KERNEL);
	if (!hw_data)
		return -ENOMEM;

	/* Register all clocks */
	ret = devm_ccu_probe(pdev, reg, hw_data, a733_ccu_resets,
			     ARRAY_SIZE(a733_ccu_resets));
	if (ret)
		return ret;

	return devm_of_clk_add_hw_provider(&pdev->dev, of_clk_hw_onecell_get,
					   hw_data);
}

static const struct of_device_id sun60i_a733_ccu_match[] = {
	{ .compatible = "allwinner,sun60i-a733-ccu" },
	{ }
};

static struct platform_driver sun60i_a733_ccu_driver = {
	.probe	= sun60i_a733_ccu_probe,
	.driver	= {
		.name		= "sun60i-a733-ccu",
		.of_match_table	= sun60i_a733_ccu_match,
	},
};
builtin_platform_driver(sun60i_a733_ccu_driver);

