// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (C) 2026 Alexander Grec
 *
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: generators/generate_ccu.py --domain rtc
 * Source data:  /home/grec-alexander/Documents/porting/sun60iw2-upstream/generators/data/ccu-rtc-extracted.json
 */

#include <linux/clk-provider.h>
#include <linux/io.h>
#include <linux/module.h>
#include <linux/platform_device.h>
#include <linux/delay.h>
#include <dt-bindings/clock/sun60i-a733-rtc.h>


#include "../clk.h"

#include "ccu_common.h"
#include "ccu_reset.h"

#include "ccu_div.h"
#include "ccu_gate.h"
#include "ccu_mp.h"
#include "ccu_nm.h"
#include "ccu_nkmp.h"
#include "ccu_mux.h"

struct sun60i_key_gate {
	struct ccu_gate gate;
	u32 key_value;
};

static inline struct sun60i_key_gate *hw_to_sun60i_key_gate(struct clk_hw *hw)
{
	struct ccu_gate *cg = hw_to_ccu_gate(hw);

	return container_of(cg, struct sun60i_key_gate, gate);
}

static int sun60i_key_gate_enable(struct clk_hw *hw)
{
	struct sun60i_key_gate *kg = hw_to_sun60i_key_gate(hw);
	struct ccu_common *common = &kg->gate.common;
	unsigned long flags;
	u32 reg;

	spin_lock_irqsave(common->lock, flags);
	reg = readl(common->base + common->reg);
	reg |= kg->key_value;
	reg |= kg->gate.enable;
	if (common->features & CCU_FEATURE_UPDATE_BIT)
		reg |= CCU_SUNXI_UPDATE_BIT;
	writel(reg, common->base + common->reg);
	spin_unlock_irqrestore(common->lock, flags);

	return 0;
}

static void sun60i_key_gate_disable(struct clk_hw *hw)
{
	struct sun60i_key_gate *kg = hw_to_sun60i_key_gate(hw);
	struct ccu_common *common = &kg->gate.common;
	unsigned long flags;
	u32 reg;

	spin_lock_irqsave(common->lock, flags);
	reg = readl(common->base + common->reg);
	reg |= kg->key_value;
	reg &= ~kg->gate.enable;
	if (common->features & CCU_FEATURE_UPDATE_BIT)
		reg |= CCU_SUNXI_UPDATE_BIT;
	writel(reg, common->base + common->reg);
	spin_unlock_irqrestore(common->lock, flags);
}

static int sun60i_key_gate_is_enabled(struct clk_hw *hw)
{
	struct sun60i_key_gate *kg = hw_to_sun60i_key_gate(hw);

	return ccu_gate_helper_is_enabled(&kg->gate.common, kg->gate.enable);
}

static unsigned long sun60i_key_gate_recalc_rate(struct clk_hw *hw,
						 unsigned long parent_rate)
{
	return parent_rate;
}

static int sun60i_key_gate_determine_rate(struct clk_hw *hw,
					  struct clk_rate_request *req)
{
	if (clk_hw_get_flags(hw) & CLK_SET_RATE_PARENT)
		req->best_parent_rate = clk_hw_round_rate(clk_hw_get_parent(hw), req->rate);

	req->rate = req->best_parent_rate;
	return 0;
}

static int sun60i_key_gate_set_rate(struct clk_hw *hw, unsigned long rate,
				    unsigned long parent_rate)
{
	return 0;
}

static const struct clk_ops sun60i_key_gate_ops = {
	.disable	= sun60i_key_gate_disable,
	.enable		= sun60i_key_gate_enable,
	.is_enabled	= sun60i_key_gate_is_enabled,
	.determine_rate	= sun60i_key_gate_determine_rate,
	.set_rate	= sun60i_key_gate_set_rate,
	.recalc_rate	= sun60i_key_gate_recalc_rate,
};

struct sun60i_special_gate {
	struct ccu_gate gate;
	u16 key_reg;
	u32 key_value;
	bool reverse;
};

static inline struct sun60i_special_gate *hw_to_sun60i_special_gate(struct clk_hw *hw)
{
	struct ccu_gate *cg = hw_to_ccu_gate(hw);

	return container_of(cg, struct sun60i_special_gate, gate);
}

static int sun60i_special_gate_enable(struct clk_hw *hw)
{
	struct sun60i_special_gate *sg = hw_to_sun60i_special_gate(hw);
	struct ccu_common *common = &sg->gate.common;
	unsigned long flags;
	u32 reg;
	u32 key_reg;

	spin_lock_irqsave(common->lock, flags);
	reg = readl(common->base + common->reg);
	if (sg->key_value) {
		if (common->reg == sg->key_reg) {
			reg |= sg->key_value;
		} else {
			key_reg = readl(common->base + sg->key_reg);
			key_reg |= sg->key_value;
			writel(key_reg, common->base + sg->key_reg);
		}
	}
	if (sg->reverse)
		reg &= ~sg->gate.enable;
	else
		reg |= sg->gate.enable;
	if (common->features & CCU_FEATURE_UPDATE_BIT)
		reg |= CCU_SUNXI_UPDATE_BIT;
	writel(reg, common->base + common->reg);
	spin_unlock_irqrestore(common->lock, flags);

	return 0;
}

static void sun60i_special_gate_disable(struct clk_hw *hw)
{
	struct sun60i_special_gate *sg = hw_to_sun60i_special_gate(hw);
	struct ccu_common *common = &sg->gate.common;
	unsigned long flags;
	u32 reg;
	u32 key_reg;

	spin_lock_irqsave(common->lock, flags);
	reg = readl(common->base + common->reg);
	if (sg->key_value) {
		if (common->reg == sg->key_reg) {
			reg |= sg->key_value;
		} else {
			key_reg = readl(common->base + sg->key_reg);
			key_reg |= sg->key_value;
			writel(key_reg, common->base + sg->key_reg);
		}
	}
	if (sg->reverse)
		reg |= sg->gate.enable;
	else
		reg &= ~sg->gate.enable;
	if (common->features & CCU_FEATURE_UPDATE_BIT)
		reg |= CCU_SUNXI_UPDATE_BIT;
	writel(reg, common->base + common->reg);
	spin_unlock_irqrestore(common->lock, flags);
}

static int sun60i_special_gate_is_enabled(struct clk_hw *hw)
{
	struct sun60i_special_gate *sg = hw_to_sun60i_special_gate(hw);
	struct ccu_common *common = &sg->gate.common;
	u32 val = readl(common->base + common->reg) & sg->gate.enable;

	return sg->reverse ? !val : !!val;
}

static unsigned long sun60i_special_gate_recalc_rate(struct clk_hw *hw,
						     unsigned long parent_rate)
{
	return parent_rate;
}

static int sun60i_special_gate_determine_rate(struct clk_hw *hw,
					      struct clk_rate_request *req)
{
	if (clk_hw_get_flags(hw) & CLK_SET_RATE_PARENT)
		req->best_parent_rate = clk_hw_round_rate(clk_hw_get_parent(hw), req->rate);

	req->rate = req->best_parent_rate;
	return 0;
}

static int sun60i_special_gate_set_rate(struct clk_hw *hw, unsigned long rate,
					unsigned long parent_rate)
{
	return 0;
}

static const struct clk_ops sun60i_special_gate_ops = {
	.disable	= sun60i_special_gate_disable,
	.enable		= sun60i_special_gate_enable,
	.is_enabled	= sun60i_special_gate_is_enabled,
	.determine_rate	= sun60i_special_gate_determine_rate,
	.set_rate	= sun60i_special_gate_set_rate,
	.recalc_rate	= sun60i_special_gate_recalc_rate,
};

struct sun60i_fixed_rate_gate {
	struct ccu_gate gate;
	unsigned long fixed_rate;
};

static inline struct sun60i_fixed_rate_gate *hw_to_sun60i_fixed_rate_gate(struct clk_hw *hw)
{
	struct ccu_gate *cg = hw_to_ccu_gate(hw);

	return container_of(cg, struct sun60i_fixed_rate_gate, gate);
}

static int sun60i_fixed_rate_gate_enable(struct clk_hw *hw)
{
	struct sun60i_fixed_rate_gate *fg = hw_to_sun60i_fixed_rate_gate(hw);

	return ccu_gate_helper_enable(&fg->gate.common, fg->gate.enable);
}

static void sun60i_fixed_rate_gate_disable(struct clk_hw *hw)
{
	struct sun60i_fixed_rate_gate *fg = hw_to_sun60i_fixed_rate_gate(hw);

	ccu_gate_helper_disable(&fg->gate.common, fg->gate.enable);
}

static int sun60i_fixed_rate_gate_is_enabled(struct clk_hw *hw)
{
	struct sun60i_fixed_rate_gate *fg = hw_to_sun60i_fixed_rate_gate(hw);

	return ccu_gate_helper_is_enabled(&fg->gate.common, fg->gate.enable);
}

static unsigned long sun60i_fixed_rate_gate_recalc_rate(struct clk_hw *hw,
							unsigned long parent_rate)
{
	struct sun60i_fixed_rate_gate *fg = hw_to_sun60i_fixed_rate_gate(hw);

	return fg->fixed_rate;
}

static int sun60i_fixed_rate_gate_determine_rate(struct clk_hw *hw,
						 struct clk_rate_request *req)
{
	struct sun60i_fixed_rate_gate *fg = hw_to_sun60i_fixed_rate_gate(hw);

	req->rate = fg->fixed_rate;
	return 0;
}

static int sun60i_fixed_rate_gate_set_rate(struct clk_hw *hw, unsigned long rate,
					   unsigned long parent_rate)
{
	return 0;
}

static const struct clk_ops sun60i_fixed_rate_gate_ops = {
	.disable	= sun60i_fixed_rate_gate_disable,
	.enable		= sun60i_fixed_rate_gate_enable,
	.is_enabled	= sun60i_fixed_rate_gate_is_enabled,
	.determine_rate	= sun60i_fixed_rate_gate_determine_rate,
	.set_rate	= sun60i_fixed_rate_gate_set_rate,
	.recalc_rate	= sun60i_fixed_rate_gate_recalc_rate,
};


#define SUN60I_A733_RTC_KEY_FIELD_MAGIC_NUM	0x16AA0000
#define SUN60I_A733_RTC_LOSC_CTRL_REG		0x000
#define SUN60I_A733_RTC_LOSC_AUTO_SWT_STA_REG	0x004
#define SUN60I_A733_RTC_LOSC_OUT_GATING_REG	0x060
#define SUN60I_A733_RTC_XO_CTRL_REG		0x160

#define SUN60I_A733_RTC_LOSC_OSC32K_SEL		BIT(0)
#define SUN60I_A733_RTC_LOSC_EXT32K_ENABLE	BIT(4)
#define SUN60I_A733_RTC_LOSC_EXT32K_STABLE	BIT(4)
#define SUN60I_A733_RTC_LOSC_AUTO_SWITCH_ENABLE	BIT(14)
#define SUN60I_A733_RTC_LOSC_AUTO_SWITCH_MASK	(BIT(15) | BIT(14))
#define SUN60I_A733_RTC_LOSC_OUT_SRC_SEL_MASK	(0x3 << 1)
#define SUN60I_A733_RTC_DCXO_ENABLE		BIT(1)

static void sun60i_a733_rtc_ccu_update_bits(void __iomem *reg, u32 mask, u32 val)
{
	u32 regval = readl(reg);

	regval &= ~mask;
	regval |= val;
	writel(regval, reg);
}

static void sun60i_a733_rtc_ccu_update_key_bits(void __iomem *reg, u32 mask,
						 u32 val)
{
	u32 regval = readl(reg);

	regval &= ~mask;
	regval |= val;
	regval |= SUN60I_A733_RTC_KEY_FIELD_MAGIC_NUM;
	writel(regval, reg);
}

static bool sun60i_a733_rtc_ccu_ext32k_is_stable(void __iomem *reg)
{
	int tries;
	int stable_reads = 0;
	u32 val;

	for (tries = 0; tries < 100 && stable_reads < 4; tries++) {
		val = readl(reg);
		if (val & SUN60I_A733_RTC_LOSC_EXT32K_STABLE)
			stable_reads = 0;
		else
			stable_reads++;

		udelay(3);
	}

	return stable_reads == 4;
}

static void sun60i_a733_rtc_ccu_clock_source_init(struct device *dev,
						  void __iomem *reg)
{
	u32 val;

	sun60i_a733_rtc_ccu_update_bits(reg + SUN60I_A733_RTC_XO_CTRL_REG,
					 SUN60I_A733_RTC_DCXO_ENABLE,
					 SUN60I_A733_RTC_DCXO_ENABLE);

	sun60i_a733_rtc_ccu_update_key_bits(reg + SUN60I_A733_RTC_LOSC_CTRL_REG,
					     SUN60I_A733_RTC_LOSC_AUTO_SWITCH_MASK,
					     SUN60I_A733_RTC_LOSC_AUTO_SWITCH_ENABLE);

	val = readl(reg + SUN60I_A733_RTC_LOSC_CTRL_REG);
	if (!(val & SUN60I_A733_RTC_LOSC_EXT32K_ENABLE)) {
		sun60i_a733_rtc_ccu_update_key_bits(reg + SUN60I_A733_RTC_LOSC_CTRL_REG,
						     SUN60I_A733_RTC_LOSC_EXT32K_ENABLE,
						     SUN60I_A733_RTC_LOSC_EXT32K_ENABLE);

		if (!sun60i_a733_rtc_ccu_ext32k_is_stable(
			    reg + SUN60I_A733_RTC_LOSC_AUTO_SWT_STA_REG))
			dev_warn(dev,
				 "ext-32k not stable, osc32k will fall back to iosc-div32k\n");
	}

	sun60i_a733_rtc_ccu_update_key_bits(reg + SUN60I_A733_RTC_LOSC_CTRL_REG,
					     SUN60I_A733_RTC_LOSC_OSC32K_SEL,
					     SUN60I_A733_RTC_LOSC_OSC32K_SEL);

	sun60i_a733_rtc_ccu_update_bits(reg + SUN60I_A733_RTC_LOSC_OUT_GATING_REG,
					 SUN60I_A733_RTC_LOSC_OUT_SRC_SEL_MASK, 0);
}
static SUNXI_CCU_GATE(iosc_clk, "iosc", "rc-16m", 0x160, BIT(0), 0);

static struct sun60i_key_gate ext32k_gate_clk = {
	.gate		= {
		.enable	= BIT(4),
		.common	= {
			.reg		= 0x000,
			.hw.init	= CLK_HW_INIT("ext32k-gate", "ext-32k",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x16AA0000,
};

static CLK_FIXED_FACTOR(iosc_div32k_clk, "iosc-div32k", "iosc", 500, 1, 0);

static struct sun60i_fixed_rate_gate dcxo24M_div32k_clk = {
	.gate		= {
		.enable	= BIT(16),
		.common	= {
			.reg		= 0x060,
			.hw.init	= CLK_HW_INIT("dcxo24M-div32k", "dcxo",
					      &sun60i_fixed_rate_gate_ops,
					      0),
		},
	},
	.fixed_rate	= 32768,
};

static CLK_FIXED_FACTOR(rtc_1k_clk, "rtc-1k", "rtc32k", 32, 1, 0);

static struct sun60i_special_gate dcxo_wakeup_clk = {
	.gate		= {
		.enable	= BIT(31),
		.common	= {
			.reg		= 0x160,
			.hw.init	= CLK_HW_INIT("dcxo-wakeup", "dcxo",
					      &sun60i_special_gate_ops,
					      0),
		},
	},
	.key_reg	= 0x15c,
	.key_value	= 0x16AA,
	.reverse	= true,
};

static const struct clk_parent_data dcxo_parents[] = {
	{ .fw_name = "dcxo24M", .name = "dcxo24M" },
	{ .fw_name = "dcxo19_2M", .name = "dcxo19_2M" },
	{ .fw_name = "dcxo26M", .name = "dcxo26M" },
	{ .fw_name = "dcxo24M", .name = "dcxo24M" },
};

static const struct clk_parent_data osc32k_parents[] = {
	{ .hw = &iosc_div32k_clk.hw },
	{ .hw = &ext32k_gate_clk.gate.common.hw },
};

static const struct clk_parent_data rtc32k_clk_parents[] = {
	{ .fw_name = "osc32k", .name = "osc32k" },
	{ .hw = &dcxo24M_div32k_clk.gate.common.hw },
};

static const struct clk_parent_data rtc_32k_fanout_clk_parents[] = {
	{ .fw_name = "rtc32k", .name = "rtc32k" },
	{ .fw_name = "osc32k", .name = "osc32k" },
	{ .hw = &dcxo24M_div32k_clk.gate.common.hw },
};
static struct ccu_mux osc32k_clk = {
	.enable	= BIT(0),
	.mux	= _SUNXI_CCU_MUX(0, 1),
	.common	= {
		.reg		= 0x000,
		.features	= CCU_FEATURE_KEY_FIELD,
		.hw.init	= CLK_HW_INIT_PARENTS_DATA("osc32k",
							   osc32k_parents,
							   &ccu_mux_ops,
							   0),
	},
};

static struct ccu_mux rtc32k_clk = {
	.enable	= BIT(0),
	.mux	= _SUNXI_CCU_MUX(1, 1),
	.common	= {
		.reg		= 0x000,
		.features	= CCU_FEATURE_KEY_FIELD,
		.hw.init	= CLK_HW_INIT_PARENTS_DATA("rtc32k",
							   rtc32k_clk_parents,
							   &ccu_mux_ops,
							   0),
	},
};

static SUNXI_CCU_MUX_DATA_WITH_GATE(rtc_32k_fanout_clk, "rtc-32k-fanout", rtc_32k_fanout_clk_parents, 0x060, 1, 2, BIT(0), 0);

static SUNXI_CCU_MUX_DATA(dcxo_clk, "dcxo", dcxo_parents, 0x160, 14, 2, CLK_SET_RATE_NO_REPARENT);

static struct ccu_common *sun60i_a733_rtc_ccu_clks[] = {
	&iosc_clk.common,
	&ext32k_gate_clk.gate.common,
	&osc32k_clk.common,
	&dcxo24M_div32k_clk.gate.common,
	&rtc32k_clk.common,
	&rtc_32k_fanout_clk.common,
	&dcxo_clk.common,
	&dcxo_wakeup_clk.gate.common,
};

static struct clk_hw_onecell_data sun60i_a733_rtc_ccu_hw_clks = {
	.num	= CLK_RTC_NUMBER,
	.hws	= {
	[CLK_IOSC]	= &iosc_clk.common.hw,
	[CLK_EXT32K_GATE]	= &ext32k_gate_clk.gate.common.hw,
	[CLK_IOSC_DIV32K]	= &iosc_div32k_clk.hw,
	[CLK_OSC32K]	= &osc32k_clk.common.hw,
	[CLK_DCXO24M_DIV32K]	= &dcxo24M_div32k_clk.gate.common.hw,
	[CLK_RTC32K]	= &rtc32k_clk.common.hw,
	[CLK_RTC_1K]	= &rtc_1k_clk.hw,
	[CLK_RTC_32K_FANOUT]	= &rtc_32k_fanout_clk.common.hw,
	[CLK_DCXO]	= &dcxo_clk.common.hw,
	[CLK_RTC_DCXO_WAKEUP]	= &dcxo_wakeup_clk.gate.common.hw,
	},
};

static const struct sunxi_ccu_desc sun60i_a733_rtc_ccu_desc = {
	.ccu_clks	= sun60i_a733_rtc_ccu_clks,
	.num_ccu_clks	= ARRAY_SIZE(sun60i_a733_rtc_ccu_clks),

	.hw_clks	= &sun60i_a733_rtc_ccu_hw_clks,

	.resets		= NULL,
	.num_resets	= 0,
};

static int sun60i_a733_rtc_ccu_probe(struct platform_device *pdev)
{
	void __iomem *reg;
	int ret;

	struct resource *res;

	res = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!res)
		return -EINVAL;

	reg = devm_ioremap(&pdev->dev, res->start, resource_size(res));
	if (!reg)
		return -ENOMEM;

	sun60i_a733_rtc_ccu_clock_source_init(&pdev->dev, reg);
	ret = devm_sunxi_ccu_probe(&pdev->dev, reg, &sun60i_a733_rtc_ccu_desc);
	if (ret)
		return ret;

	return 0;
}

static const struct of_device_id sun60i_a733_rtc_ccu_ids[] = {
	{ .compatible = "allwinner,sun60i-a733-rtc-ccu" },
	{ }
};
MODULE_DEVICE_TABLE(of, sun60i_a733_rtc_ccu_ids);

static struct platform_driver sun60i_a733_rtc_ccu_driver = {
	.probe	= sun60i_a733_rtc_ccu_probe,
	.driver	= {
		.name			= "sun60i-a733-rtc-ccu",
		.suppress_bind_attrs	= true,
		.of_match_table		= sun60i_a733_rtc_ccu_ids,
	},
};
#ifdef MODULE
module_platform_driver(sun60i_a733_rtc_ccu_driver);
#else
static int __init sun60i_a733_rtc_ccu_driver_init(void)
{
	return platform_driver_register(&sun60i_a733_rtc_ccu_driver);
}
core_initcall(sun60i_a733_rtc_ccu_driver_init);
#endif

MODULE_IMPORT_NS("SUNXI_CCU");
MODULE_DESCRIPTION("Support for the Allwinner A733 RTC_CCU CCU");
MODULE_LICENSE("GPL");
