// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (C) 2026 Alexander Grec
 *
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: generators/generate_ccu.py --domain cpupll
 * Source data:  /home/alex/Documents/porting/projects/sun60iw2-upstream/generators/data/ccu-cpupll-extracted.json
 */

#include <linux/clk-provider.h>
#include <linux/io.h>
#include <linux/module.h>
#include <linux/platform_device.h>
#include <dt-bindings/clock/sun60i-a733-cpupll-ccu.h>


#include "../clk.h"

#include "ccu_common.h"
#include "ccu_reset.h"

#include "ccu_div.h"
#include "ccu_gate.h"
#include "ccu_mp.h"
#include "ccu_nm.h"
#include "ccu_nkmp.h"
#include "ccu_mux.h"

static struct ccu_nm pll_cpu_back_clk = {
	.enable		= BIT(31),
	.lock		= BIT(28),
	.n		= _SUNXI_CCU_MULT_OFFSET_MIN_MAX(8, 8, 0, 53, 105),
	.m		= _SUNXI_CCU_DIV(0, 4),
	.min_rate	= 159000000,
	.max_rate	= 2520000000,
	.common		= {
		.reg		= 0x000,
		.features	= CCU_FEATURE_CLEAR_MOD,
		.clear		= BIT(26),
		.hw.init	= CLK_HW_INIT("pll-cpu-back", "dcxo", &ccu_nm_ops,
					      CLK_SET_RATE_UNGATE | CLK_IS_CRITICAL),
	},
};

static struct ccu_nkmp pll_cpu_l_clk = {
	.enable		= BIT(31),
	.lock		= BIT(28),
	.p_reg		= 0x101c,
	.n		= _SUNXI_CCU_MULT_OFFSET_MIN_MAX(8, 8, 0, 28, 94),
	.m		= _SUNXI_CCU_DIV(0, 0),
	.p		= _SUNXI_CCU_DIV(16, 2),
	.max_rate	= 2256000000,
	.common		= {
		.reg		= 0x1000,
		.features	= CCU_FEATURE_CLEAR_MOD,
		.clear		= BIT(26),
		.hw.init	= CLK_HW_INIT("pll-cpu-l", "dcxo", &ccu_nkmp_ops,
					      CLK_SET_RATE_UNGATE | CLK_IS_CRITICAL),
	},
};

static struct ccu_nkmp pll_cpu_b_clk = {
	.enable		= BIT(31),
	.lock		= BIT(28),
	.p_reg		= 0x201c,
	.n		= _SUNXI_CCU_MULT_OFFSET_MIN_MAX(8, 8, 0, 28, 94),
	.m		= _SUNXI_CCU_DIV(0, 0),
	.p		= _SUNXI_CCU_DIV(16, 2),
	.max_rate	= 2256000000,
	.common		= {
		.reg		= 0x2000,
		.features	= CCU_FEATURE_CLEAR_MOD,
		.clear		= BIT(26),
		.hw.init	= CLK_HW_INIT("pll-cpu-b", "dcxo", &ccu_nkmp_ops,
					      CLK_SET_RATE_UNGATE | CLK_IS_CRITICAL),
	},
};

static struct ccu_nkmp pll_cpu_dsu_clk = {
	.enable		= BIT(31),
	.lock		= BIT(28),
	.p_reg		= 0x301c,
	.n		= _SUNXI_CCU_MULT_OFFSET_MIN_MAX(8, 8, 0, 28, 94),
	.m		= _SUNXI_CCU_DIV(0, 0),
	.p		= _SUNXI_CCU_DIV(16, 2),
	.max_rate	= 2256000000,
	.common		= {
		.reg		= 0x3000,
		.features	= CCU_FEATURE_CLEAR_MOD,
		.clear		= BIT(26),
		.hw.init	= CLK_HW_INIT("pll-cpu-dsu", "dcxo", &ccu_nkmp_ops,
					      CLK_SET_RATE_UNGATE | CLK_IS_CRITICAL),
	},
};

static const struct clk_parent_data cpu_b_parents[] = {
	{ .fw_name = "dcxo", .name = "dcxo" },
	{ .fw_name = "dcxo", .name = "dcxo" },
	{ .fw_name = "dcxo", .name = "dcxo" },
	{ .hw = &pll_cpu_b_clk.common.hw },
	{ .fw_name = "pll-peri0-2x", .name = "pll-peri0-2x" },
	{ .hw = &pll_cpu_back_clk.common.hw },
};

static const struct clk_parent_data cpu_dsu_parents[] = {
	{ .fw_name = "dcxo", .name = "dcxo" },
	{ .fw_name = "dcxo", .name = "dcxo" },
	{ .fw_name = "dcxo", .name = "dcxo" },
	{ .hw = &pll_cpu_dsu_clk.common.hw },
	{ .fw_name = "pll-peri0-2x", .name = "pll-peri0-2x" },
	{ .hw = &pll_cpu_back_clk.common.hw },
};

static const struct clk_parent_data cpu_l_parents[] = {
	{ .fw_name = "dcxo", .name = "dcxo" },
	{ .fw_name = "dcxo", .name = "dcxo" },
	{ .fw_name = "dcxo", .name = "dcxo" },
	{ .hw = &pll_cpu_l_clk.common.hw },
	{ .fw_name = "pll-peri0-2x", .name = "pll-peri0-2x" },
	{ .hw = &pll_cpu_back_clk.common.hw },
};
static SUNXI_CCU_MUX_DATA(cpu_l_clk, "cpu_l", cpu_l_parents, 0x101c, 24, 3, CLK_SET_RATE_PARENT | CLK_IS_CRITICAL);

static SUNXI_CCU_MUX_DATA(cpu_b_clk, "cpu_b", cpu_b_parents, 0x201c, 24, 3, CLK_SET_RATE_PARENT | CLK_IS_CRITICAL);

static SUNXI_CCU_MUX_DATA(cpu_dsu_clk, "cpu_dsu", cpu_dsu_parents, 0x301c, 24, 3, CLK_SET_RATE_PARENT | CLK_IS_CRITICAL);

static struct ccu_common *sun60i_a733_cpupll_ccu_clks[] = {
	&pll_cpu_back_clk.common,
	&pll_cpu_l_clk.common,
	&pll_cpu_b_clk.common,
	&pll_cpu_dsu_clk.common,
	&cpu_l_clk.common,
	&cpu_b_clk.common,
	&cpu_dsu_clk.common,
};

static struct clk_hw_onecell_data sun60i_a733_cpupll_ccu_hw_clks = {
	.num	= CLK_CPUPLL_NUMBER,
	.hws	= {
	[CLK_PLL_CPU_BACK]	= &pll_cpu_back_clk.common.hw,
	[CLK_PLL_CPU_L]	= &pll_cpu_l_clk.common.hw,
	[CLK_PLL_CPU_B]	= &pll_cpu_b_clk.common.hw,
	[CLK_PLL_CPU_DSU]	= &pll_cpu_dsu_clk.common.hw,
	[CLK_CPU_L]	= &cpu_l_clk.common.hw,
	[CLK_CPU_B]	= &cpu_b_clk.common.hw,
	[CLK_CPU_DSU]	= &cpu_dsu_clk.common.hw,
	},
};

static const struct sunxi_ccu_desc sun60i_a733_cpupll_ccu_desc = {
	.ccu_clks	= sun60i_a733_cpupll_ccu_clks,
	.num_ccu_clks	= ARRAY_SIZE(sun60i_a733_cpupll_ccu_clks),

	.hw_clks	= &sun60i_a733_cpupll_ccu_hw_clks,

	.resets		= NULL,
	.num_resets	= 0,
};

static int sun60i_a733_cpupll_ccu_probe(struct platform_device *pdev)
{
	void __iomem *reg;
	int ret;

	reg = devm_platform_ioremap_resource(pdev, 0);
	if (IS_ERR(reg))
		return PTR_ERR(reg);

	ret = devm_sunxi_ccu_probe(&pdev->dev, reg, &sun60i_a733_cpupll_ccu_desc);
	if (ret)
		return ret;

	return 0;
}

static const struct of_device_id sun60i_a733_cpupll_ccu_ids[] = {
	{ .compatible = "allwinner,sun60i-a733-cpupll-ccu" },
	{ }
};
MODULE_DEVICE_TABLE(of, sun60i_a733_cpupll_ccu_ids);

static struct platform_driver sun60i_a733_cpupll_ccu_driver = {
	.probe	= sun60i_a733_cpupll_ccu_probe,
	.driver	= {
		.name			= "sun60i-a733-cpupll-ccu",
		.suppress_bind_attrs	= true,
		.of_match_table		= sun60i_a733_cpupll_ccu_ids,
	},
};
module_platform_driver(sun60i_a733_cpupll_ccu_driver);

MODULE_IMPORT_NS("SUNXI_CCU");
MODULE_DESCRIPTION("Support for the Allwinner A733 CPUPLL_CCU CCU");
MODULE_LICENSE("GPL");
