// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (C) 2026 Alexander Grec
 *
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: generators/generate_ccu.py
 * Source data:  generators/data/ccu-main.json + ccu-main-extracted.json
 */

#include <linux/clk-provider.h>
#include <linux/io.h>
#include <linux/module.h>
#include <linux/platform_device.h>

#include <dt-bindings/clock/sun60i-a733-ccu.h>
#include <dt-bindings/reset/sun60i-a733-ccu.h>

#include "../clk.h"

#include "ccu_common.h"
#include "ccu_reset.h"

#include "ccu_div.h"
#include "ccu_gate.h"
#include "ccu_mp.h"
#include "ccu_nm.h"
#include "ccu_nkmp.h"
#include "ccu_mux.h"

static const struct clk_parent_data osc24M[] = {
	{ .fw_name = "hosc" },
};

struct sun60i_key_gate {
	struct ccu_gate gate;
	u32 key_value;
};

static inline struct sun60i_key_gate *hw_to_sun60i_key_gate(struct clk_hw *hw)
{
	struct ccu_gate *cg = hw_to_ccu_gate(hw);

	return container_of(cg, struct sun60i_key_gate, gate);
}

static int sun60i_key_gate_enable(struct clk_hw *hw)
{
	struct sun60i_key_gate *kg = hw_to_sun60i_key_gate(hw);
	struct ccu_common *common = &kg->gate.common;
	unsigned long flags;
	u32 reg;

	spin_lock_irqsave(common->lock, flags);
	reg = readl(common->base + common->reg);
	reg |= kg->key_value;
	reg |= kg->gate.enable;
	if (common->features & CCU_FEATURE_UPDATE_BIT)
		reg |= CCU_SUNXI_UPDATE_BIT;
	writel(reg, common->base + common->reg);
	spin_unlock_irqrestore(common->lock, flags);

	return 0;
}

static void sun60i_key_gate_disable(struct clk_hw *hw)
{
	struct sun60i_key_gate *kg = hw_to_sun60i_key_gate(hw);
	struct ccu_common *common = &kg->gate.common;
	unsigned long flags;
	u32 reg;

	spin_lock_irqsave(common->lock, flags);
	reg = readl(common->base + common->reg);
	reg |= kg->key_value;
	reg &= ~kg->gate.enable;
	if (common->features & CCU_FEATURE_UPDATE_BIT)
		reg |= CCU_SUNXI_UPDATE_BIT;
	writel(reg, common->base + common->reg);
	spin_unlock_irqrestore(common->lock, flags);
}

static int sun60i_key_gate_is_enabled(struct clk_hw *hw)
{
	struct sun60i_key_gate *kg = hw_to_sun60i_key_gate(hw);

	return ccu_gate_helper_is_enabled(&kg->gate.common, kg->gate.enable);
}

static unsigned long sun60i_key_gate_recalc_rate(struct clk_hw *hw,
						 unsigned long parent_rate)
{
	return parent_rate;
}

static int sun60i_key_gate_determine_rate(struct clk_hw *hw,
					  struct clk_rate_request *req)
{
	if (clk_hw_get_flags(hw) & CLK_SET_RATE_PARENT)
		req->best_parent_rate = clk_hw_round_rate(clk_hw_get_parent(hw), req->rate);

	req->rate = req->best_parent_rate;
	return 0;
}

static int sun60i_key_gate_set_rate(struct clk_hw *hw, unsigned long rate,
				    unsigned long parent_rate)
{
	return 0;
}

static const struct clk_ops sun60i_key_gate_ops = {
	.disable	= sun60i_key_gate_disable,
	.enable		= sun60i_key_gate_enable,
	.is_enabled	= sun60i_key_gate_is_enabled,
	.determine_rate	= sun60i_key_gate_determine_rate,
	.set_rate	= sun60i_key_gate_set_rate,
	.recalc_rate	= sun60i_key_gate_recalc_rate,
};

static struct ccu_nm pll_ref_clk = {
	.enable		= BIT(27),
	.lock		= BIT(28),
	.n		= _SUNXI_CCU_MULT_MIN(8, 8, 11),
	.m		= _SUNXI_CCU_DIV(1, 1),
	.common		= {
		.reg		= 0x000,
		.hw.init	= CLK_HW_INIT("pll-ref", "dcxo", &ccu_nm_ops,
					      CLK_SET_RATE_GATE),
	},
};

static struct ccu_nm pll_ddr_clk = {
	.enable		= BIT(27),
	.lock		= BIT(28),
	.n		= _SUNXI_CCU_MULT_MIN(8, 8, 11),
	.m		= _SUNXI_CCU_DIV(1, 1),
	.common		= {
		.reg		= 0x020,
		.hw.init	= CLK_HW_INIT("pll-ddr", "pll-ref", &ccu_nm_ops,
					      CLK_SET_RATE_GATE),
	},
};

static struct ccu_nm pll_peri0_clk = {
	.enable		= BIT(27),
	.lock		= BIT(28),
	.n		= _SUNXI_CCU_MULT_MIN(8, 8, 11),
	.m		= _SUNXI_CCU_DIV(1, 1),
	.common		= {
		.reg		= 0x0a0,
		.hw.init	= CLK_HW_INIT("pll-peri0", "pll-ref", &ccu_nm_ops,
					      CLK_SET_RATE_GATE),
	},
};

static struct ccu_nm pll_peri1_clk = {
	.enable		= BIT(27),
	.lock		= BIT(28),
	.n		= _SUNXI_CCU_MULT_MIN(8, 8, 11),
	.m		= _SUNXI_CCU_DIV(1, 1),
	.common		= {
		.reg		= 0x0c0,
		.hw.init	= CLK_HW_INIT("pll-peri1", "pll-ref", &ccu_nm_ops,
					      CLK_SET_RATE_GATE),
	},
};

static struct ccu_nm pll_gpu0_clk = {
	.enable		= BIT(27),
	.lock		= BIT(28),
	.n		= _SUNXI_CCU_MULT_MIN(8, 8, 11),
	.m		= _SUNXI_CCU_DIV(1, 1),
	.common		= {
		.reg		= 0x0e0,
		.hw.init	= CLK_HW_INIT("pll-gpu0", "pll-ref", &ccu_nm_ops,
					      CLK_SET_RATE_GATE),
	},
};

static struct ccu_nm pll_video0_clk = {
	.enable		= BIT(27),
	.lock		= BIT(28),
	.n		= _SUNXI_CCU_MULT_MIN(8, 8, 11),
	.m		= _SUNXI_CCU_DIV(1, 1),
	.common		= {
		.reg		= 0x120,
		.hw.init	= CLK_HW_INIT("pll-video0", "pll-ref", &ccu_nm_ops,
					      CLK_SET_RATE_GATE),
	},
};

static struct ccu_nm pll_video1_clk = {
	.enable		= BIT(27),
	.lock		= BIT(28),
	.n		= _SUNXI_CCU_MULT_MIN(8, 8, 11),
	.m		= _SUNXI_CCU_DIV(1, 1),
	.common		= {
		.reg		= 0x140,
		.hw.init	= CLK_HW_INIT("pll-video1", "pll-ref", &ccu_nm_ops,
					      CLK_SET_RATE_GATE),
	},
};

static struct ccu_nm pll_video2_clk = {
	.enable		= BIT(27),
	.lock		= BIT(28),
	.n		= _SUNXI_CCU_MULT_MIN(8, 8, 11),
	.m		= _SUNXI_CCU_DIV(1, 1),
	.common		= {
		.reg		= 0x160,
		.hw.init	= CLK_HW_INIT("pll-video2", "pll-ref", &ccu_nm_ops,
					      CLK_SET_RATE_GATE),
	},
};

static struct ccu_nm pll_ve0_clk = {
	.enable		= BIT(27),
	.lock		= BIT(28),
	.n		= _SUNXI_CCU_MULT_MIN(8, 8, 11),
	.m		= _SUNXI_CCU_DIV(1, 1),
	.common		= {
		.reg		= 0x220,
		.hw.init	= CLK_HW_INIT("pll-ve0", "pll-ref", &ccu_nm_ops,
					      CLK_SET_RATE_GATE),
	},
};

static struct ccu_nm pll_ve1_clk = {
	.enable		= BIT(27),
	.lock		= BIT(28),
	.n		= _SUNXI_CCU_MULT_MIN(8, 8, 11),
	.m		= _SUNXI_CCU_DIV(1, 1),
	.common		= {
		.reg		= 0x240,
		.hw.init	= CLK_HW_INIT("pll-ve1", "pll-ref", &ccu_nm_ops,
					      CLK_SET_RATE_GATE),
	},
};

static struct ccu_nm pll_audio0_4x_clk = {
	.enable		= BIT(27),
	.lock		= BIT(28),
	.n		= _SUNXI_CCU_MULT_MIN(8, 8, 11),
	.m		= _SUNXI_CCU_DIV(1, 1),
	.common		= {
		.reg		= 0x260,
		.hw.init	= CLK_HW_INIT("pll-audio0-4x", "pll-ref", &ccu_nm_ops,
					      CLK_SET_RATE_GATE),
	},
};

static struct ccu_nm pll_audio1_clk = {
	.enable		= BIT(27),
	.lock		= BIT(28),
	.n		= _SUNXI_CCU_MULT_MIN(8, 8, 11),
	.m		= _SUNXI_CCU_DIV(1, 1),
	.common		= {
		.reg		= 0x280,
		.hw.init	= CLK_HW_INIT("pll-audio1", "pll-ref", &ccu_nm_ops,
					      CLK_SET_RATE_GATE),
	},
};

static struct ccu_nm pll_npu_clk = {
	.enable		= BIT(27),
	.lock		= BIT(28),
	.n		= _SUNXI_CCU_MULT_MIN(8, 8, 11),
	.m		= _SUNXI_CCU_DIV(1, 1),
	.common		= {
		.reg		= 0x2a0,
		.hw.init	= CLK_HW_INIT("pll-npu", "pll-ref", &ccu_nm_ops,
					      CLK_SET_RATE_GATE),
	},
};

static struct ccu_nm pll_de_clk = {
	.enable		= BIT(27),
	.lock		= BIT(28),
	.n		= _SUNXI_CCU_MULT_MIN(8, 8, 11),
	.m		= _SUNXI_CCU_DIV(1, 1),
	.common		= {
		.reg		= 0x2e0,
		.hw.init	= CLK_HW_INIT("pll-de", "pll-ref", &ccu_nm_ops,
					      CLK_SET_RATE_GATE),
	},
};

static SUNXI_CCU_M(pll_peri0_2x_clk, "pll-peri0-2x", "pll-peri0", 0x0a0, 20, 3, 0);

static SUNXI_CCU_M(pll_peri0_800m_clk, "pll-peri0-800m", "pll-peri0", 0x0a0, 16, 3, 0);

static SUNXI_CCU_M(pll_peri0_480m_clk, "pll-peri0-480m", "pll-peri0", 0x0a0, 2, 3, 0);

static CLK_FIXED_FACTOR(pll_peri0_600m_clk, "pll-peri0-600m", "pll-peri0-2x", 1, 2, 0);

static CLK_FIXED_FACTOR(pll_peri0_400m_clk, "pll-peri0-400m", "pll-peri0-2x", 1, 3, 0);

static CLK_FIXED_FACTOR(pll_peri0_300m_clk, "pll-peri0-300m", "pll-peri0-600m", 1, 2, 0);

static CLK_FIXED_FACTOR(pll_peri0_200m_clk, "pll-peri0-200m", "pll-peri0-400m", 1, 2, 0);

static CLK_FIXED_FACTOR(pll_peri0_160m_clk, "pll-peri0-160m", "pll-peri0-480m", 1, 3, 0);

static CLK_FIXED_FACTOR(pll_peri0_150m_clk, "pll-peri0-150m", "pll-peri0-300m", 1, 2, 0);

static SUNXI_CCU_M(pll_peri1_2x_clk, "pll-peri1-2x", "pll-peri1", 0x0c0, 20, 3, 0);

static SUNXI_CCU_M(pll_peri1_800m_clk, "pll-peri1-800m", "pll-peri1", 0x0c0, 16, 3, 0);

static SUNXI_CCU_M(pll_peri1_480m_clk, "pll-peri1-480m", "pll-peri1", 0x0c0, 2, 3, 0);

static CLK_FIXED_FACTOR(pll_peri1_600m_clk, "pll-peri1-600m", "pll-peri1-2x", 1, 2, 0);

static CLK_FIXED_FACTOR(pll_peri1_400m_clk, "pll-peri1-400m", "pll-peri1-2x", 1, 3, 0);

static CLK_FIXED_FACTOR(pll_peri1_300m_clk, "pll-peri1-300m", "pll-peri1-600m", 1, 2, 0);

static CLK_FIXED_FACTOR(pll_peri1_200m_clk, "pll-peri1-200m", "pll-peri1-400m", 1, 2, 0);

static CLK_FIXED_FACTOR(pll_peri1_160m_clk, "pll-peri1-160m", "pll-peri1-480m", 1, 3, 0);

static CLK_FIXED_FACTOR(pll_peri1_150m_clk, "pll-peri1-150m", "pll-peri1-300m", 1, 2, 0);

static CLK_FIXED_FACTOR(hdmi_cec_clk32k_clk, "hdmi-cec-clk32k", "pll-peri0-2x", 36621, 1, 0);

static SUNXI_CCU_M(pll_video0_4x_clk, "pll-video0-4x", "pll-video0", 0x120, 20, 3, 0);

static SUNXI_CCU_M(pll_video0_3x_clk, "pll-video0-3x", "pll-video0", 0x120, 16, 3, 0);

static SUNXI_CCU_M(pll_video1_4x_clk, "pll-video1-4x", "pll-video1", 0x140, 20, 3, 0);

static SUNXI_CCU_M(pll_video1_3x_clk, "pll-video1-3x", "pll-video1", 0x140, 16, 3, 0);

static SUNXI_CCU_M(pll_video2_4x_clk, "pll-video2-4x", "pll-video2", 0x160, 20, 3, 0);

static SUNXI_CCU_M(pll_video2_3x_clk, "pll-video2-3x", "pll-video2", 0x160, 16, 3, 0);

static SUNXI_CCU_M(pll_audio1_div2_clk, "pll-audio1-div2", "pll-audio1", 0x280, 20, 3, 0);

static SUNXI_CCU_M(pll_audio1_div5_clk, "pll-audio1-div5", "pll-audio1", 0x280, 16, 3, 0);

static SUNXI_CCU_GATE(its_pcie0_aclk_clk, "its-pcie0-aclk", "dcxo", 0x574, BIT(1), 0);

static SUNXI_CCU_GATE(nsi_cfg_clk, "nsi-cfg", "dcxo", 0x584, BIT(0), 0);

static SUNXI_CCU_GATE(iommu0_sys_hclk_clk, "iommu0-sys-hclk", "dcxo", 0x58c, BIT(2), 0);

static SUNXI_CCU_GATE(iommu0_sys_pclk_clk, "iommu0-sys-pclk", "dcxo", 0x58c, BIT(1), 0);

static SUNXI_CCU_GATE(iommu0_sys_mclk_clk, "iommu0-sys-mclk", "dcxo", 0x58c, BIT(0), 0);

static SUNXI_CCU_GATE(msi_lite0_clk, "msi-lite0", "dcxo", 0x594, BIT(0), 0);

static SUNXI_CCU_GATE(msi_lite1_clk, "msi-lite1", "dcxo", 0x59c, BIT(0), 0);

static SUNXI_CCU_GATE(msi_lite2_clk, "msi-lite2", "dcxo", 0x5a4, BIT(0), 0);

static SUNXI_CCU_GATE(iommu1_sys_hclk_clk, "iommu1-sys-hclk", "dcxo", 0x5b4, BIT(2), 0);

static SUNXI_CCU_GATE(iommu1_sys_pclk_clk, "iommu1-sys-pclk", "dcxo", 0x5b4, BIT(1), 0);

static SUNXI_CCU_GATE(iommu1_sys_mclk_clk, "iommu1-sys-mclk", "dcxo", 0x5b4, BIT(0), 0);

static struct sun60i_key_gate cpus_hclk_gate_clk = {
	.gate		= {
		.enable	= BIT(28),
		.common	= {
			.reg		= 0x5c0,
			.hw.init	= CLK_HW_INIT("cpus-hclk-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x10000FF,
};

static struct sun60i_key_gate store_ahb_gate_clk = {
	.gate		= {
		.enable	= BIT(24),
		.common	= {
			.reg		= 0x5c0,
			.hw.init	= CLK_HW_INIT("store-ahb-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x10000FF,
};

static struct sun60i_key_gate msilite0_ahb_gate_clk = {
	.gate		= {
		.enable	= BIT(16),
		.common	= {
			.reg		= 0x5c0,
			.hw.init	= CLK_HW_INIT("msilite0-ahb-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x10000FF,
};

static struct sun60i_key_gate usb_sys_ahb_gate_clk = {
	.gate		= {
		.enable	= BIT(9),
		.common	= {
			.reg		= 0x5c0,
			.hw.init	= CLK_HW_INIT("usb-sys-ahb-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x10000FF,
};

static struct sun60i_key_gate serdes_ahb_gate_clk = {
	.gate		= {
		.enable	= BIT(8),
		.common	= {
			.reg		= 0x5c0,
			.hw.init	= CLK_HW_INIT("serdes-ahb-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x10000FF,
};

static struct sun60i_key_gate gpu0_ahb_gate_clk = {
	.gate		= {
		.enable	= BIT(7),
		.common	= {
			.reg		= 0x5c0,
			.hw.init	= CLK_HW_INIT("gpu0-ahb-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x10000FF,
};

static struct sun60i_key_gate npu_ahb_gate_clk = {
	.gate		= {
		.enable	= BIT(6),
		.common	= {
			.reg		= 0x5c0,
			.hw.init	= CLK_HW_INIT("npu-ahb-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x10000FF,
};

static struct sun60i_key_gate de_ahb_gate_clk = {
	.gate		= {
		.enable	= BIT(5),
		.common	= {
			.reg		= 0x5c0,
			.hw.init	= CLK_HW_INIT("de-ahb-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x10000FF,
};

static struct sun60i_key_gate vid_out1_ahb_gate_clk = {
	.gate		= {
		.enable	= BIT(4),
		.common	= {
			.reg		= 0x5c0,
			.hw.init	= CLK_HW_INIT("vid-out1-ahb-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x10000FF,
};

static struct sun60i_key_gate vid_out0_ahb_gate_clk = {
	.gate		= {
		.enable	= BIT(3),
		.common	= {
			.reg		= 0x5c0,
			.hw.init	= CLK_HW_INIT("vid-out0-ahb-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x10000FF,
};

static struct sun60i_key_gate vid_in_ahb_gate_clk = {
	.gate		= {
		.enable	= BIT(2),
		.common	= {
			.reg		= 0x5c0,
			.hw.init	= CLK_HW_INIT("vid-in-ahb-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x10000FF,
};

static struct sun60i_key_gate ve_enc_ahb_gate_clk = {
	.gate		= {
		.enable	= BIT(1),
		.common	= {
			.reg		= 0x5c0,
			.hw.init	= CLK_HW_INIT("ve-enc-ahb-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x10000FF,
};

static struct sun60i_key_gate ve_ahb_gate_clk = {
	.gate		= {
		.enable	= BIT(0),
		.common	= {
			.reg		= 0x5c0,
			.hw.init	= CLK_HW_INIT("ve-ahb-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x10000FF,
};

static struct sun60i_key_gate msilite2_mbus_gate_clk = {
	.gate		= {
		.enable	= BIT(31),
		.common	= {
			.reg		= 0x5e0,
			.hw.init	= CLK_HW_INIT("msilite2-mbus-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x41055800,
};

static struct sun60i_key_gate store_mbus_gate_clk = {
	.gate		= {
		.enable	= BIT(30),
		.common	= {
			.reg		= 0x5e0,
			.hw.init	= CLK_HW_INIT("store-mbus-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x41055800,
};

static struct sun60i_key_gate msilite0_mbus_gate_clk = {
	.gate		= {
		.enable	= BIT(29),
		.common	= {
			.reg		= 0x5e0,
			.hw.init	= CLK_HW_INIT("msilite0-mbus-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x41055800,
};

static struct sun60i_key_gate serdes_mbus_gate_clk = {
	.gate		= {
		.enable	= BIT(28),
		.common	= {
			.reg		= 0x5e0,
			.hw.init	= CLK_HW_INIT("serdes-mbus-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x41055800,
};

static struct sun60i_key_gate vid_in_mbus_gate_clk = {
	.gate		= {
		.enable	= BIT(24),
		.common	= {
			.reg		= 0x5e0,
			.hw.init	= CLK_HW_INIT("vid-in-mbus-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x41055800,
};

static struct sun60i_key_gate npu_mbus_gate_clk = {
	.gate		= {
		.enable	= BIT(18),
		.common	= {
			.reg		= 0x5e0,
			.hw.init	= CLK_HW_INIT("npu-mbus-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x41055800,
};

static struct sun60i_key_gate gpu0_mbus_gate_clk = {
	.gate		= {
		.enable	= BIT(16),
		.common	= {
			.reg		= 0x5e0,
			.hw.init	= CLK_HW_INIT("gpu0-mbus-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x41055800,
};

static struct sun60i_key_gate ve_dec_mbus_gate_clk = {
	.gate		= {
		.enable	= BIT(14),
		.common	= {
			.reg		= 0x5e0,
			.hw.init	= CLK_HW_INIT("ve-dec-mbus-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x41055800,
};

static struct sun60i_key_gate ve_mbus_gate_clk = {
	.gate		= {
		.enable	= BIT(12),
		.common	= {
			.reg		= 0x5e0,
			.hw.init	= CLK_HW_INIT("ve-mbus-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x41055800,
};

static struct sun60i_key_gate desys_mbus_gate_clk = {
	.gate		= {
		.enable	= BIT(11),
		.common	= {
			.reg		= 0x5e0,
			.hw.init	= CLK_HW_INIT("desys-mbus-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x41055800,
};

static struct sun60i_key_gate iommu1_mbus_gate_clk = {
	.gate		= {
		.enable	= BIT(1),
		.common	= {
			.reg		= 0x5e0,
			.hw.init	= CLK_HW_INIT("iommu1-mbus-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x41055800,
};

static struct sun60i_key_gate iommu0_mbus_gate_clk = {
	.gate		= {
		.enable	= BIT(0),
		.common	= {
			.reg		= 0x5e0,
			.hw.init	= CLK_HW_INIT("iommu0-mbus-gate", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x41055800,
};

static struct sun60i_key_gate ve_dec_mclk_clk = {
	.gate		= {
		.enable	= BIT(18),
		.common	= {
			.reg		= 0x5e4,
			.hw.init	= CLK_HW_INIT("ve-dec-mclk", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x40302,
};

static struct sun60i_key_gate gmac1_mclk_clk = {
	.gate		= {
		.enable	= BIT(12),
		.common	= {
			.reg		= 0x5e4,
			.hw.init	= CLK_HW_INIT("gmac1-mclk", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x40302,
};

static struct sun60i_key_gate gmac0_mclk_clk = {
	.gate		= {
		.enable	= BIT(11),
		.common	= {
			.reg		= 0x5e4,
			.hw.init	= CLK_HW_INIT("gmac0-mclk", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x40302,
};

static struct sun60i_key_gate isp_mclk_clk = {
	.gate		= {
		.enable	= BIT(9),
		.common	= {
			.reg		= 0x5e4,
			.hw.init	= CLK_HW_INIT("isp-mclk", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x40302,
};

static struct sun60i_key_gate csi_mclk_clk = {
	.gate		= {
		.enable	= BIT(8),
		.common	= {
			.reg		= 0x5e4,
			.hw.init	= CLK_HW_INIT("csi-mclk", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x40302,
};

static struct sun60i_key_gate nand_mclk_clk = {
	.gate		= {
		.enable	= BIT(5),
		.common	= {
			.reg		= 0x5e4,
			.hw.init	= CLK_HW_INIT("nand-mclk", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x40302,
};

static struct sun60i_key_gate dma1_mclk_clk = {
	.gate		= {
		.enable	= BIT(3),
		.common	= {
			.reg		= 0x5e4,
			.hw.init	= CLK_HW_INIT("dma1-mclk", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x40302,
};

static struct sun60i_key_gate ce_mclk_clk = {
	.gate		= {
		.enable	= BIT(2),
		.common	= {
			.reg		= 0x5e4,
			.hw.init	= CLK_HW_INIT("ce-mclk", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x40302,
};

static struct sun60i_key_gate ve_mclk_clk = {
	.gate		= {
		.enable	= BIT(1),
		.common	= {
			.reg		= 0x5e4,
			.hw.init	= CLK_HW_INIT("ve-mclk", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x40302,
};

static struct sun60i_key_gate dma0_mclk_clk = {
	.gate		= {
		.enable	= BIT(0),
		.common	= {
			.reg		= 0x5e4,
			.hw.init	= CLK_HW_INIT("dma0-mclk", "dcxo",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x40302,
};

static SUNXI_CCU_GATE(dma0_clk, "dma0", "dcxo", 0x704, BIT(0), 0);

static SUNXI_CCU_GATE(dma1_clk, "dma1", "dcxo", 0x70c, BIT(0), 0);

static SUNXI_CCU_GATE(spinlock_clk, "spinlock", "dcxo", 0x724, BIT(0), 0);

static SUNXI_CCU_GATE(msgbox0_clk, "msgbox0", "dcxo", 0x744, BIT(0), 0);

static SUNXI_CCU_GATE(pwm0_clk, "pwm0", "dcxo", 0x784, BIT(0), 0);

static SUNXI_CCU_GATE(pwm1_clk, "pwm1", "dcxo", 0x78c, BIT(0), 0);

static SUNXI_CCU_GATE(dbgsys_clk, "dbgsys", "dcxo", 0x7a4, BIT(0), 0);

static SUNXI_CCU_GATE(sysdap_clk, "sysdap", "dcxo", 0x7ac, BIT(0), 0);

static SUNXI_CCU_GATE(timer_bus_clk, "timer-bus", "dcxo", 0x850, BIT(0), 0);

static SUNXI_CCU_GATE(de0_gate_clk, "de0-gate", "dcxo", 0xa04, BIT(0), 0);

static SUNXI_CCU_GATE(di_gate_clk, "di-gate", "dcxo", 0xa24, BIT(0), 0);

static SUNXI_CCU_GATE(g2d_gate_clk, "g2d-gate", "dcxo", 0xa44, BIT(0), 0);

static SUNXI_CCU_GATE(eink_gate_clk, "eink-gate", "dcxo", 0xa6c, BIT(0), 0);

static SUNXI_CCU_GATE(ve_dec_gate_clk, "ve-dec-gate", "dcxo", 0xa8c, BIT(2), 0);

static SUNXI_CCU_GATE(ve_enc0_bus_clk, "ve-enc0-bus", "dcxo", 0xa8c, BIT(0), 0);

static SUNXI_CCU_GATE(ce_sys_clk, "ce-sys", "dcxo", 0xac4, BIT(1), 0);

static SUNXI_CCU_GATE(ce_bus_clk, "ce-bus", "dcxo", 0xac4, BIT(0), 0);

static SUNXI_CCU_GATE(npu_gate_clk, "npu-gate", "dcxo", 0xb04, BIT(0), 0);

static SUNXI_CCU_GATE(gpu0_gate_clk, "gpu0-gate", "dcxo", 0xb24, BIT(0), 0);

static SUNXI_CCU_GATE(dram0_gate_clk, "dram0-gate", "dcxo", 0xc0c, BIT(0), 0);

static SUNXI_CCU_GATE(nand0_bus_clk, "nand0-bus", "dcxo", 0xc8c, BIT(0), 0);

static SUNXI_CCU_GATE(smhc0_gate_clk, "smhc0-gate", "dcxo", 0xd0c, BIT(0), 0);

static SUNXI_CCU_GATE(smhc1_gate_clk, "smhc1-gate", "dcxo", 0xd1c, BIT(0), 0);

static SUNXI_CCU_GATE(smhc2_gate_clk, "smhc2-gate", "dcxo", 0xd2c, BIT(0), 0);

static SUNXI_CCU_GATE(smhc3_bus_clk, "smhc3-bus", "dcxo", 0xd3c, BIT(0), 0);

static SUNXI_CCU_GATE(ufs_clk, "ufs", "dcxo", 0xd8c, BIT(0), 0);

static SUNXI_CCU_GATE(uart0_clk, "uart0", "apb-uart", 0xe00, BIT(0), 0);

static SUNXI_CCU_GATE(uart1_clk, "uart1", "apb-uart", 0xe04, BIT(0), 0);

static SUNXI_CCU_GATE(uart2_clk, "uart2", "apb-uart", 0xe08, BIT(0), 0);

static SUNXI_CCU_GATE(uart3_clk, "uart3", "apb-uart", 0xe0c, BIT(0), 0);

static SUNXI_CCU_GATE(uart4_clk, "uart4", "apb-uart", 0xe10, BIT(0), 0);

static SUNXI_CCU_GATE(uart5_clk, "uart5", "apb-uart", 0xe14, BIT(0), 0);

static SUNXI_CCU_GATE(uart6_clk, "uart6", "apb-uart", 0xe18, BIT(0), 0);

static SUNXI_CCU_GATE(twi0_clk, "twi0", "apb1", 0xe80, BIT(0), 0);

static SUNXI_CCU_GATE(twi1_clk, "twi1", "apb1", 0xe84, BIT(0), 0);

static SUNXI_CCU_GATE(twi2_clk, "twi2", "apb1", 0xe88, BIT(0), 0);

static SUNXI_CCU_GATE(twi3_clk, "twi3", "apb1", 0xe8c, BIT(0), 0);

static SUNXI_CCU_GATE(twi4_clk, "twi4", "apb1", 0xe90, BIT(0), 0);

static SUNXI_CCU_GATE(twi5_clk, "twi5", "apb1", 0xe94, BIT(0), 0);

static SUNXI_CCU_GATE(twi6_clk, "twi6", "apb1", 0xe98, BIT(0), 0);

static SUNXI_CCU_GATE(twi7_clk, "twi7", "apb1", 0xe9c, BIT(0), 0);

static SUNXI_CCU_GATE(twi8_clk, "twi8", "apb1", 0xea0, BIT(0), 0);

static SUNXI_CCU_GATE(twi9_clk, "twi9", "apb1", 0xea4, BIT(0), 0);

static SUNXI_CCU_GATE(twi10_clk, "twi10", "apb1", 0xea8, BIT(0), 0);

static SUNXI_CCU_GATE(twi11_clk, "twi11", "apb1", 0xeac, BIT(0), 0);

static SUNXI_CCU_GATE(twi12_clk, "twi12", "apb1", 0xeb0, BIT(0), 0);

static SUNXI_CCU_GATE(spi0_bus_clk, "spi0-bus", "dcxo", 0xf04, BIT(0), 0);

static SUNXI_CCU_GATE(spi1_bus_clk, "spi1-bus", "dcxo", 0xf0c, BIT(0), 0);

static SUNXI_CCU_GATE(spi2_bus_clk, "spi2-bus", "dcxo", 0xf14, BIT(0), 0);

static SUNXI_CCU_GATE(spif_bus_clk, "spif-bus", "dcxo", 0xf1c, BIT(0), 0);

static SUNXI_CCU_GATE(spi3_bus_clk, "spi3-bus", "dcxo", 0xf24, BIT(0), 0);

static SUNXI_CCU_GATE(spi4_bus_clk, "spi4-bus", "dcxo", 0xf2c, BIT(0), 0);

static SUNXI_CCU_GATE(gpadc0_clk, "gpadc0", "dcxo", 0xfc4, BIT(0), 0);

static SUNXI_CCU_GATE(ths0_clk, "ths0", "dcxo", 0xfe4, BIT(0), 0);

static SUNXI_CCU_GATE(irrx_gate_clk, "irrx-gate", "dcxo", 0x1004, BIT(0), 0);

static SUNXI_CCU_GATE(irtx_gate_clk, "irtx-gate", "dcxo", 0x100c, BIT(0), 0);

static SUNXI_CCU_GATE(lradc_clk, "lradc", "dcxo", 0x1024, BIT(0), 0);

static SUNXI_CCU_GATE(sgpio_bus_clk, "sgpio-bus", "dcxo", 0x1064, BIT(0), 0);

static SUNXI_CCU_GATE(lpc_gate_clk, "lpc-gate", "dcxo", 0x1084, BIT(0), 0);

static SUNXI_CCU_GATE(i2spcm0_bus_clk, "i2spcm0-bus", "dcxo", 0x120c, BIT(0), 0);

static SUNXI_CCU_GATE(i2spcm1_bus_clk, "i2spcm1-bus", "dcxo", 0x121c, BIT(0), 0);

static SUNXI_CCU_GATE(i2spcm2_bus_clk, "i2spcm2-bus", "dcxo", 0x122c, BIT(0), 0);

static SUNXI_CCU_GATE(i2spcm3_bus_clk, "i2spcm3-bus", "dcxo", 0x123c, BIT(0), 0);

static SUNXI_CCU_GATE(i2spcm4_bus_clk, "i2spcm4-bus", "dcxo", 0x124c, BIT(0), 0);

static SUNXI_CCU_GATE(owa_bus_clk, "owa-bus", "dcxo", 0x128c, BIT(0), 0);

static SUNXI_CCU_GATE(dmic_bus_clk, "dmic-bus", "dcxo", 0x12cc, BIT(0), 0);

static SUNXI_CCU_GATE(usb_clk, "usb", "dcxo", 0x1300, BIT(31), 0);

static SUNXI_CCU_GATE(usb0_device_clk, "usb0-device", "dcxo", 0x1304, BIT(8), 0);

static SUNXI_CCU_GATE(usb0_ehci_clk, "usb0-ehci", "dcxo", 0x1304, BIT(4), 0);

static SUNXI_CCU_GATE(usb0_ohci_clk, "usb0-ohci", "dcxo", 0x1304, BIT(0), 0);

static SUNXI_CCU_GATE(usb1_clk, "usb1", "dcxo", 0x1308, BIT(31), 0);

static SUNXI_CCU_GATE(usb1_ehci_clk, "usb1-ehci", "dcxo", 0x130c, BIT(4), 0);

static SUNXI_CCU_GATE(usb1_ohci_clk, "usb1-ohci", "dcxo", 0x130c, BIT(0), 0);

static SUNXI_CCU_GATE(gmac0_clk, "gmac0", "dcxo", 0x141c, BIT(0), 0);

static SUNXI_CCU_GATE(gmac1_clk, "gmac1", "dcxo", 0x142c, BIT(0), 0);

static SUNXI_CCU_GATE(vo0_tconlcd0_bus_clk, "vo0-tconlcd0-bus", "dcxo", 0x1504, BIT(0), 0);

static SUNXI_CCU_GATE(vo0_tconlcd1_bus_clk, "vo0-tconlcd1-bus", "dcxo", 0x150c, BIT(0), 0);

static SUNXI_CCU_GATE(vo0_tconlcd2_bus_clk, "vo0-tconlcd2-bus", "dcxo", 0x1514, BIT(0), 0);

static SUNXI_CCU_GATE(dsi0_bus_clk, "dsi0-bus", "dcxo", 0x1584, BIT(0), 0);

static SUNXI_CCU_GATE(dsi1_bus_clk, "dsi1-bus", "dcxo", 0x158c, BIT(0), 0);

static SUNXI_CCU_GATE(tcontv0_clk, "tcontv0", "dcxo", 0x1604, BIT(0), 0);

static SUNXI_CCU_GATE(tcontv1_clk, "tcontv1", "dcxo", 0x160c, BIT(0), 0);

static SUNXI_CCU_GATE(edp_clk, "edp", "dcxo", 0x164c, BIT(0), 0);

static SUNXI_CCU_GATE(hdmi_clk, "hdmi", "dcxo", 0x168c, BIT(0), 0);

static SUNXI_CCU_GATE(hdcp_esm_clk, "hdcp-esm", "pll-peri0-300m", 0x1694, BIT(31), 0);

static SUNXI_CCU_GATE(dpss_top0_clk, "dpss-top0", "dcxo", 0x16c4, BIT(0), 0);

static SUNXI_CCU_GATE(dpss_top1_clk, "dpss-top1", "dcxo", 0x16cc, BIT(0), 0);

static SUNXI_CCU_GATE(ledc_bus_clk, "ledc-bus", "dcxo", 0x1704, BIT(0), 0);

static SUNXI_CCU_GATE(dsc_clk, "dsc", "dcxo", 0x1744, BIT(0), 0);

static SUNXI_CCU_GATE(csi_bus_clk, "csi-bus", "dcxo", 0x1844, BIT(0), 0);

static SUNXI_CCU_GATE(res_dcap_24m_clk, "res-dcap-24m", "dcxo", 0x1a00, BIT(3), 0);

static SUNXI_CCU_GATE(fanout_25m_clk, "fanout-25m", "dcxo", 0x1f30, BIT(3), 0);

static SUNXI_CCU_GATE(fanout_16m_clk, "fanout-16m", "dcxo", 0x1f30, BIT(2), 0);

static SUNXI_CCU_GATE(fanout_12m_clk, "fanout-12m", "dcxo", 0x1f30, BIT(1), 0);

static SUNXI_CCU_GATE(fanout_24m_clk, "fanout-24m", "dcxo", 0x1f30, BIT(0), 0);

static CLK_FIXED_FACTOR(sys12M_clk, "sys12M", "sys24M", 1, 2, 0);

static CLK_FIXED_FACTOR(pll_peri0_16m_clk, "pll-peri0-16m", "pll-peri0-160m", 1, 10, 0);

static CLK_FIXED_FACTOR(pll_peri0_25m_clk, "pll-peri0-25m", "pll-peri0-150m", 1, 6, 0);

static SUNXI_CCU_GATE(pll_ddr_auto_clk, "pll-ddr-auto", "dcxo", 0x1904, BIT(0), 0);

static SUNXI_CCU_GATE(pll_peri0_2x_auto_clk, "pll-peri0-2x-auto", "dcxo", 0x1908, BIT(11), 0);

static SUNXI_CCU_GATE(pll_peri0_800m_auto_clk, "pll-peri0-800m-auto", "dcxo", 0x1908, BIT(10), 0);

static SUNXI_CCU_GATE(pll_peri0_600m_auto_clk, "pll-peri0-600m-auto", "dcxo", 0x1908, BIT(9), 0);

static SUNXI_CCU_GATE(pll_peri0_480m_all_auto_clk, "pll-peri0-480m-all-auto", "dcxo", 0x1908, BIT(8), 0);

static SUNXI_CCU_GATE(pll_peri0_480m_auto_clk, "pll-peri0-480m-auto", "dcxo", 0x1908, BIT(7), 0);

static SUNXI_CCU_GATE(pll_peri0_160m_auto_clk, "pll-peri0-160m-auto", "dcxo", 0x1908, BIT(6), 0);

static SUNXI_CCU_GATE(pll_peri0_300m_all_auto_clk, "pll-peri0-300m-all-auto", "dcxo", 0x1908, BIT(5), 0);

static SUNXI_CCU_GATE(pll_peri0_300m_auto_clk, "pll-peri0-300m-auto", "dcxo", 0x1908, BIT(4), 0);

static SUNXI_CCU_GATE(pll_peri0_150m_auto_clk, "pll-peri0-150m-auto", "dcxo", 0x1908, BIT(3), 0);

static SUNXI_CCU_GATE(pll_peri0_400m_all_auto_clk, "pll-peri0-400m-all-auto", "dcxo", 0x1908, BIT(2), 0);

static SUNXI_CCU_GATE(pll_peri0_400m_auto_clk, "pll-peri0-400m-auto", "dcxo", 0x1908, BIT(1), 0);

static SUNXI_CCU_GATE(pll_peri0_200m_auto_clk, "pll-peri0-200m-auto", "dcxo", 0x1908, BIT(0), 0);

static SUNXI_CCU_GATE(pll_peri1_800m_auto_clk, "pll-peri1-800m-auto", "dcxo", 0x190c, BIT(11), 0);

static SUNXI_CCU_GATE(pll_peri1_600m_all_auto_clk, "pll-peri1-600m-all-auto", "dcxo", 0x190c, BIT(10), 0);

static SUNXI_CCU_GATE(pll_peri1_600m_auto_clk, "pll-peri1-600m-auto", "dcxo", 0x190c, BIT(9), 0);

static SUNXI_CCU_GATE(pll_peri1_480m_all_auto_clk, "pll-peri1-480m-all-auto", "dcxo", 0x190c, BIT(8), 0);

static SUNXI_CCU_GATE(pll_peri1_480m_auto_clk, "pll-peri1-480m-auto", "dcxo", 0x190c, BIT(7), 0);

static SUNXI_CCU_GATE(pll_peri1_160m_auto_clk, "pll-peri1-160m-auto", "dcxo", 0x190c, BIT(6), 0);

static SUNXI_CCU_GATE(pll_peri1_300m_all_auto_clk, "pll-peri1-300m-all-auto", "dcxo", 0x190c, BIT(5), 0);

static SUNXI_CCU_GATE(pll_peri1_300m_auto_clk, "pll-peri1-300m-auto", "dcxo", 0x190c, BIT(4), 0);

static SUNXI_CCU_GATE(pll_peri1_150m_auto_clk, "pll-peri1-150m-auto", "dcxo", 0x190c, BIT(3), 0);

static SUNXI_CCU_GATE(pll_peri1_400m_all_auto_clk, "pll-peri1-400m-all-auto", "dcxo", 0x190c, BIT(2), 0);

static SUNXI_CCU_GATE(pll_peri1_400m_auto_clk, "pll-peri1-400m-auto", "dcxo", 0x190c, BIT(1), 0);

static SUNXI_CCU_GATE(pll_peri1_200m_auto_clk, "pll-peri1-200m-auto", "dcxo", 0x190c, BIT(0), 0);

static SUNXI_CCU_GATE(pll_video2_3x_auto_clk, "pll-video2-3x-auto", "dcxo", 0x1910, BIT(6), 0);

static SUNXI_CCU_GATE(pll_video1_3x_auto_clk, "pll-video1-3x-auto", "dcxo", 0x1910, BIT(5), 0);

static SUNXI_CCU_GATE(pll_video0_3x_auto_clk, "pll-video0-3x-auto", "dcxo", 0x1910, BIT(4), 0);

static SUNXI_CCU_GATE(pll_video2_4x_auto_clk, "pll-video2-4x-auto", "dcxo", 0x1910, BIT(2), 0);

static SUNXI_CCU_GATE(pll_video1_4x_auto_clk, "pll-video1-4x-auto", "dcxo", 0x1910, BIT(1), 0);

static SUNXI_CCU_GATE(pll_video0_4x_auto_clk, "pll-video0-4x-auto", "dcxo", 0x1910, BIT(0), 0);

static SUNXI_CCU_GATE(pll_gpu0_auto_clk, "pll-gpu0-auto", "dcxo", 0x1914, BIT(0), 0);

static SUNXI_CCU_GATE(pll_ve1_auto_clk, "pll-ve1-auto", "dcxo", 0x1918, BIT(1), 0);

static SUNXI_CCU_GATE(pll_ve0_auto_clk, "pll-ve0-auto", "dcxo", 0x1918, BIT(0), 0);

static SUNXI_CCU_GATE(pll_audio1_div5_auto_clk, "pll-audio1-div5-auto", "dcxo", 0x191c, BIT(2), 0);

static SUNXI_CCU_GATE(pll_audio1_div2_auto_clk, "pll-audio1-div2-auto", "dcxo", 0x191c, BIT(1), 0);

static SUNXI_CCU_GATE(pll_audio1_4x_auto_clk, "pll-audio1-4x-auto", "dcxo", 0x191c, BIT(0), 0);

static SUNXI_CCU_GATE(pll_npu_auto_clk, "pll-npu-auto", "dcxo", 0x1920, BIT(0), 0);

static SUNXI_CCU_GATE(pll_de_3x_auto_clk, "pll-de-3x-auto", "dcxo", 0x1928, BIT(1), 0);

static SUNXI_CCU_GATE(pll_de_4x_auto_clk, "pll-de-4x-auto", "dcxo", 0x1928, BIT(0), 0);

static const struct clk_parent_data apb0_parents[] = {
	{ .fw_name = "sys24M" },
	{ .fw_name = "osc32k" },
	{ .fw_name = "iosc" },
	{ .hw = &pll_peri0_600m_clk.hw },
};

static const struct clk_parent_data apb2jtag_parents[] = {
	{ .fw_name = "sys24M" },
	{ .fw_name = "osc32k" },
	{ .fw_name = "iosc" },
	{ .hw = &pll_peri0_480m_clk.common.hw },
	{ .hw = &pll_peri1_480m_clk.common.hw },
	{ .hw = &pll_peri0_200m_clk.hw },
	{ .hw = &pll_peri1_200m_clk.hw },
};

static const struct clk_parent_data apb_uart_parents[] = {
	{ .fw_name = "sys24M" },
	{ .fw_name = "osc32k" },
	{ .fw_name = "iosc" },
	{ .hw = &pll_peri0_600m_clk.hw },
	{ .hw = &pll_peri0_480m_clk.common.hw },
};

static const struct clk_parent_data avs_parents[] = {
	{ .fw_name = "sys24M" },
	{ .fw_name = "dcxo" },
};

static const struct clk_parent_data bus_debug_parents[] = {
	{ .fw_name = "ahb" },
	{ .fw_name = "apb0" },
	{ .fw_name = "apb1" },
	{ .fw_name = "apb-uart" },
	{ .fw_name = "mbus" },
	{ .fw_name = "nsi" },
	{ .fw_name = "ddr0" },
	{ .hw = &pll_ddr_clk.common.hw },
	{ .fw_name = "dram0" },
};

static const struct clk_parent_data ce_parents[] = {
	{ .fw_name = "sys24M" },
	{ .hw = &pll_peri0_400m_clk.hw },
	{ .hw = &pll_peri0_600m_clk.hw },
};

static const struct clk_parent_data clk27m_fanout_parents[] = {
	{ .hw = &pll_video0_4x_clk.common.hw },
	{ .hw = &pll_video1_4x_clk.common.hw },
	{ .hw = &pll_video2_4x_clk.common.hw },
};

static const struct clk_parent_data clk_fanout_parents[] = {
	{ .fw_name = "apb0" },
};

static const struct clk_parent_data combphy_parents[] = {
	{ .hw = &pll_video0_4x_clk.common.hw },
	{ .hw = &pll_video1_4x_clk.common.hw },
	{ .hw = &pll_video2_4x_clk.common.hw },
	{ .hw = &pll_peri0_2x_clk.common.hw },
	{ .hw = &pll_video0_3x_clk.common.hw },
};

static const struct clk_parent_data cpu_peri_parents[] = {
	{ .fw_name = "sys24M" },
	{ .fw_name = "osc32k" },
	{ .hw = &pll_peri0_600m_clk.hw },
	{ .hw = &pll_peri0_480m_clk.common.hw },
	{ .hw = &pll_peri0_400m_clk.hw },
};

static const struct clk_parent_data csi_master_parents[] = {
	{ .fw_name = "sys24M" },
	{ .hw = &pll_video0_4x_clk.common.hw },
	{ .hw = &pll_video0_3x_clk.common.hw },
	{ .hw = &pll_video1_4x_clk.common.hw },
	{ .hw = &pll_video1_3x_clk.common.hw },
	{ .hw = &pll_video2_4x_clk.common.hw },
	{ .hw = &pll_video2_3x_clk.common.hw },
};

static const struct clk_parent_data csi_parents[] = {
	{ .hw = &pll_video2_4x_clk.common.hw },
	{ .fw_name = "pll-de-4x" },
	{ .hw = &pll_peri0_480m_clk.common.hw },
	{ .hw = &pll_peri0_400m_clk.hw },
	{ .hw = &pll_peri0_600m_clk.hw },
	{ .hw = &pll_video0_4x_clk.common.hw },
	{ .hw = &pll_video1_4x_clk.common.hw },
};

static const struct clk_parent_data de0_parents[] = {
	{ .fw_name = "pll-de-3x" },
	{ .fw_name = "pll-de-4x" },
	{ .hw = &pll_peri0_480m_clk.common.hw },
	{ .hw = &pll_peri0_400m_clk.hw },
	{ .hw = &pll_peri0_300m_clk.hw },
	{ .hw = &pll_video0_4x_clk.common.hw },
	{ .hw = &pll_video2_4x_clk.common.hw },
};

static const struct clk_parent_data di_parents[] = {
	{ .hw = &pll_peri0_600m_clk.hw },
	{ .hw = &pll_peri0_480m_clk.common.hw },
	{ .hw = &pll_peri0_400m_clk.hw },
	{ .hw = &pll_video0_4x_clk.common.hw },
	{ .hw = &pll_video2_4x_clk.common.hw },
};

static const struct clk_parent_data dmic_parents[] = {
	{ .hw = &pll_audio0_4x_clk.common.hw },
	{ .hw = &pll_audio1_div2_clk.common.hw },
	{ .hw = &pll_audio1_div5_clk.common.hw },
};

static const struct clk_parent_data dram0_parents[] = {
	{ .hw = &pll_ddr_clk.common.hw },
	{ .hw = &pll_peri1_800m_clk.common.hw },
	{ .hw = &pll_peri1_600m_clk.hw },
	{ .fw_name = "pll-de-3x" },
	{ .hw = &pll_npu_clk.common.hw },
};

static const struct clk_parent_data dsi_parents[] = {
	{ .fw_name = "sys24M" },
	{ .hw = &pll_peri0_200m_clk.hw },
	{ .hw = &pll_peri0_150m_clk.hw },
};

static const struct clk_parent_data edp_tv_parents[] = {
	{ .hw = &pll_video0_4x_clk.common.hw },
	{ .hw = &pll_video1_4x_clk.common.hw },
	{ .hw = &pll_video2_4x_clk.common.hw },
	{ .hw = &pll_peri0_2x_clk.common.hw },
};

static const struct clk_parent_data eink_panel_parents[] = {
	{ .hw = &pll_video0_4x_clk.common.hw },
	{ .hw = &pll_video0_3x_clk.common.hw },
	{ .hw = &pll_video1_4x_clk.common.hw },
	{ .hw = &pll_video1_3x_clk.common.hw },
	{ .hw = &pll_peri0_300m_clk.hw },
};

static const struct clk_parent_data eink_parents[] = {
	{ .hw = &pll_peri0_480m_clk.common.hw },
	{ .hw = &pll_peri0_400m_clk.hw },
};

static const struct clk_parent_data fanout_clk_parents[] = {
	{ .fw_name = "rtc32k" },
	{ .hw = &sys12M_clk.hw },
	{ .hw = &pll_peri0_16m_clk.hw },
	{ .fw_name = "sys24M" },
	{ .hw = &pll_peri0_25m_clk.hw },
	{ .fw_name = "clk27m-fanout" },
	{ .fw_name = "clk-fanout" },
};

static const struct clk_parent_data g2d_parents[] = {
	{ .hw = &pll_peri0_300m_clk.hw },
	{ .hw = &pll_peri0_400m_clk.hw },
	{ .hw = &pll_video0_4x_clk.common.hw },
	{ .hw = &pll_video2_4x_clk.common.hw },
};

static const struct clk_parent_data gic_parents[] = {
	{ .fw_name = "sys24M" },
	{ .fw_name = "osc32k" },
	{ .hw = &pll_peri0_600m_clk.hw },
	{ .hw = &pll_peri0_480m_clk.common.hw },
	{ .hw = &pll_peri0_400m_clk.hw },
};

static const struct clk_parent_data gmac_ptp_parents[] = {
	{ .fw_name = "sys24M" },
	{ .hw = &pll_peri0_200m_clk.hw },
	{ .fw_name = "dcxo" },
};

static const struct clk_parent_data gpadc0_24m_parents[] = {
	{ .fw_name = "sys24M" },
	{ .fw_name = "dcxo" },
};

static const struct clk_parent_data gpu0_parents[] = {
	{ .fw_name = "pll-gpu" },
	{ .hw = &pll_peri0_800m_clk.common.hw },
	{ .hw = &pll_peri0_600m_clk.hw },
	{ .hw = &pll_peri0_400m_clk.hw },
	{ .hw = &pll_peri0_300m_clk.hw },
	{ .hw = &pll_peri0_200m_clk.hw },
};

static const struct clk_parent_data hdmi_ref_parents[] = {
	{ .fw_name = "osc32k" },
	{ .hw = &hdmi_cec_clk32k_clk.hw },
};

static const struct clk_parent_data hdmi_sfr_parents[] = {
	{ .fw_name = "sys24M" },
	{ .fw_name = "dcxo" },
};

static const struct clk_parent_data hdmi_tv_parents[] = {
	{ .hw = &pll_video0_4x_clk.common.hw },
	{ .hw = &pll_video1_4x_clk.common.hw },
	{ .hw = &pll_video2_4x_clk.common.hw },
	{ .hw = &pll_peri0_2x_clk.common.hw },
};

static const struct clk_parent_data i2spcm2_asrc_parents[] = {
	{ .hw = &pll_audio0_4x_clk.common.hw },
	{ .hw = &pll_audio1_div2_clk.common.hw },
	{ .hw = &pll_audio1_div5_clk.common.hw },
	{ .hw = &pll_peri0_300m_clk.hw },
	{ .hw = &pll_peri1_300m_clk.hw },
};

static const struct clk_parent_data i2spcm3_parents[] = {
	{ .hw = &pll_audio0_4x_clk.common.hw },
	{ .hw = &pll_audio1_div2_clk.common.hw },
	{ .hw = &pll_audio1_div5_clk.common.hw },
	{ .hw = &pll_peri0_200m_clk.hw },
};

static const struct clk_parent_data i2spcm_parents[] = {
	{ .hw = &pll_audio0_4x_clk.common.hw },
	{ .hw = &pll_audio1_div2_clk.common.hw },
	{ .hw = &pll_audio1_div5_clk.common.hw },
	{ .hw = &pll_peri0_200m_clk.hw },
};

static const struct clk_parent_data irrx_parents[] = {
	{ .fw_name = "osc32k" },
	{ .fw_name = "sys24M" },
	{ .fw_name = "dcxo" },
};

static const struct clk_parent_data irtx_parents[] = {
	{ .fw_name = "sys24M" },
	{ .hw = &pll_peri1_600m_clk.hw },
	{ .fw_name = "dcxo" },
};

static const struct clk_parent_data isp_parents[] = {
	{ .hw = &pll_video2_4x_clk.common.hw },
	{ .hw = &pll_peri0_480m_clk.common.hw },
	{ .hw = &pll_peri0_400m_clk.hw },
	{ .hw = &pll_peri0_600m_clk.hw },
	{ .hw = &pll_video0_4x_clk.common.hw },
	{ .hw = &pll_video1_4x_clk.common.hw },
};

static const struct clk_parent_data ledc_parents[] = {
	{ .fw_name = "sys24M" },
	{ .hw = &pll_peri0_600m_clk.hw },
	{ .fw_name = "dcxo" },
};

static const struct clk_parent_data lpc_parents[] = {
	{ .hw = &pll_video0_3x_clk.common.hw },
	{ .hw = &pll_video1_3x_clk.common.hw },
	{ .hw = &pll_video2_3x_clk.common.hw },
	{ .hw = &pll_peri0_300m_clk.hw },
};

static const struct clk_parent_data mbus_parents[] = {
	{ .fw_name = "sys24M" },
	{ .hw = &pll_peri0_600m_clk.hw },
	{ .hw = &pll_ddr_clk.common.hw },
	{ .hw = &pll_peri0_480m_clk.common.hw },
	{ .hw = &pll_peri0_400m_clk.hw },
	{ .hw = &pll_npu_clk.common.hw },
};

static const struct clk_parent_data nand0_clk_parents[] = {
	{ .fw_name = "sys24M" },
	{ .hw = &pll_peri0_400m_clk.hw },
	{ .hw = &pll_peri0_300m_clk.hw },
	{ .hw = &pll_peri1_400m_clk.hw },
	{ .hw = &pll_peri1_300m_clk.hw },
};

static const struct clk_parent_data npu_parents[] = {
	{ .hw = &pll_npu_clk.common.hw },
	{ .hw = &pll_peri0_800m_clk.common.hw },
	{ .hw = &pll_peri0_600m_clk.hw },
	{ .hw = &pll_peri0_480m_clk.common.hw },
	{ .hw = &pll_ve0_clk.common.hw },
	{ .hw = &pll_ve1_clk.common.hw },
	{ .fw_name = "pll-de-3x" },
};

static const struct clk_parent_data nsi_parents[] = {
	{ .fw_name = "sys24M" },
	{ .hw = &pll_ddr_clk.common.hw },
	{ .hw = &pll_peri0_800m_clk.common.hw },
	{ .hw = &pll_peri0_600m_clk.hw },
	{ .hw = &pll_peri0_480m_clk.common.hw },
	{ .fw_name = "pll-de-3x" },
};

static const struct clk_parent_data owa_rx_parents[] = {
	{ .hw = &pll_peri0_200m_clk.hw },
	{ .hw = &pll_peri0_300m_clk.hw },
	{ .hw = &pll_peri0_400m_clk.hw },
};

static const struct clk_parent_data owa_tx_parents[] = {
	{ .hw = &pll_audio0_4x_clk.common.hw },
	{ .hw = &pll_audio1_div2_clk.common.hw },
	{ .hw = &pll_audio1_div5_clk.common.hw },
};

static const struct clk_parent_data pcie0_aux_parents[] = {
	{ .fw_name = "sys24M" },
	{ .fw_name = "osc32k" },
};

static const struct clk_parent_data pcie0_axi_slv_parents[] = {
	{ .hw = &pll_peri0_600m_clk.hw },
	{ .hw = &pll_peri0_600m_clk.hw },
	{ .hw = &pll_peri0_400m_clk.hw },
};

static const struct clk_parent_data serdes_phy_cfg_parents[] = {
	{ .fw_name = "sys24M" },
	{ .hw = &pll_peri0_600m_clk.hw },
};

static const struct clk_parent_data sgpio_parents[] = {
	{ .fw_name = "sys24M" },
	{ .fw_name = "osc32k" },
};

static const struct clk_parent_data smhc2_parents[] = {
	{ .fw_name = "sys24M" },
	{ .hw = &pll_peri0_800m_clk.common.hw },
	{ .hw = &pll_peri0_600m_clk.hw },
	{ .hw = &pll_peri1_800m_clk.common.hw },
	{ .hw = &pll_peri1_600m_clk.hw },
};

static const struct clk_parent_data smhc_parents[] = {
	{ .fw_name = "sys24M" },
	{ .hw = &pll_peri0_400m_clk.hw },
	{ .hw = &pll_peri0_300m_clk.hw },
	{ .hw = &pll_peri1_400m_clk.hw },
	{ .hw = &pll_peri1_300m_clk.hw },
};

static const struct clk_parent_data spi_parents[] = {
	{ .fw_name = "sys24M" },
	{ .hw = &pll_peri0_300m_clk.hw },
	{ .hw = &pll_peri0_200m_clk.hw },
	{ .hw = &pll_peri1_300m_clk.hw },
	{ .hw = &pll_peri1_200m_clk.hw },
	{ .hw = &pll_peri0_480m_clk.common.hw },
	{ .hw = &pll_peri1_480m_clk.common.hw },
	{ .fw_name = "dcxo" },
};

static const struct clk_parent_data spif_parents[] = {
	{ .fw_name = "sys24M" },
	{ .hw = &pll_peri0_400m_clk.hw },
	{ .hw = &pll_peri0_300m_clk.hw },
	{ .hw = &pll_peri1_400m_clk.hw },
	{ .hw = &pll_peri1_300m_clk.hw },
	{ .hw = &pll_peri0_160m_clk.hw },
	{ .hw = &pll_peri1_160m_clk.hw },
	{ .fw_name = "dcxo" },
};

static const struct clk_parent_data timer_clk_parents[] = {
	{ .fw_name = "sys24M" },
	{ .fw_name = "iosc" },
	{ .fw_name = "osc32k" },
	{ .hw = &pll_peri0_200m_clk.hw },
	{ .fw_name = "dcxo" },
};

static const struct clk_parent_data trace_parents[] = {
	{ .fw_name = "sys24M" },
	{ .fw_name = "osc32k" },
	{ .fw_name = "iosc" },
	{ .hw = &pll_peri0_300m_clk.hw },
	{ .hw = &pll_peri0_400m_clk.hw },
};

static const struct clk_parent_data ufs_axi_parents[] = {
	{ .hw = &pll_peri0_300m_clk.hw },
	{ .hw = &pll_peri0_200m_clk.hw },
};

static const struct clk_parent_data ufs_cfg_parents[] = {
	{ .hw = &pll_peri0_480m_clk.common.hw },
	{ .fw_name = "dcxo" },
};

static const struct clk_parent_data usb2_mf_parents[] = {
	{ .fw_name = "sys24M" },
	{ .hw = &pll_peri0_300m_clk.hw },
	{ .fw_name = "dcxo" },
};

static const struct clk_parent_data usb2_suspend_parents[] = {
	{ .fw_name = "osc32k" },
	{ .fw_name = "sys24M" },
};

static const struct clk_parent_data usb2_u2_pipe_parents[] = {
	{ .fw_name = "sys24M" },
	{ .hw = &pll_peri0_480m_clk.common.hw },
	{ .fw_name = "dcxo" },
};

static const struct clk_parent_data usb2_u3_utmi_parents[] = {
	{ .fw_name = "sys24M" },
	{ .hw = &pll_peri0_300m_clk.hw },
	{ .fw_name = "dcxo" },
};

static const struct clk_parent_data usb_ref_parents[] = {
	{ .fw_name = "sys24M" },
	{ .fw_name = "dcxo" },
};

static const struct clk_parent_data ve_dec_parents[] = {
	{ .hw = &pll_ve1_clk.common.hw },
	{ .hw = &pll_ve0_clk.common.hw },
	{ .hw = &pll_peri0_800m_clk.common.hw },
	{ .hw = &pll_peri0_600m_clk.hw },
	{ .hw = &pll_peri0_480m_clk.common.hw },
	{ .fw_name = "pll-de-3x" },
	{ .hw = &pll_npu_clk.common.hw },
};

static const struct clk_parent_data ve_enc0_parents[] = {
	{ .hw = &pll_ve0_clk.common.hw },
	{ .hw = &pll_ve1_clk.common.hw },
	{ .hw = &pll_peri0_800m_clk.common.hw },
	{ .hw = &pll_peri0_600m_clk.hw },
	{ .hw = &pll_peri0_480m_clk.common.hw },
	{ .fw_name = "pll-de-3x" },
	{ .hw = &pll_npu_clk.common.hw },
};

static const struct clk_parent_data vo0_tconlcd_parents[] = {
	{ .hw = &pll_video0_4x_clk.common.hw },
	{ .hw = &pll_video1_4x_clk.common.hw },
	{ .hw = &pll_video2_4x_clk.common.hw },
	{ .hw = &pll_peri0_2x_clk.common.hw },
};
static SUNXI_CCU_M_DATA_WITH_MUX(ahb_clk, "ahb", apb0_parents, 0x500, 24, 2, 0, 5, 0);

static SUNXI_CCU_M_DATA_WITH_MUX(apb0_clk, "apb0", apb0_parents, 0x510, 24, 2, 0, 5, 0);

static SUNXI_CCU_M_DATA_WITH_MUX(apb1_clk, "apb1", apb0_parents, 0x518, 24, 2, 0, 5, 0);

static SUNXI_CCU_M_DATA_WITH_MUX(apb_uart_clk, "apb-uart", apb_uart_parents, 0x538, 24, 3, 0, 5, 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(trace_clk, "trace", trace_parents, 0x540, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(gic_clk, "gic", gic_parents, 0x560, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(cpu_peri_clk, "cpu-peri", cpu_peri_parents, 0x568, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX(timer0_clk, "timer0", timer_clk_parents, 0x800, 0, 3, 24, 3, 0);

static SUNXI_CCU_M_DATA_WITH_MUX(timer1_clk, "timer1", timer_clk_parents, 0x804, 0, 3, 24, 3, 0);

static SUNXI_CCU_M_DATA_WITH_MUX(timer2_clk, "timer2", timer_clk_parents, 0x808, 0, 3, 24, 3, 0);

static SUNXI_CCU_M_DATA_WITH_MUX(timer3_clk, "timer3", timer_clk_parents, 0x80c, 0, 3, 24, 3, 0);

static SUNXI_CCU_M_DATA_WITH_MUX(timer4_clk, "timer4", timer_clk_parents, 0x810, 0, 3, 24, 3, 0);

static SUNXI_CCU_M_DATA_WITH_MUX(timer5_clk, "timer5", timer_clk_parents, 0x814, 0, 3, 24, 3, 0);

static SUNXI_CCU_M_DATA_WITH_MUX(timer6_clk, "timer6", timer_clk_parents, 0x818, 0, 3, 24, 3, 0);

static SUNXI_CCU_M_DATA_WITH_MUX(timer7_clk, "timer7", timer_clk_parents, 0x81c, 0, 3, 24, 3, 0);

static SUNXI_CCU_M_DATA_WITH_MUX(timer8_clk, "timer8", timer_clk_parents, 0x820, 0, 3, 24, 3, 0);

static SUNXI_CCU_M_DATA_WITH_MUX(timer9_clk, "timer9", timer_clk_parents, 0x824, 0, 3, 24, 3, 0);

static SUNXI_CCU_MUX_DATA_WITH_GATE(avs_clk, "avs", avs_parents, 0x880, 24, 3, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(de0_clk, "de0", de0_parents, 0xa00, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(di_clk, "di", di_parents, 0xa20, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(g2d_clk, "g2d", g2d_parents, 0xa40, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(eink_clk, "eink", eink_parents, 0xa60, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(eink_panel_clk, "eink-panel", eink_panel_parents, 0xa64, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(ve_enc0_clk, "ve-enc0", ve_enc0_parents, 0xa80, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(ve_dec_clk, "ve-dec", ve_dec_parents, 0xa88, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(ce_clk, "ce", ce_parents, 0xac0, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(npu_clk, "npu", npu_parents, 0xb00, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX(gpu0_clk, "gpu0", gpu0_parents, 0xb20, 0, 4, 24, 3, 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(nand0_clk0_clk, "nand0-clk0", nand0_clk_parents, 0xc80, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(nand0_clk1_clk, "nand0-clk1", nand0_clk_parents, 0xc84, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_MP_DATA_WITH_MUX_GATE_FEAT(smhc0_clk, "smhc0", smhc_parents, 0xd00, 0, 5, 8, 5, 24, 3, BIT(31), 0, CCU_FEATURE_DUAL_DIV);

static SUNXI_CCU_MP_DATA_WITH_MUX_GATE_FEAT(smhc1_clk, "smhc1", smhc_parents, 0xd10, 0, 5, 8, 5, 24, 3, BIT(31), 0, CCU_FEATURE_DUAL_DIV);

static SUNXI_CCU_MP_DATA_WITH_MUX_GATE_FEAT(smhc2_clk, "smhc2", smhc2_parents, 0xd20, 0, 5, 8, 5, 24, 3, BIT(31), 0, CCU_FEATURE_DUAL_DIV);

static SUNXI_CCU_MP_DATA_WITH_MUX_GATE_FEAT(smhc3_clk, "smhc3", smhc2_parents, 0xd30, 0, 5, 8, 5, 24, 3, BIT(31), 0, CCU_FEATURE_DUAL_DIV);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(ufs_axi_clk, "ufs-axi", ufs_axi_parents, 0xd80, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(ufs_cfg_clk, "ufs-cfg", ufs_cfg_parents, 0xd84, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_MP_DATA_WITH_MUX_GATE_FEAT(spi0_clk, "spi0", spi_parents, 0xf00, 0, 5, 8, 5, 24, 3, BIT(31), 0, CCU_FEATURE_DUAL_DIV);

static SUNXI_CCU_MP_DATA_WITH_MUX_GATE_FEAT(spi1_clk, "spi1", spi_parents, 0xf08, 0, 5, 8, 5, 24, 3, BIT(31), 0, CCU_FEATURE_DUAL_DIV);

static SUNXI_CCU_MP_DATA_WITH_MUX_GATE_FEAT(spi2_clk, "spi2", spi_parents, 0xf10, 0, 5, 8, 5, 24, 3, BIT(31), 0, CCU_FEATURE_DUAL_DIV);

static SUNXI_CCU_MP_DATA_WITH_MUX_GATE_FEAT(spif_clk, "spif", spif_parents, 0xf18, 0, 5, 8, 5, 24, 3, BIT(31), 0, CCU_FEATURE_DUAL_DIV);

static SUNXI_CCU_MP_DATA_WITH_MUX_GATE_FEAT(spi3_clk, "spi3", spi_parents, 0xf20, 0, 5, 8, 5, 24, 3, BIT(31), 0, CCU_FEATURE_DUAL_DIV);

static SUNXI_CCU_MP_DATA_WITH_MUX_GATE_FEAT(spi4_clk, "spi4", spi_parents, 0xf28, 0, 5, 8, 5, 24, 3, BIT(31), 0, CCU_FEATURE_DUAL_DIV);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(gpadc0_24m_clk, "gpadc0-24m", gpadc0_24m_parents, 0xfc0, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(irrx_clk, "irrx", irrx_parents, 0x1000, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(irtx_clk, "irtx", irtx_parents, 0x1008, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(sgpio_clk, "sgpio", sgpio_parents, 0x1060, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(lpc_clk, "lpc", lpc_parents, 0x1080, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(i2spcm0_clk, "i2spcm0", i2spcm_parents, 0x1200, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(i2spcm1_clk, "i2spcm1", i2spcm_parents, 0x1210, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(i2spcm2_clk, "i2spcm2", i2spcm_parents, 0x1220, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(i2spcm2_asrc_clk, "i2spcm2-asrc", i2spcm2_asrc_parents, 0x1224, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(i2spcm3_clk, "i2spcm3", i2spcm3_parents, 0x1230, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(i2spcm4_clk, "i2spcm4", i2spcm3_parents, 0x1240, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(owa_tx_clk, "owa-tx", owa_tx_parents, 0x1280, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(owa_rx_clk, "owa-rx", owa_rx_parents, 0x1284, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(dmic_clk, "dmic", dmic_parents, 0x12c0, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_MUX_DATA_WITH_GATE(usb_ref_clk, "usb-ref", usb_ref_parents, 0x1340, 24, 3, BIT(31), 0);

static SUNXI_CCU_MUX_DATA_WITH_GATE(usb2_u2_ref_clk, "usb2-u2-ref", usb_ref_parents, 0x1348, 24, 3, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(usb2_suspend_clk, "usb2-suspend", usb2_suspend_parents, 0x1350, 24, 1, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(usb2_mf_clk, "usb2-mf", usb2_mf_parents, 0x1354, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(usb2_u3_utmi_clk, "usb2-u3-utmi", usb2_u3_utmi_parents, 0x1360, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(usb2_u2_pipe_clk, "usb2-u2-pipe", usb2_u2_pipe_parents, 0x1364, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(pcie0_aux_clk, "pcie0-aux", pcie0_aux_parents, 0x1380, 24, 1, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(pcie0_axi_slv_clk, "pcie0-axi-slv", pcie0_axi_slv_parents, 0x1384, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(serdes_phy_cfg_clk, "serdes-phy-cfg", serdes_phy_cfg_parents, 0x13c0, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(gmac_ptp_clk, "gmac-ptp", gmac_ptp_parents, 0x1400, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(vo0_tconlcd0_clk, "vo0-tconlcd0", vo0_tconlcd_parents, 0x1500, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(vo0_tconlcd1_clk, "vo0-tconlcd1", vo0_tconlcd_parents, 0x1508, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(vo0_tconlcd2_clk, "vo0-tconlcd2", vo0_tconlcd_parents, 0x1510, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(dsi0_clk, "dsi0", dsi_parents, 0x1580, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(dsi1_clk, "dsi1", dsi_parents, 0x1588, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(combphy0_clk, "combphy0", combphy_parents, 0x15c0, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(combphy1_clk, "combphy1", combphy_parents, 0x15c4, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_MP_DATA_WITH_MUX_GATE_FEAT(edp_tv_clk, "edp-tv", edp_tv_parents, 0x1640, 0, 5, 8, 5, 24, 3, BIT(31), 0, CCU_FEATURE_DUAL_DIV);

static SUNXI_CCU_MUX_DATA_WITH_GATE(hdmi_ref_clk, "hdmi-ref", hdmi_ref_parents, 0x1680, 24, 3, BIT(31), 0);

static SUNXI_CCU_MP_DATA_WITH_MUX_GATE_FEAT(hdmi_tv_clk, "hdmi-tv", hdmi_tv_parents, 0x1684, 0, 5, 8, 5, 24, 3, BIT(31), 0, CCU_FEATURE_DUAL_DIV);

static SUNXI_CCU_MUX_DATA_WITH_GATE(hdmi_sfr_clk, "hdmi-sfr", hdmi_sfr_parents, 0x1690, 24, 3, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(ledc_clk, "ledc", ledc_parents, 0x1700, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_MP_DATA_WITH_MUX_GATE_FEAT(csi_master0_clk, "csi-master0", csi_master_parents, 0x1800, 0, 5, 8, 5, 24, 3, BIT(31), 0, CCU_FEATURE_DUAL_DIV);

static SUNXI_CCU_MP_DATA_WITH_MUX_GATE_FEAT(csi_master1_clk, "csi-master1", csi_master_parents, 0x1804, 0, 5, 8, 5, 24, 3, BIT(31), 0, CCU_FEATURE_DUAL_DIV);

static SUNXI_CCU_MP_DATA_WITH_MUX_GATE_FEAT(csi_master2_clk, "csi-master2", csi_master_parents, 0x1808, 0, 5, 8, 5, 24, 3, BIT(31), 0, CCU_FEATURE_DUAL_DIV);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(csi_clk, "csi", csi_parents, 0x1840, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(isp_clk, "isp", isp_parents, 0x1860, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(apb2jtag_clk, "apb2jtag", apb2jtag_parents, 0x1c00, 24, 3, 0, 5, BIT(31), 0);

static SUNXI_CCU_MP_DATA_WITH_MUX_GATE_FEAT(clk27m_fanout_clk, "clk27m_fanout", clk27m_fanout_parents, 0x1f34, 0, 5, 8, 5, 24, 2, BIT(31), 0, CCU_FEATURE_DUAL_DIV);

static SUNXI_CCU_MP_DATA_WITH_MUX_GATE_FEAT(clk_fanout_clk, "clk-fanout", clk_fanout_parents, 0x1f38, 0, 5, 5, 5, 24, 2, BIT(31), 0, CCU_FEATURE_DUAL_DIV);

static SUNXI_CCU_MUX_DATA_WITH_GATE(fanout3_clk, "fanout3", fanout_clk_parents, 0x1f3c, 9, 3, BIT(24), 0);

static SUNXI_CCU_MUX_DATA_WITH_GATE(fanout2_clk, "fanout2", fanout_clk_parents, 0x1f3c, 6, 3, BIT(23), 0);

static SUNXI_CCU_MUX_DATA_WITH_GATE(fanout1_clk, "fanout1", fanout_clk_parents, 0x1f3c, 3, 3, BIT(22), 0);

static SUNXI_CCU_MUX_DATA_WITH_GATE(fanout0_clk, "fanout0", fanout_clk_parents, 0x1f3c, 0, 3, BIT(21), 0);

static SUNXI_CCU_MUX_DATA(bus_debug_clk, "bus_debug", bus_debug_parents, 0x1f50, 0, 2, 0);

static struct ccu_common *sun60i_a733_ccu_clks[] = {
	&pll_ref_clk.common,
	&pll_ddr_clk.common,
	&pll_peri0_clk.common,
	&pll_peri0_2x_clk.common,
	&pll_peri0_800m_clk.common,
	&pll_peri0_480m_clk.common,
	&pll_peri1_clk.common,
	&pll_peri1_2x_clk.common,
	&pll_peri1_800m_clk.common,
	&pll_peri1_480m_clk.common,
	&pll_gpu0_clk.common,
	&pll_video0_clk.common,
	&pll_video0_4x_clk.common,
	&pll_video0_3x_clk.common,
	&pll_video1_clk.common,
	&pll_video1_4x_clk.common,
	&pll_video1_3x_clk.common,
	&pll_video2_clk.common,
	&pll_video2_4x_clk.common,
	&pll_video2_3x_clk.common,
	&pll_ve0_clk.common,
	&pll_ve1_clk.common,
	&pll_audio0_4x_clk.common,
	&pll_audio1_clk.common,
	&pll_audio1_div2_clk.common,
	&pll_audio1_div5_clk.common,
	&pll_npu_clk.common,
	&pll_de_clk.common,
	&ahb_clk.common,
	&apb0_clk.common,
	&apb1_clk.common,
	&apb_uart_clk.common,
	&trace_clk.common,
	&gic_clk.common,
	&cpu_peri_clk.common,
	&its_pcie0_aclk_clk.common,
	&nsi_cfg_clk.common,
	&iommu0_sys_hclk_clk.common,
	&iommu0_sys_pclk_clk.common,
	&iommu0_sys_mclk_clk.common,
	&msi_lite0_clk.common,
	&msi_lite1_clk.common,
	&msi_lite2_clk.common,
	&iommu1_sys_hclk_clk.common,
	&iommu1_sys_pclk_clk.common,
	&iommu1_sys_mclk_clk.common,
	&cpus_hclk_gate_clk.gate.common,
	&store_ahb_gate_clk.gate.common,
	&msilite0_ahb_gate_clk.gate.common,
	&usb_sys_ahb_gate_clk.gate.common,
	&serdes_ahb_gate_clk.gate.common,
	&gpu0_ahb_gate_clk.gate.common,
	&npu_ahb_gate_clk.gate.common,
	&de_ahb_gate_clk.gate.common,
	&vid_out1_ahb_gate_clk.gate.common,
	&vid_out0_ahb_gate_clk.gate.common,
	&vid_in_ahb_gate_clk.gate.common,
	&ve_enc_ahb_gate_clk.gate.common,
	&ve_ahb_gate_clk.gate.common,
	&msilite2_mbus_gate_clk.gate.common,
	&store_mbus_gate_clk.gate.common,
	&msilite0_mbus_gate_clk.gate.common,
	&serdes_mbus_gate_clk.gate.common,
	&vid_in_mbus_gate_clk.gate.common,
	&npu_mbus_gate_clk.gate.common,
	&gpu0_mbus_gate_clk.gate.common,
	&ve_dec_mbus_gate_clk.gate.common,
	&ve_mbus_gate_clk.gate.common,
	&desys_mbus_gate_clk.gate.common,
	&iommu1_mbus_gate_clk.gate.common,
	&iommu0_mbus_gate_clk.gate.common,
	&ve_dec_mclk_clk.gate.common,
	&gmac1_mclk_clk.gate.common,
	&gmac0_mclk_clk.gate.common,
	&isp_mclk_clk.gate.common,
	&csi_mclk_clk.gate.common,
	&nand_mclk_clk.gate.common,
	&dma1_mclk_clk.gate.common,
	&ce_mclk_clk.gate.common,
	&ve_mclk_clk.gate.common,
	&dma0_mclk_clk.gate.common,
	&dma0_clk.common,
	&dma1_clk.common,
	&spinlock_clk.common,
	&msgbox0_clk.common,
	&pwm0_clk.common,
	&pwm1_clk.common,
	&dbgsys_clk.common,
	&sysdap_clk.common,
	&timer0_clk.common,
	&timer1_clk.common,
	&timer2_clk.common,
	&timer3_clk.common,
	&timer4_clk.common,
	&timer5_clk.common,
	&timer6_clk.common,
	&timer7_clk.common,
	&timer8_clk.common,
	&timer9_clk.common,
	&timer_bus_clk.common,
	&avs_clk.common,
	&de0_clk.common,
	&de0_gate_clk.common,
	&di_clk.common,
	&di_gate_clk.common,
	&g2d_clk.common,
	&g2d_gate_clk.common,
	&eink_clk.common,
	&eink_panel_clk.common,
	&eink_gate_clk.common,
	&ve_enc0_clk.common,
	&ve_dec_clk.common,
	&ve_dec_gate_clk.common,
	&ve_enc0_bus_clk.common,
	&ce_clk.common,
	&ce_sys_clk.common,
	&ce_bus_clk.common,
	&npu_clk.common,
	&npu_gate_clk.common,
	&gpu0_clk.common,
	&gpu0_gate_clk.common,
	&dram0_gate_clk.common,
	&nand0_clk0_clk.common,
	&nand0_clk1_clk.common,
	&nand0_bus_clk.common,
	&smhc0_clk.common,
	&smhc0_gate_clk.common,
	&smhc1_clk.common,
	&smhc1_gate_clk.common,
	&smhc2_clk.common,
	&smhc2_gate_clk.common,
	&smhc3_clk.common,
	&smhc3_bus_clk.common,
	&ufs_axi_clk.common,
	&ufs_cfg_clk.common,
	&ufs_clk.common,
	&uart0_clk.common,
	&uart1_clk.common,
	&uart2_clk.common,
	&uart3_clk.common,
	&uart4_clk.common,
	&uart5_clk.common,
	&uart6_clk.common,
	&twi0_clk.common,
	&twi1_clk.common,
	&twi2_clk.common,
	&twi3_clk.common,
	&twi4_clk.common,
	&twi5_clk.common,
	&twi6_clk.common,
	&twi7_clk.common,
	&twi8_clk.common,
	&twi9_clk.common,
	&twi10_clk.common,
	&twi11_clk.common,
	&twi12_clk.common,
	&spi0_clk.common,
	&spi0_bus_clk.common,
	&spi1_clk.common,
	&spi1_bus_clk.common,
	&spi2_clk.common,
	&spi2_bus_clk.common,
	&spif_clk.common,
	&spif_bus_clk.common,
	&spi3_clk.common,
	&spi3_bus_clk.common,
	&spi4_clk.common,
	&spi4_bus_clk.common,
	&gpadc0_24m_clk.common,
	&gpadc0_clk.common,
	&ths0_clk.common,
	&irrx_clk.common,
	&irrx_gate_clk.common,
	&irtx_clk.common,
	&irtx_gate_clk.common,
	&lradc_clk.common,
	&sgpio_clk.common,
	&sgpio_bus_clk.common,
	&lpc_clk.common,
	&lpc_gate_clk.common,
	&i2spcm0_clk.common,
	&i2spcm0_bus_clk.common,
	&i2spcm1_clk.common,
	&i2spcm1_bus_clk.common,
	&i2spcm2_clk.common,
	&i2spcm2_asrc_clk.common,
	&i2spcm2_bus_clk.common,
	&i2spcm3_clk.common,
	&i2spcm3_bus_clk.common,
	&i2spcm4_clk.common,
	&i2spcm4_bus_clk.common,
	&owa_tx_clk.common,
	&owa_rx_clk.common,
	&owa_bus_clk.common,
	&dmic_clk.common,
	&dmic_bus_clk.common,
	&usb_clk.common,
	&usb0_device_clk.common,
	&usb0_ehci_clk.common,
	&usb0_ohci_clk.common,
	&usb1_clk.common,
	&usb1_ehci_clk.common,
	&usb1_ohci_clk.common,
	&usb_ref_clk.common,
	&usb2_u2_ref_clk.common,
	&usb2_suspend_clk.common,
	&usb2_mf_clk.common,
	&usb2_u3_utmi_clk.common,
	&usb2_u2_pipe_clk.common,
	&pcie0_aux_clk.common,
	&pcie0_axi_slv_clk.common,
	&serdes_phy_cfg_clk.common,
	&gmac_ptp_clk.common,
	&gmac0_clk.common,
	&gmac1_clk.common,
	&vo0_tconlcd0_clk.common,
	&vo0_tconlcd0_bus_clk.common,
	&vo0_tconlcd1_clk.common,
	&vo0_tconlcd1_bus_clk.common,
	&vo0_tconlcd2_clk.common,
	&vo0_tconlcd2_bus_clk.common,
	&dsi0_clk.common,
	&dsi0_bus_clk.common,
	&dsi1_clk.common,
	&dsi1_bus_clk.common,
	&combphy0_clk.common,
	&combphy1_clk.common,
	&tcontv0_clk.common,
	&tcontv1_clk.common,
	&edp_tv_clk.common,
	&edp_clk.common,
	&hdmi_ref_clk.common,
	&hdmi_tv_clk.common,
	&hdmi_clk.common,
	&hdmi_sfr_clk.common,
	&hdcp_esm_clk.common,
	&dpss_top0_clk.common,
	&dpss_top1_clk.common,
	&ledc_clk.common,
	&ledc_bus_clk.common,
	&dsc_clk.common,
	&csi_master0_clk.common,
	&csi_master1_clk.common,
	&csi_master2_clk.common,
	&csi_clk.common,
	&csi_bus_clk.common,
	&isp_clk.common,
	&res_dcap_24m_clk.common,
	&apb2jtag_clk.common,
	&fanout_25m_clk.common,
	&fanout_16m_clk.common,
	&fanout_12m_clk.common,
	&fanout_24m_clk.common,
	&clk27m_fanout_clk.common,
	&clk_fanout_clk.common,
	&fanout3_clk.common,
	&fanout2_clk.common,
	&fanout1_clk.common,
	&fanout0_clk.common,
	&bus_debug_clk.common,
	&pll_ddr_auto_clk.common,
	&pll_peri0_2x_auto_clk.common,
	&pll_peri0_800m_auto_clk.common,
	&pll_peri0_600m_auto_clk.common,
	&pll_peri0_480m_all_auto_clk.common,
	&pll_peri0_480m_auto_clk.common,
	&pll_peri0_160m_auto_clk.common,
	&pll_peri0_300m_all_auto_clk.common,
	&pll_peri0_300m_auto_clk.common,
	&pll_peri0_150m_auto_clk.common,
	&pll_peri0_400m_all_auto_clk.common,
	&pll_peri0_400m_auto_clk.common,
	&pll_peri0_200m_auto_clk.common,
	&pll_peri1_800m_auto_clk.common,
	&pll_peri1_600m_all_auto_clk.common,
	&pll_peri1_600m_auto_clk.common,
	&pll_peri1_480m_all_auto_clk.common,
	&pll_peri1_480m_auto_clk.common,
	&pll_peri1_160m_auto_clk.common,
	&pll_peri1_300m_all_auto_clk.common,
	&pll_peri1_300m_auto_clk.common,
	&pll_peri1_150m_auto_clk.common,
	&pll_peri1_400m_all_auto_clk.common,
	&pll_peri1_400m_auto_clk.common,
	&pll_peri1_200m_auto_clk.common,
	&pll_video2_3x_auto_clk.common,
	&pll_video1_3x_auto_clk.common,
	&pll_video0_3x_auto_clk.common,
	&pll_video2_4x_auto_clk.common,
	&pll_video1_4x_auto_clk.common,
	&pll_video0_4x_auto_clk.common,
	&pll_gpu0_auto_clk.common,
	&pll_ve1_auto_clk.common,
	&pll_ve0_auto_clk.common,
	&pll_audio1_div5_auto_clk.common,
	&pll_audio1_div2_auto_clk.common,
	&pll_audio1_4x_auto_clk.common,
	&pll_npu_auto_clk.common,
	&pll_de_3x_auto_clk.common,
	&pll_de_4x_auto_clk.common,
};

static struct clk_hw_onecell_data sun60i_a733_hw_clks = {
	.num	= CLK_NUMBER,
	.hws	= {
	[CLK_PLL_DDR]	= &pll_ddr_clk.common.hw,
	[CLK_PLL_PERI0]	= &pll_peri0_clk.common.hw,
	[CLK_PLL_PERI0_2X]	= &pll_peri0_2x_clk.common.hw,
	[CLK_PLL_PERI0_800M]	= &pll_peri0_800m_clk.common.hw,
	[CLK_PLL_PERI0_480M]	= &pll_peri0_480m_clk.common.hw,
	[CLK_PLL_PERI0_600M]	= &pll_peri0_600m_clk.hw,
	[CLK_PLL_PERI0_400M]	= &pll_peri0_400m_clk.hw,
	[CLK_PLL_PERI0_300M]	= &pll_peri0_300m_clk.hw,
	[CLK_PLL_PERI0_200M]	= &pll_peri0_200m_clk.hw,
	[CLK_PLL_PERI0_160M]	= &pll_peri0_160m_clk.hw,
	[CLK_PLL_PERI0_150M]	= &pll_peri0_150m_clk.hw,
	[CLK_PLL_PERI1]	= &pll_peri1_clk.common.hw,
	[CLK_PLL_PERI1_2X]	= &pll_peri1_2x_clk.common.hw,
	[CLK_PLL_PERI1_800M]	= &pll_peri1_800m_clk.common.hw,
	[CLK_PLL_PERI1_480M]	= &pll_peri1_480m_clk.common.hw,
	[CLK_PLL_PERI1_600M]	= &pll_peri1_600m_clk.hw,
	[CLK_PLL_PERI1_400M]	= &pll_peri1_400m_clk.hw,
	[CLK_PLL_PERI1_300M]	= &pll_peri1_300m_clk.hw,
	[CLK_PLL_PERI1_200M]	= &pll_peri1_200m_clk.hw,
	[CLK_PLL_PERI1_160M]	= &pll_peri1_160m_clk.hw,
	[CLK_PLL_PERI1_150M]	= &pll_peri1_150m_clk.hw,
	[CLK_PLL_GPU0]	= &pll_gpu0_clk.common.hw,
	[CLK_PLL_VIDEO0]	= &pll_video0_clk.common.hw,
	[CLK_PLL_VIDEO0_4X]	= &pll_video0_4x_clk.common.hw,
	[CLK_PLL_VIDEO0_3X]	= &pll_video0_3x_clk.common.hw,
	[CLK_PLL_VIDEO1]	= &pll_video1_clk.common.hw,
	[CLK_PLL_VIDEO1_4X]	= &pll_video1_4x_clk.common.hw,
	[CLK_PLL_VIDEO1_3X]	= &pll_video1_3x_clk.common.hw,
	[CLK_PLL_VIDEO2]	= &pll_video2_clk.common.hw,
	[CLK_PLL_VIDEO2_4X]	= &pll_video2_4x_clk.common.hw,
	[CLK_PLL_VIDEO2_3X]	= &pll_video2_3x_clk.common.hw,
	[CLK_PLL_VE0]	= &pll_ve0_clk.common.hw,
	[CLK_PLL_VE1]	= &pll_ve1_clk.common.hw,
	[CLK_PLL_AUDIO0_4X]	= &pll_audio0_4x_clk.common.hw,
	[CLK_PLL_AUDIO1]	= &pll_audio1_clk.common.hw,
	[CLK_PLL_AUDIO1_DIV2]	= &pll_audio1_div2_clk.common.hw,
	[CLK_PLL_AUDIO1_DIV5]	= &pll_audio1_div5_clk.common.hw,
	[CLK_PLL_NPU]	= &pll_npu_clk.common.hw,
	[CLK_PLL_DE]	= &pll_de_clk.common.hw,
	[CLK_AHB]	= &ahb_clk.common.hw,
	[CLK_APB0]	= &apb0_clk.common.hw,
	[CLK_APB1]	= &apb1_clk.common.hw,
	[CLK_TRACE]	= &trace_clk.common.hw,
	[CLK_GIC]	= &gic_clk.common.hw,
	[CLK_CPU_PERI]	= &cpu_peri_clk.common.hw,
	[CLK_NSI_CFG]	= &nsi_cfg_clk.common.hw,
	[CLK_MSI_LITE0]	= &msi_lite0_clk.common.hw,
	[CLK_MSI_LITE1]	= &msi_lite1_clk.common.hw,
	[CLK_MSI_LITE2]	= &msi_lite2_clk.common.hw,
	[CLK_CPUS_HCLK_GATE]	= &cpus_hclk_gate_clk.gate.common.hw,
	[CLK_STORE_AHB_GATE]	= &store_ahb_gate_clk.gate.common.hw,
	[CLK_MSILITE0_AHB_GATE]	= &msilite0_ahb_gate_clk.gate.common.hw,
	[CLK_USB_SYS_AHB_GATE]	= &usb_sys_ahb_gate_clk.gate.common.hw,
	[CLK_SERDES_AHB_GATE]	= &serdes_ahb_gate_clk.gate.common.hw,
	[CLK_GPU0_AHB_GATE]	= &gpu0_ahb_gate_clk.gate.common.hw,
	[CLK_NPU_AHB_GATE]	= &npu_ahb_gate_clk.gate.common.hw,
	[CLK_DE_AHB_GATE]	= &de_ahb_gate_clk.gate.common.hw,
	[CLK_VID_OUT1_AHB_GATE]	= &vid_out1_ahb_gate_clk.gate.common.hw,
	[CLK_VID_OUT0_AHB_GATE]	= &vid_out0_ahb_gate_clk.gate.common.hw,
	[CLK_VID_IN_AHB_GATE]	= &vid_in_ahb_gate_clk.gate.common.hw,
	[CLK_VE_ENC_AHB_GATE]	= &ve_enc_ahb_gate_clk.gate.common.hw,
	[CLK_VE_AHB_GATE]	= &ve_ahb_gate_clk.gate.common.hw,
	[CLK_VE_DEC_MBUS]	= &ve_dec_mbus_gate_clk.gate.common.hw,
	[CLK_IOMMU1_MBUS_GATE]	= &iommu1_mbus_gate_clk.gate.common.hw,
	[CLK_IOMMU0_MBUS_GATE]	= &iommu0_mbus_gate_clk.gate.common.hw,
	[CLK_DMA0]	= &dma0_clk.common.hw,
	[CLK_DMA1]	= &dma1_clk.common.hw,
	[CLK_SPINLOCK]	= &spinlock_clk.common.hw,
	[CLK_MSGBOX0]	= &msgbox0_clk.common.hw,
	[CLK_PWM0]	= &pwm0_clk.common.hw,
	[CLK_PWM1]	= &pwm1_clk.common.hw,
	[CLK_DBGSYS]	= &dbgsys_clk.common.hw,
	[CLK_SYSDAP]	= &sysdap_clk.common.hw,
	[CLK_TIMER0]	= &timer0_clk.common.hw,
	[CLK_TIMER1]	= &timer1_clk.common.hw,
	[CLK_TIMER2]	= &timer2_clk.common.hw,
	[CLK_TIMER3]	= &timer3_clk.common.hw,
	[CLK_TIMER4]	= &timer4_clk.common.hw,
	[CLK_TIMER5]	= &timer5_clk.common.hw,
	[CLK_TIMER6]	= &timer6_clk.common.hw,
	[CLK_TIMER7]	= &timer7_clk.common.hw,
	[CLK_TIMER8]	= &timer8_clk.common.hw,
	[CLK_TIMER9]	= &timer9_clk.common.hw,
	[CLK_AVS]	= &avs_clk.common.hw,
	[CLK_DE0]	= &de0_clk.common.hw,
	[CLK_DE0]	= &de0_gate_clk.common.hw,
	[CLK_DI]	= &di_clk.common.hw,
	[CLK_DI_GATE]	= &di_gate_clk.common.hw,
	[CLK_G2D]	= &g2d_clk.common.hw,
	[CLK_G2D_GATE]	= &g2d_gate_clk.common.hw,
	[CLK_EINK]	= &eink_clk.common.hw,
	[CLK_EINK_PANEL]	= &eink_panel_clk.common.hw,
	[CLK_EINK_GATE]	= &eink_gate_clk.common.hw,
	[CLK_VE_ENC0]	= &ve_enc0_clk.common.hw,
	[CLK_VE_DEC]	= &ve_dec_clk.common.hw,
	[CLK_CE]	= &ce_clk.common.hw,
	[CLK_CE_SYS]	= &ce_sys_clk.common.hw,
	[CLK_CE]	= &ce_bus_clk.common.hw,
	[CLK_NPU]	= &npu_clk.common.hw,
	[CLK_GPU0]	= &gpu0_clk.common.hw,
	[CLK_DRAM0]	= &dram0_gate_clk.common.hw,
	[CLK_NAND0_CLK0]	= &nand0_clk0_clk.common.hw,
	[CLK_NAND0_CLK1]	= &nand0_clk1_clk.common.hw,
	[CLK_SMHC0]	= &smhc0_clk.common.hw,
	[CLK_SMHC1]	= &smhc1_clk.common.hw,
	[CLK_SMHC2]	= &smhc2_clk.common.hw,
	[CLK_SMHC3]	= &smhc3_clk.common.hw,
	[CLK_UFS_AXI]	= &ufs_axi_clk.common.hw,
	[CLK_UFS_CFG]	= &ufs_cfg_clk.common.hw,
	[CLK_UFS]	= &ufs_clk.common.hw,
	[CLK_UART0]	= &uart0_clk.common.hw,
	[CLK_UART1]	= &uart1_clk.common.hw,
	[CLK_UART2]	= &uart2_clk.common.hw,
	[CLK_UART3]	= &uart3_clk.common.hw,
	[CLK_UART4]	= &uart4_clk.common.hw,
	[CLK_UART5]	= &uart5_clk.common.hw,
	[CLK_UART6]	= &uart6_clk.common.hw,
	[CLK_TWI0]	= &twi0_clk.common.hw,
	[CLK_TWI1]	= &twi1_clk.common.hw,
	[CLK_TWI2]	= &twi2_clk.common.hw,
	[CLK_TWI3]	= &twi3_clk.common.hw,
	[CLK_TWI4]	= &twi4_clk.common.hw,
	[CLK_TWI5]	= &twi5_clk.common.hw,
	[CLK_TWI6]	= &twi6_clk.common.hw,
	[CLK_TWI7]	= &twi7_clk.common.hw,
	[CLK_TWI8]	= &twi8_clk.common.hw,
	[CLK_TWI9]	= &twi9_clk.common.hw,
	[CLK_TWI10]	= &twi10_clk.common.hw,
	[CLK_TWI11]	= &twi11_clk.common.hw,
	[CLK_TWI12]	= &twi12_clk.common.hw,
	[CLK_SPI0]	= &spi0_clk.common.hw,
	[CLK_SPI1]	= &spi1_clk.common.hw,
	[CLK_SPI2]	= &spi2_clk.common.hw,
	[CLK_SPIF]	= &spif_clk.common.hw,
	[CLK_SPI3]	= &spi3_clk.common.hw,
	[CLK_SPI4]	= &spi4_clk.common.hw,
	[CLK_GPADC0_24M]	= &gpadc0_24m_clk.common.hw,
	[CLK_GPADC0]	= &gpadc0_clk.common.hw,
	[CLK_THS0]	= &ths0_clk.common.hw,
	[CLK_IRRX]	= &irrx_clk.common.hw,
	[CLK_IRRX_GATE]	= &irrx_gate_clk.common.hw,
	[CLK_IRTX]	= &irtx_clk.common.hw,
	[CLK_IRTX_GATE]	= &irtx_gate_clk.common.hw,
	[CLK_LRADC]	= &lradc_clk.common.hw,
	[CLK_SGPIO]	= &sgpio_clk.common.hw,
	[CLK_LPC]	= &lpc_clk.common.hw,
	[CLK_I2SPCM0]	= &i2spcm0_clk.common.hw,
	[CLK_I2SPCM1]	= &i2spcm1_clk.common.hw,
	[CLK_I2SPCM2]	= &i2spcm2_clk.common.hw,
	[CLK_I2SPCM2_ASRC]	= &i2spcm2_asrc_clk.common.hw,
	[CLK_I2SPCM3]	= &i2spcm3_clk.common.hw,
	[CLK_I2SPCM4]	= &i2spcm4_clk.common.hw,
	[CLK_OWA_TX]	= &owa_tx_clk.common.hw,
	[CLK_OWA_RX]	= &owa_rx_clk.common.hw,
	[CLK_DMIC]	= &dmic_clk.common.hw,
	[CLK_USB]	= &usb_clk.common.hw,
	[CLK_USB0_DEVICE]	= &usb0_device_clk.common.hw,
	[CLK_USB0_EHCI]	= &usb0_ehci_clk.common.hw,
	[CLK_USB0_OHCI]	= &usb0_ohci_clk.common.hw,
	[CLK_USB1]	= &usb1_clk.common.hw,
	[CLK_USB1_EHCI]	= &usb1_ehci_clk.common.hw,
	[CLK_USB1_OHCI]	= &usb1_ohci_clk.common.hw,
	[CLK_USB_REF]	= &usb_ref_clk.common.hw,
	[CLK_USB2_U2_REF]	= &usb2_u2_ref_clk.common.hw,
	[CLK_USB2_SUSPEND]	= &usb2_suspend_clk.common.hw,
	[CLK_USB2_MF]	= &usb2_mf_clk.common.hw,
	[CLK_USB2_U3_UTMI]	= &usb2_u3_utmi_clk.common.hw,
	[CLK_USB2_U2_PIPE]	= &usb2_u2_pipe_clk.common.hw,
	[CLK_PCIE0_AUX]	= &pcie0_aux_clk.common.hw,
	[CLK_PCIE0_AXI_SLV]	= &pcie0_axi_slv_clk.common.hw,
	[CLK_SERDES_PHY_CFG]	= &serdes_phy_cfg_clk.common.hw,
	[CLK_GMAC_PTP]	= &gmac_ptp_clk.common.hw,
	[CLK_GMAC0]	= &gmac0_clk.common.hw,
	[CLK_GMAC1]	= &gmac1_clk.common.hw,
	[CLK_VO0_TCONLCD0]	= &vo0_tconlcd0_clk.common.hw,
	[CLK_VO0_TCONLCD0]	= &vo0_tconlcd0_bus_clk.common.hw,
	[CLK_VO0_TCONLCD1]	= &vo0_tconlcd1_clk.common.hw,
	[CLK_VO0_TCONLCD1]	= &vo0_tconlcd1_bus_clk.common.hw,
	[CLK_VO0_TCONLCD2]	= &vo0_tconlcd2_clk.common.hw,
	[CLK_VO0_TCONLCD2]	= &vo0_tconlcd2_bus_clk.common.hw,
	[CLK_DSI0]	= &dsi0_clk.common.hw,
	[CLK_DSI0]	= &dsi0_bus_clk.common.hw,
	[CLK_DSI1]	= &dsi1_clk.common.hw,
	[CLK_DSI1]	= &dsi1_bus_clk.common.hw,
	[CLK_COMBPHY0]	= &combphy0_clk.common.hw,
	[CLK_COMBPHY1]	= &combphy1_clk.common.hw,
	[CLK_TCONTV0]	= &tcontv0_clk.common.hw,
	[CLK_TCONTV1]	= &tcontv1_clk.common.hw,
	[CLK_EDP_TV]	= &edp_tv_clk.common.hw,
	[CLK_EDP]	= &edp_clk.common.hw,
	[CLK_HDMI_REF]	= &hdmi_ref_clk.common.hw,
	[CLK_HDMI_TV]	= &hdmi_tv_clk.common.hw,
	[CLK_HDMI]	= &hdmi_clk.common.hw,
	[CLK_HDMI_SFR]	= &hdmi_sfr_clk.common.hw,
	[CLK_HDCP_ESM]	= &hdcp_esm_clk.common.hw,
	[CLK_DPSS_TOP0]	= &dpss_top0_clk.common.hw,
	[CLK_DPSS_TOP1]	= &dpss_top1_clk.common.hw,
	[CLK_LEDC]	= &ledc_clk.common.hw,
	[CLK_DSC]	= &dsc_clk.common.hw,
	[CLK_CSI_MASTER0]	= &csi_master0_clk.common.hw,
	[CLK_CSI_MASTER1]	= &csi_master1_clk.common.hw,
	[CLK_CSI_MASTER2]	= &csi_master2_clk.common.hw,
	[CLK_CSI]	= &csi_clk.common.hw,
	[CLK_ISP]	= &isp_clk.common.hw,
	[CLK_RES_DCAP_24M]	= &res_dcap_24m_clk.common.hw,
	[CLK_APB2JTAG]	= &apb2jtag_clk.common.hw,
	[CLK_FANOUT_25M]	= &fanout_25m_clk.common.hw,
	[CLK_FANOUT_16M]	= &fanout_16m_clk.common.hw,
	[CLK_FANOUT_12M]	= &fanout_12m_clk.common.hw,
	[CLK_FANOUT_24M]	= &fanout_24m_clk.common.hw,
	[CLK_CLK27M_FANOUT]	= &clk27m_fanout_clk.common.hw,
	[CLK_CLK_FANOUT]	= &clk_fanout_clk.common.hw,
	[CLK_PLL_PERI0_16M]	= &pll_peri0_16m_clk.hw,
	[CLK_PLL_PERI0_25M]	= &pll_peri0_25m_clk.hw,
	[CLK_FANOUT3]	= &fanout3_clk.common.hw,
	[CLK_FANOUT2]	= &fanout2_clk.common.hw,
	[CLK_FANOUT1]	= &fanout1_clk.common.hw,
	[CLK_FANOUT0]	= &fanout0_clk.common.hw,
	[CLK_BUS_DEBUG]	= &bus_debug_clk.common.hw,
	[CLK_PLL_DDR_AUTO]	= &pll_ddr_auto_clk.common.hw,
	[CLK_PLL_PERI0_2X_AUTO]	= &pll_peri0_2x_auto_clk.common.hw,
	[CLK_PLL_PERI0_800M_AUTO]	= &pll_peri0_800m_auto_clk.common.hw,
	[CLK_PLL_PERI0_600M_AUTO]	= &pll_peri0_600m_auto_clk.common.hw,
	[CLK_PLL_PERI0_480M_ALL_AUTO]	= &pll_peri0_480m_all_auto_clk.common.hw,
	[CLK_PLL_PERI0_480M_AUTO]	= &pll_peri0_480m_auto_clk.common.hw,
	[CLK_PLL_PERI0_160M_AUTO]	= &pll_peri0_160m_auto_clk.common.hw,
	[CLK_PLL_PERI0_300M_ALL_AUTO]	= &pll_peri0_300m_all_auto_clk.common.hw,
	[CLK_PLL_PERI0_300M_AUTO]	= &pll_peri0_300m_auto_clk.common.hw,
	[CLK_PLL_PERI0_150M_AUTO]	= &pll_peri0_150m_auto_clk.common.hw,
	[CLK_PLL_PERI0_400M_ALL_AUTO]	= &pll_peri0_400m_all_auto_clk.common.hw,
	[CLK_PLL_PERI0_400M_AUTO]	= &pll_peri0_400m_auto_clk.common.hw,
	[CLK_PLL_PERI0_200M_AUTO]	= &pll_peri0_200m_auto_clk.common.hw,
	[CLK_PLL_PERI1_800M_AUTO]	= &pll_peri1_800m_auto_clk.common.hw,
	[CLK_PLL_PERI1_600M_ALL_AUTO]	= &pll_peri1_600m_all_auto_clk.common.hw,
	[CLK_PLL_PERI1_600M_AUTO]	= &pll_peri1_600m_auto_clk.common.hw,
	[CLK_PLL_PERI1_480M_ALL_AUTO]	= &pll_peri1_480m_all_auto_clk.common.hw,
	[CLK_PLL_PERI1_480M_AUTO]	= &pll_peri1_480m_auto_clk.common.hw,
	[CLK_PLL_PERI1_160M_AUTO]	= &pll_peri1_160m_auto_clk.common.hw,
	[CLK_PLL_PERI1_300M_ALL_AUTO]	= &pll_peri1_300m_all_auto_clk.common.hw,
	[CLK_PLL_PERI1_300M_AUTO]	= &pll_peri1_300m_auto_clk.common.hw,
	[CLK_PLL_PERI1_150M_AUTO]	= &pll_peri1_150m_auto_clk.common.hw,
	[CLK_PLL_PERI1_400M_ALL_AUTO]	= &pll_peri1_400m_all_auto_clk.common.hw,
	[CLK_PLL_PERI1_400M_AUTO]	= &pll_peri1_400m_auto_clk.common.hw,
	[CLK_PLL_PERI1_200M_AUTO]	= &pll_peri1_200m_auto_clk.common.hw,
	[CLK_PLL_VIDEO2_3X_AUTO]	= &pll_video2_3x_auto_clk.common.hw,
	[CLK_PLL_VIDEO1_3X_AUTO]	= &pll_video1_3x_auto_clk.common.hw,
	[CLK_PLL_VIDEO0_3X_AUTO]	= &pll_video0_3x_auto_clk.common.hw,
	[CLK_PLL_VIDEO2_4X_AUTO]	= &pll_video2_4x_auto_clk.common.hw,
	[CLK_PLL_VIDEO1_4X_AUTO]	= &pll_video1_4x_auto_clk.common.hw,
	[CLK_PLL_VIDEO0_4X_AUTO]	= &pll_video0_4x_auto_clk.common.hw,
	[CLK_PLL_GPU0_AUTO]	= &pll_gpu0_auto_clk.common.hw,
	[CLK_PLL_VE1_AUTO]	= &pll_ve1_auto_clk.common.hw,
	[CLK_PLL_VE0_AUTO]	= &pll_ve0_auto_clk.common.hw,
	[CLK_PLL_AUDIO1_DIV5_AUTO]	= &pll_audio1_div5_auto_clk.common.hw,
	[CLK_PLL_AUDIO1_DIV2_AUTO]	= &pll_audio1_div2_auto_clk.common.hw,
	[CLK_PLL_NPU_AUTO]	= &pll_npu_auto_clk.common.hw,
	[CLK_PLL_DE_3X_AUTO]	= &pll_de_3x_auto_clk.common.hw,
	[CLK_PLL_DE_4X_AUTO]	= &pll_de_4x_auto_clk.common.hw,
	},
};

static const struct sunxi_ccu_desc sun60i_a733_ccu_desc = {
	.ccu_clks	= sun60i_a733_ccu_clks,
	.num_ccu_clks	= ARRAY_SIZE(sun60i_a733_ccu_clks),

	.hw_clks	= &sun60i_a733_hw_clks,

	.resets		= NULL,
	.num_resets	= 0,
};

static int sun60i_a733_ccu_probe(struct platform_device *pdev)
{
	void __iomem *reg;
	int ret;

	reg = devm_platform_ioremap_resource(pdev, 0);
	if (IS_ERR(reg))
		return PTR_ERR(reg);

	ret = devm_sunxi_ccu_probe(&pdev->dev, reg, &sun60i_a733_ccu_desc);
	if (ret)
		return ret;

	return 0;
}

static const struct of_device_id sun60i_a733_ccu_ids[] = {
	{ .compatible = "allwinner,sun60i-a733-ccu" },
	{ }
};
MODULE_DEVICE_TABLE(of, sun60i_a733_ccu_ids);

static struct platform_driver sun60i_a733_ccu_driver = {
	.probe	= sun60i_a733_ccu_probe,
	.driver	= {
		.name			= "sun60i-a733-ccu",
		.suppress_bind_attrs	= true,
		.of_match_table		= sun60i_a733_ccu_ids,
	},
};
module_platform_driver(sun60i_a733_ccu_driver);

MODULE_IMPORT_NS("SUNXI_CCU");
MODULE_DESCRIPTION("Support for the Allwinner A733 CCU");
MODULE_LICENSE("GPL");
