// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (C) 2026 Alexander Grec
 *
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: generators/generate_ccu.py --domain rtc
 * Source data:  /home/grec-alexander/Documents/porting/sun60iw2-upstream/generators/data/ccu-rtc-extracted.json
 */

#include <linux/clk-provider.h>
#include <linux/io.h>
#include <linux/module.h>
#include <linux/platform_device.h>

#include <dt-bindings/clock/sun60i-a733-rtc.h>


#include "../clk.h"

#include "ccu_common.h"
#include "ccu_reset.h"

#include "ccu_div.h"
#include "ccu_gate.h"
#include "ccu_mp.h"
#include "ccu_nm.h"
#include "ccu_nkmp.h"
#include "ccu_mux.h"

static const struct clk_parent_data osc24M[] = {
	{ .fw_name = "hosc" },
};

struct sun60i_key_gate {
	struct ccu_gate gate;
	u32 key_value;
};

static inline struct sun60i_key_gate *hw_to_sun60i_key_gate(struct clk_hw *hw)
{
	struct ccu_gate *cg = hw_to_ccu_gate(hw);

	return container_of(cg, struct sun60i_key_gate, gate);
}

static int sun60i_key_gate_enable(struct clk_hw *hw)
{
	struct sun60i_key_gate *kg = hw_to_sun60i_key_gate(hw);
	struct ccu_common *common = &kg->gate.common;
	unsigned long flags;
	u32 reg;

	spin_lock_irqsave(common->lock, flags);
	reg = readl(common->base + common->reg);
	reg |= kg->key_value;
	reg |= kg->gate.enable;
	if (common->features & CCU_FEATURE_UPDATE_BIT)
		reg |= CCU_SUNXI_UPDATE_BIT;
	writel(reg, common->base + common->reg);
	spin_unlock_irqrestore(common->lock, flags);

	return 0;
}

static void sun60i_key_gate_disable(struct clk_hw *hw)
{
	struct sun60i_key_gate *kg = hw_to_sun60i_key_gate(hw);
	struct ccu_common *common = &kg->gate.common;
	unsigned long flags;
	u32 reg;

	spin_lock_irqsave(common->lock, flags);
	reg = readl(common->base + common->reg);
	reg |= kg->key_value;
	reg &= ~kg->gate.enable;
	if (common->features & CCU_FEATURE_UPDATE_BIT)
		reg |= CCU_SUNXI_UPDATE_BIT;
	writel(reg, common->base + common->reg);
	spin_unlock_irqrestore(common->lock, flags);
}

static int sun60i_key_gate_is_enabled(struct clk_hw *hw)
{
	struct sun60i_key_gate *kg = hw_to_sun60i_key_gate(hw);

	return ccu_gate_helper_is_enabled(&kg->gate.common, kg->gate.enable);
}

static unsigned long sun60i_key_gate_recalc_rate(struct clk_hw *hw,
						 unsigned long parent_rate)
{
	return parent_rate;
}

static int sun60i_key_gate_determine_rate(struct clk_hw *hw,
					  struct clk_rate_request *req)
{
	if (clk_hw_get_flags(hw) & CLK_SET_RATE_PARENT)
		req->best_parent_rate = clk_hw_round_rate(clk_hw_get_parent(hw), req->rate);

	req->rate = req->best_parent_rate;
	return 0;
}

static int sun60i_key_gate_set_rate(struct clk_hw *hw, unsigned long rate,
				    unsigned long parent_rate)
{
	return 0;
}

static const struct clk_ops sun60i_key_gate_ops = {
	.disable	= sun60i_key_gate_disable,
	.enable		= sun60i_key_gate_enable,
	.is_enabled	= sun60i_key_gate_is_enabled,
	.determine_rate	= sun60i_key_gate_determine_rate,
	.set_rate	= sun60i_key_gate_set_rate,
	.recalc_rate	= sun60i_key_gate_recalc_rate,
};

static SUNXI_CCU_GATE(iosc_clk, "iosc", "rc-16m", 0x160, BIT(0), 0);

static struct sun60i_key_gate ext32k_gate_clk = {
	.gate		= {
		.enable	= BIT(4),
		.common	= {
			.reg		= 0x000,
			.hw.init	= CLK_HW_INIT("ext32k-gate", "ext-32k",
					      &sun60i_key_gate_ops,
					      0),
		},
	},
	.key_value	= 0x16AA0000,
};

static CLK_FIXED_FACTOR(iosc_div32k_clk, "iosc-div32k", "iosc", 500, 1, 0);

/* Unsupported clock type 'mux_gate_key' for 'osc32k' */

/* Unsupported clock type 'gate_with_fixed_rate' for 'dcxo24M-div32k' */

/* Unsupported clock type 'mux_gate_key' for 'rtc32k' */

static CLK_FIXED_FACTOR(rtc_1k_clk, "rtc-1k", "rtc32k", 32, 1, 0);

static SUNXI_CCU_GATE(dcxo_wakeup_clk, "dcxo-wakeup", "dcxo", 0x160, BIT(31), 0);

static SUNXI_CCU_GATE(dcxo_serdes1_clk, "dcxo-serdes1", "r-ahb", 0x16c, BIT(5), 0);

static SUNXI_CCU_GATE(dcxo_serdes0_clk, "dcxo-serdes0", "r-ahb", 0x16c, BIT(4), 0);

static SUNXI_CCU_GATE(rtc_spi_clk, "rtc-spi", "r-ahb", 0x310, BIT(31), 0);

static const struct clk_parent_data dcxo_parents[] = {
	{ .fw_name = "dcxo24M" },
	{ .fw_name = "dcxo19_2M" },
	{ .fw_name = "dcxo26M" },
	{ .fw_name = "dcxo24M" },
};

static const struct clk_parent_data osc32k_parents[] = {
	{ .hw = &iosc_div32k_clk.hw },
	{ .hw = &ext32k_gate_clk.gate.common.hw },
};

static const struct clk_parent_data rtc32k_clk_parents[] = {
	{ .fw_name = "osc32k" },
	{ .fw_name = "dcxo24M-div32k" },
};

static const struct clk_parent_data rtc_32k_fanout_clk_parents[] = {
	{ .fw_name = "rtc32k" },
	{ .fw_name = "osc32k" },
	{ .fw_name = "dcxo24M-div32k" },
};
static SUNXI_CCU_MUX_DATA_WITH_GATE(rtc_32k_fanout_clk, "rtc-32k-fanout", rtc_32k_fanout_clk_parents, 0x060, 1, 2, BIT(0), 0);

static SUNXI_CCU_MUX_DATA(dcxo_clk, "dcxo", dcxo_parents, 0x160, 14, 2, 0);

static struct ccu_common *sun60i_a733_rtc_ccu_clks[] = {
	&iosc_clk.common,
	&ext32k_gate_clk.gate.common,
	&rtc_32k_fanout_clk.common,
	&dcxo_clk.common,
	&dcxo_wakeup_clk.common,
	&dcxo_serdes1_clk.common,
	&dcxo_serdes0_clk.common,
	&rtc_spi_clk.common,
};

static struct clk_hw_onecell_data sun60i_a733_rtc_ccu_hw_clks = {
	.num	= CLK_RTC_NUMBER,
	.hws	= {
	[CLK_IOSC]	= &iosc_clk.common.hw,
	[CLK_EXT32K_GATE]	= &ext32k_gate_clk.gate.common.hw,
	[CLK_IOSC_DIV32K]	= &iosc_div32k_clk.hw,
	[CLK_RTC_1K]	= &rtc_1k_clk.hw,
	[CLK_RTC_32K_FANOUT]	= &rtc_32k_fanout_clk.common.hw,
	[CLK_DCXO]	= &dcxo_clk.common.hw,
	[CLK_RTC_DCXO_WAKEUP]	= &dcxo_wakeup_clk.common.hw,
	[CLK_RTC_DCXO_SERDES1]	= &dcxo_serdes1_clk.common.hw,
	[CLK_RTC_DCXO_SERDES0]	= &dcxo_serdes0_clk.common.hw,
	[CLK_RTC_SPI]	= &rtc_spi_clk.common.hw,
	},
};

static const struct sunxi_ccu_desc sun60i_a733_rtc_ccu_desc = {
	.ccu_clks	= sun60i_a733_rtc_ccu_clks,
	.num_ccu_clks	= ARRAY_SIZE(sun60i_a733_rtc_ccu_clks),

	.hw_clks	= &sun60i_a733_rtc_ccu_hw_clks,

	.resets		= NULL,
	.num_resets	= 0,
};

static int sun60i_a733_rtc_ccu_probe(struct platform_device *pdev)
{
	void __iomem *reg;
	int ret;

	reg = devm_platform_ioremap_resource(pdev, 0);
	if (IS_ERR(reg))
		return PTR_ERR(reg);

	ret = devm_sunxi_ccu_probe(&pdev->dev, reg, &sun60i_a733_rtc_ccu_desc);
	if (ret)
		return ret;

	return 0;
}

static const struct of_device_id sun60i_a733_rtc_ccu_ids[] = {
	{ .compatible = "allwinner,sun60i-a733-rtc-ccu" },
	{ }
};
MODULE_DEVICE_TABLE(of, sun60i_a733_rtc_ccu_ids);

static struct platform_driver sun60i_a733_rtc_ccu_driver = {
	.probe	= sun60i_a733_rtc_ccu_probe,
	.driver	= {
		.name			= "sun60i-a733-rtc-ccu",
		.suppress_bind_attrs	= true,
		.of_match_table		= sun60i_a733_rtc_ccu_ids,
	},
};
module_platform_driver(sun60i_a733_rtc_ccu_driver);

MODULE_IMPORT_NS("SUNXI_CCU");
MODULE_DESCRIPTION("Support for the Allwinner A733 RTC_CCU CCU");
MODULE_LICENSE("GPL");
