// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (C) 2026 Alexander Grec
 *
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: generators/generate_ccu.py --domain r
 * Source data:  /home/grec-alexander/Documents/porting/sun60iw2-upstream/generators/data/ccu-r-extracted.json
 */

#include <linux/clk-provider.h>
#include <linux/io.h>
#include <linux/module.h>
#include <linux/platform_device.h>

#include <dt-bindings/clock/sun60i-a733-r-ccu.h>


#include "../clk.h"

#include "ccu_common.h"
#include "ccu_reset.h"

#include "ccu_div.h"
#include "ccu_gate.h"
#include "ccu_mp.h"
#include "ccu_nm.h"
#include "ccu_nkmp.h"
#include "ccu_mux.h"

static const struct clk_parent_data osc24M[] = {
	{ .fw_name = "hosc" },
};

static SUNXI_CCU_GATE(r_timer_clk, "r-timer", "dcxo", 0x11c, BIT(0), 0);

static SUNXI_CCU_GATE(r_twd_clk, "r-twd", "dcxo", 0x12c, BIT(0), 0);

static SUNXI_CCU_GATE(r_bus_pwm_clk, "r-bus-pwm", "dcxo", 0x13c, BIT(0), 0);

static SUNXI_CCU_GATE(r_bus_spi_clk, "r-bus-spi", "dcxo", 0x15c, BIT(0), 0);

static SUNXI_CCU_GATE(r_mbox_clk, "r-mbox", "dcxo", 0x17c, BIT(0), 0);

static SUNXI_CCU_GATE(r_uart1_clk, "r-uart1", "r-apbs1", 0x18c, BIT(1), 0);

static SUNXI_CCU_GATE(r_uart0_clk, "r-uart0", "r-apbs1", 0x18c, BIT(0), 0);

static SUNXI_CCU_GATE(r_twi2_clk, "r-twi2", "r-apbs1", 0x19c, BIT(2), 0);

static SUNXI_CCU_GATE(r_twi1_clk, "r-twi1", "r-apbs1", 0x19c, BIT(1), 0);

static SUNXI_CCU_GATE(r_twi0_clk, "r-twi0", "r-apbs1", 0x19c, BIT(0), 0);

static SUNXI_CCU_GATE(r_ppu_clk, "r-ppu", "dcxo", 0x1ac, BIT(0), 0);

static SUNXI_CCU_GATE(r_tzma_clk, "r-tzma", "dcxo", 0x1b0, BIT(0), 0);

static SUNXI_CCU_GATE(r_cpus_bist_clk, "r-cpus-bist", "dcxo", 0x1bc, BIT(0), 0);

static SUNXI_CCU_GATE(r_bus_irrx_clk, "r-bus-irrx", "dcxo", 0x1cc, BIT(0), 0);

static SUNXI_CCU_GATE(rtc_clk, "rtc", "dcxo", 0x20c, BIT(0), 0);

static SUNXI_CCU_GATE(riscv_cfg_clk, "riscv-cfg", "dcxo", 0x21c, BIT(1), 0);

static SUNXI_CCU_GATE(riscv_clk, "riscv", "dcxo", 0x21c, BIT(0), 0);

static SUNXI_CCU_GATE(r_cpucfg_clk, "r-cpucfg", "dcxo", 0x22c, BIT(0), 0);

static SUNXI_CCU_GATE(vdd_usb2cpus_clk, "vdd-usb2cpus", "dcxo", 0x250, BIT(8), 0);

static SUNXI_CCU_GATE(vdd_sys2usb_clk, "vdd-sys2usb", "dcxo", 0x250, BIT(3), 0);

static SUNXI_CCU_GATE(vdd_sys2cpus_clk, "vdd-sys2cpus", "dcxo", 0x250, BIT(2), 0);

static SUNXI_CCU_GATE(vdd_ddr_clk, "vdd-ddr", "dcxo", 0x250, BIT(0), 0);

static SUNXI_CCU_GATE(tt_auto_clk, "tt-auto", "dcxo", 0x338, BIT(9), 0);

static SUNXI_CCU_GATE(cpu_icache_auto_clk, "cpu-icache-auto", "dcxo", 0x338, BIT(8), 0);

static SUNXI_CCU_GATE(ahbs_auto_clk_clk, "ahbs-auto-clk", "dcxo", 0x33c, BIT(24), 0);

static const struct clk_parent_data r_ahb_parents[] = {
	{ .fw_name = "dcxo" },
	{ .fw_name = "rtc32k" },
	{ .fw_name = "iosc" },
	{ .fw_name = "pll-peri0-200m" },
	{ .fw_name = "pll-peri0-300m" },
};

static const struct clk_parent_data r_apbs_parents[] = {
	{ .fw_name = "dcxo" },
	{ .fw_name = "rtc32k" },
	{ .fw_name = "iosc" },
	{ .fw_name = "pll-peri0-200m" },
	{ .fw_name = "pll-ref" },
};

static const struct clk_parent_data r_irrx_parents[] = {
	{ .fw_name = "rtc32k" },
	{ .fw_name = "dcxo" },
	{ .fw_name = "pll-ref" },
};

static const struct clk_parent_data r_pwm_parents[] = {
	{ .fw_name = "dcxo" },
	{ .fw_name = "rtc32k" },
	{ .fw_name = "iosc" },
	{ .fw_name = "pll-ref" },
};

static const struct clk_parent_data r_spi_parents[] = {
	{ .fw_name = "dcxo" },
	{ .fw_name = "pll-peri0-200m" },
	{ .fw_name = "pll-peri0-300m" },
	{ .fw_name = "pll-peri1-300m" },
	{ .fw_name = "pll-ref" },
};

static const struct clk_parent_data r_timer_parents[] = {
	{ .fw_name = "dcxo" },
	{ .fw_name = "rtc32k" },
	{ .fw_name = "iosc" },
	{ .fw_name = "pll-peri0-200m" },
	{ .fw_name = "pll-ref" },
};

static const struct clk_parent_data riscv_24m_parents[] = {
	{ .fw_name = "dcxo" },
	{ .fw_name = "osc32k" },
	{ .fw_name = "iosc" },
};
static SUNXI_CCU_M_DATA_WITH_MUX(r_ahb_clk, "r-ahb", r_ahb_parents, 0x000, 24, 3, 0, 5, 0);

static SUNXI_CCU_M_DATA_WITH_MUX(r_apbs0_clk, "r-apbs0", r_apbs_parents, 0x00c, 24, 3, 0, 5, 0);

static SUNXI_CCU_M_DATA_WITH_MUX(r_apbs1_clk, "r-apbs1", r_apbs_parents, 0x010, 24, 3, 0, 5, 0);

static SUNXI_CCU_M_DATA_WITH_MUX(r_timer0_clk, "r-timer0", r_timer_parents, 0x100, 1, 3, 4, 3, 0);

static SUNXI_CCU_M_DATA_WITH_MUX(r_timer1_clk, "r-timer1", r_timer_parents, 0x104, 1, 3, 4, 3, 0);

static SUNXI_CCU_M_DATA_WITH_MUX(r_timer2_clk, "r-timer2", r_timer_parents, 0x108, 1, 3, 4, 3, 0);

static SUNXI_CCU_M_DATA_WITH_MUX(r_timer3_clk, "r-timer3", r_timer_parents, 0x10c, 1, 3, 4, 3, 0);

static SUNXI_CCU_MUX_DATA_WITH_GATE(r_pwm_clk, "r-pwm", r_pwm_parents, 0x130, 24, 2, BIT(31), 0);

static SUNXI_CCU_MP_DATA_WITH_MUX_GATE_FEAT(r_spi_clk, "r-spi", r_spi_parents, 0x150, 0, 5, 8, 5, 24, 3, BIT(31), 0, CCU_FEATURE_DUAL_DIV);

static SUNXI_CCU_M_DATA_WITH_MUX_GATE(r_irrx_clk, "r-irrx", r_irrx_parents, 0x1c0, 24, 2, 0, 5, BIT(31), 0);

static SUNXI_CCU_MUX_DATA_WITH_GATE(riscv_24m_clk, "riscv-24m", riscv_24m_parents, 0x210, 24, 2, BIT(31), 0);

static struct ccu_common *sun60i_a733_r_ccu_clks[] = {
	&r_ahb_clk.common,
	&r_apbs0_clk.common,
	&r_apbs1_clk.common,
	&r_timer0_clk.common,
	&r_timer1_clk.common,
	&r_timer2_clk.common,
	&r_timer3_clk.common,
	&r_timer_clk.common,
	&r_twd_clk.common,
	&r_pwm_clk.common,
	&r_bus_pwm_clk.common,
	&r_spi_clk.common,
	&r_bus_spi_clk.common,
	&r_mbox_clk.common,
	&r_uart1_clk.common,
	&r_uart0_clk.common,
	&r_twi2_clk.common,
	&r_twi1_clk.common,
	&r_twi0_clk.common,
	&r_ppu_clk.common,
	&r_tzma_clk.common,
	&r_cpus_bist_clk.common,
	&r_irrx_clk.common,
	&r_bus_irrx_clk.common,
	&rtc_clk.common,
	&riscv_24m_clk.common,
	&riscv_cfg_clk.common,
	&riscv_clk.common,
	&r_cpucfg_clk.common,
	&vdd_usb2cpus_clk.common,
	&vdd_sys2usb_clk.common,
	&vdd_sys2cpus_clk.common,
	&vdd_ddr_clk.common,
	&tt_auto_clk.common,
	&cpu_icache_auto_clk.common,
	&ahbs_auto_clk_clk.common,
};

static struct clk_hw_onecell_data sun60i_a733_r_ccu_hw_clks = {
	.num	= CLK_R_NUMBER,
	.hws	= {

	},
};

static const struct sunxi_ccu_desc sun60i_a733_r_ccu_desc = {
	.ccu_clks	= sun60i_a733_r_ccu_clks,
	.num_ccu_clks	= ARRAY_SIZE(sun60i_a733_r_ccu_clks),

	.hw_clks	= &sun60i_a733_r_ccu_hw_clks,

	.resets		= NULL,
	.num_resets	= 0,
};

static int sun60i_a733_r_ccu_probe(struct platform_device *pdev)
{
	void __iomem *reg;
	int ret;

	reg = devm_platform_ioremap_resource(pdev, 0);
	if (IS_ERR(reg))
		return PTR_ERR(reg);

	ret = devm_sunxi_ccu_probe(&pdev->dev, reg, &sun60i_a733_r_ccu_desc);
	if (ret)
		return ret;

	return 0;
}

static const struct of_device_id sun60i_a733_r_ccu_ids[] = {
	{ .compatible = "allwinner,sun60i-a733-r-ccu" },
	{ }
};
MODULE_DEVICE_TABLE(of, sun60i_a733_r_ccu_ids);

static struct platform_driver sun60i_a733_r_ccu_driver = {
	.probe	= sun60i_a733_r_ccu_probe,
	.driver	= {
		.name			= "sun60i-a733-r-ccu",
		.suppress_bind_attrs	= true,
		.of_match_table		= sun60i_a733_r_ccu_ids,
	},
};
module_platform_driver(sun60i_a733_r_ccu_driver);

MODULE_IMPORT_NS("SUNXI_CCU");
MODULE_DESCRIPTION("Support for the Allwinner A733 R_CCU CCU");
MODULE_LICENSE("GPL");
