// SPDX-License-Identifier: GPL-2.0-only
// GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: generators/generate_aic8800_upstream.py

#include <linux/errno.h>
#include <linux/module.h>
#include <linux/of.h>
#include <linux/serdev.h>
#include <linux/skbuff.h>
#include <linux/unaligned.h>
#include <linux/workqueue.h>
#include <net/bluetooth/bluetooth.h>
#include <net/bluetooth/hci_core.h>

enum aic_h4_len_type {
	AIC_H4_NO_LEN,
	AIC_H4_LEN_U8,
	AIC_H4_LEN_U16,
};

struct aic_bt_data {
	struct hci_dev *hdev;
	struct serdev_device *serdev;
	struct work_struct tx_work;
	struct sk_buff_head txq;
	struct sk_buff *tx_skb;
	struct sk_buff *rx_skb;
	u16 rx_expect;
	u8 rx_hdr_len;
	u8 rx_len_off;
	u8 rx_type;
	enum aic_h4_len_type rx_len_type;
};

static void aic_bt_update_tx_stats(struct hci_dev *hdev, u8 pkt_type)
{
	switch (pkt_type) {
	case HCI_COMMAND_PKT:
		hdev->stat.cmd_tx++;
		break;
	case HCI_ACLDATA_PKT:
		hdev->stat.acl_tx++;
		break;
	case HCI_SCODATA_PKT:
		hdev->stat.sco_tx++;
		break;
	default:
		break;
	}
}

static void aic_bt_tx_work(struct work_struct *work)
{
	struct aic_bt_data *data = container_of(work, struct aic_bt_data, tx_work);
	struct hci_dev *hdev = data->hdev;

	while (1) {
		int written;
		u8 pkt_type;

		if (!data->tx_skb) {
			data->tx_skb = skb_dequeue(&data->txq);
			if (!data->tx_skb)
				break;
		}

		pkt_type = hci_skb_pkt_type(data->tx_skb);
		written = serdev_device_write_buf(data->serdev,
						 data->tx_skb->data,
						 data->tx_skb->len);
		if (written <= 0)
			break;

		hdev->stat.byte_tx += written;
		skb_pull(data->tx_skb, written);
		if (data->tx_skb->len)
			break;

		aic_bt_update_tx_stats(hdev, pkt_type);
		kfree_skb(data->tx_skb);
		data->tx_skb = NULL;
	}
}

static void aic_bt_reset_rx_state(struct aic_bt_data *data)
{
	data->rx_expect = 0;
	data->rx_hdr_len = 0;
	data->rx_len_off = 0;
	data->rx_len_type = AIC_H4_NO_LEN;
	data->rx_type = 0;
	kfree_skb(data->rx_skb);
	data->rx_skb = NULL;
}

static int aic_bt_config_pkt(struct aic_bt_data *data, u8 type)
{
	data->rx_type = type;
	switch (type) {
	case HCI_EVENT_PKT:
		data->rx_hdr_len = HCI_EVENT_HDR_SIZE;
		data->rx_len_off = 1;
		data->rx_len_type = AIC_H4_LEN_U8;
		break;
	case HCI_ACLDATA_PKT:
		data->rx_hdr_len = HCI_ACL_HDR_SIZE;
		data->rx_len_off = 2;
		data->rx_len_type = AIC_H4_LEN_U16;
		break;
	case HCI_SCODATA_PKT:
		data->rx_hdr_len = HCI_SCO_HDR_SIZE;
		data->rx_len_off = 2;
		data->rx_len_type = AIC_H4_LEN_U8;
		break;
	case HCI_ISODATA_PKT:
		data->rx_hdr_len = HCI_ISO_HDR_SIZE;
		data->rx_len_off = 2;
		data->rx_len_type = AIC_H4_LEN_U16;
		break;
	default:
		return -EILSEQ;
	}

	data->rx_expect = data->rx_hdr_len;
	data->rx_skb = bt_skb_alloc(HCI_MAX_FRAME_SIZE, GFP_ATOMIC);
	if (!data->rx_skb)
		return -ENOMEM;

	hci_skb_pkt_type(data->rx_skb) = type;
	return 0;
}

static int aic_bt_try_complete_rx(struct aic_bt_data *data)
{
	struct sk_buff *skb = data->rx_skb;
	u16 payload_len = 0;

	if (!skb || skb->len < data->rx_expect)
		return 0;

	if (data->rx_expect == data->rx_hdr_len) {
		switch (data->rx_len_type) {
		case AIC_H4_NO_LEN:
			payload_len = 0;
			break;
		case AIC_H4_LEN_U8:
			payload_len = skb->data[data->rx_len_off];
			break;
		case AIC_H4_LEN_U16:
			payload_len = get_unaligned_le16(skb->data + data->rx_len_off);
			break;
		}

		if (payload_len > skb_tailroom(skb)) {
			aic_bt_reset_rx_state(data);
			return -EMSGSIZE;
		}

		if (payload_len) {
			data->rx_expect += payload_len;
			return 0;
		}
	}

	data->rx_skb = NULL;
	data->rx_expect = 0;
	data->rx_hdr_len = 0;
	data->rx_len_type = AIC_H4_NO_LEN;
	return hci_recv_frame(data->hdev, skb);
}

static size_t aic_bt_receive_buf(struct serdev_device *serdev,
				     const u8 *buf, size_t count)
{
	struct aic_bt_data *data = serdev_device_get_drvdata(serdev);
	const u8 *p = buf;
	int ret;

	if (!data || !data->hdev)
		return count;

	while (count) {
		int copy_len;

		if (!data->rx_skb) {
			ret = aic_bt_config_pkt(data, *p++);
			count--;
			if (ret)
				continue;
			if (!count)
				break;
		}

		copy_len = min_t(int, data->rx_expect - data->rx_skb->len, count);
		skb_put_data(data->rx_skb, p, copy_len);
		p += copy_len;
		count -= copy_len;

		ret = aic_bt_try_complete_rx(data);
		if (ret)
			aic_bt_reset_rx_state(data);
	}

	data->hdev->stat.byte_rx += p - buf;
	return p - buf;
}

static void aic_bt_write_wakeup(struct serdev_device *serdev)
{
	struct aic_bt_data *data = serdev_device_get_drvdata(serdev);
	schedule_work(&data->tx_work);
}

static const struct serdev_device_ops aic_bt_serdev_ops = {
	.receive_buf = aic_bt_receive_buf,
	.write_wakeup = aic_bt_write_wakeup,
};

static int aic_bt_flush(struct hci_dev *hdev)
{
	struct aic_bt_data *data = hci_get_drvdata(hdev);
	struct sk_buff *skb;

	cancel_work_sync(&data->tx_work);
	serdev_device_write_flush(data->serdev);

	if (data->tx_skb) {
		kfree_skb(data->tx_skb);
		data->tx_skb = NULL;
	}

	while ((skb = skb_dequeue(&data->txq)))
		kfree_skb(skb);

	aic_bt_reset_rx_state(data);
	return 0;
}

static int aic_bt_open(struct hci_dev *hdev)
{
	struct aic_bt_data *data = hci_get_drvdata(hdev);

	serdev_device_set_flow_control(data->serdev, true);
	serdev_device_set_baudrate(data->serdev, 1500000);
	return 0;
}

static int aic_bt_close(struct hci_dev *hdev)
{
	return aic_bt_flush(hdev);
}

static int aic_bt_setup(struct hci_dev *hdev)
{
	struct sk_buff *skb;

	skb = __hci_cmd_sync(hdev, HCI_OP_RESET, 0, NULL, HCI_INIT_TIMEOUT);
	if (IS_ERR(skb))
		return PTR_ERR(skb);

	kfree_skb(skb);
	return 0;
}

static int aic_bt_send_frame(struct hci_dev *hdev, struct sk_buff *skb)
{
	struct aic_bt_data *data;
	struct sk_buff *nskb;
	u8 pkt_type;

	if (!skb)
		return -EINVAL;

	data = hci_get_drvdata(hdev);
	pkt_type = hci_skb_pkt_type(skb);

	nskb = bt_skb_alloc(skb->len + 1, GFP_ATOMIC);
	if (!nskb) {
		kfree_skb(skb);
		return -ENOMEM;
	}

	hci_skb_pkt_type(nskb) = pkt_type;
	skb_put_u8(nskb, pkt_type);
	skb_put_data(nskb, skb->data, skb->len);
	kfree_skb(skb);

	skb_queue_tail(&data->txq, nskb);
	schedule_work(&data->tx_work);
	return 0;
}

static int aic_bt_serdev_probe(struct serdev_device *serdev)
{
	struct aic_bt_data *data;
	struct hci_dev *hdev;
	int ret;

	data = devm_kzalloc(&serdev->dev, sizeof(*data), GFP_KERNEL);
	if (!data)
		return -ENOMEM;

	data->serdev = serdev;
	serdev_device_set_drvdata(serdev, data);
	serdev_device_set_client_ops(serdev, &aic_bt_serdev_ops);

	INIT_WORK(&data->tx_work, aic_bt_tx_work);
	skb_queue_head_init(&data->txq);
	aic_bt_reset_rx_state(data);

	hdev = hci_alloc_dev();
	if (!hdev)
		return -ENOMEM;

	data->hdev = hdev;
	hdev->bus = HCI_UART;
	SET_HCIDEV_DEV(hdev, &serdev->dev);

	hdev->open  = aic_bt_open;
	hdev->close = aic_bt_close;
	hdev->setup = aic_bt_setup;
	hdev->flush = aic_bt_flush;
	hdev->send = aic_bt_send_frame;
	hdev->manufacturer = 0x00;

	hci_set_drvdata(hdev, data);

	ret = serdev_device_open(serdev);
	if (ret) {
		hci_free_dev(hdev);
		return ret;
	}

	serdev_device_set_flow_control(serdev, true);
	serdev_device_set_baudrate(serdev, 1500000);

	ret = hci_register_dev(hdev);
	if (ret) {
		hci_free_dev(hdev);
		cancel_work_sync(&data->tx_work);
		serdev_device_close(serdev);
		return ret;
	}

	return 0;
}

static void aic_bt_serdev_remove(struct serdev_device *serdev)
{
	struct aic_bt_data *data = serdev_device_get_drvdata(serdev);

	if (!data || !data->hdev)
		return;

	cancel_work_sync(&data->tx_work);
	hci_unregister_dev(data->hdev);
	hci_free_dev(data->hdev);
	aic_bt_reset_rx_state(data);

	if (data->tx_skb) {
		kfree_skb(data->tx_skb);
		data->tx_skb = NULL;
	}

	skb_queue_purge(&data->txq);
	serdev_device_close(serdev);
}

static const struct of_device_id aic_bt_of_match[] = {
	{ .compatible = "aicsemi,aic8800d80-bt" },
	{ }
};
MODULE_DEVICE_TABLE(of, aic_bt_of_match);

static struct serdev_device_driver aic_bt_serdev_driver = {
	.probe = aic_bt_serdev_probe,
	.remove = aic_bt_serdev_remove,
	.driver = {
		.name = "hci_aic8800",
		.of_match_table = aic_bt_of_match,
	},
};
module_serdev_device_driver(aic_bt_serdev_driver);

MODULE_LICENSE("GPL");
MODULE_DESCRIPTION("AIC8800 Bluetooth UART transport");
