// SPDX-License-Identifier: GPL-2.0-only
// GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: generators/generate_aic8800_upstream.py

#include <linux/errno.h>
#include <linux/firmware.h>
#include <linux/module.h>
#include <linux/string.h>
#include "bt_fw.h"

static const char * const aic8800_bt_patch_table_fallbacks[] = {
            "aic8800d80/fw_patch_table_8800d80_u02.bin",
            "aic8800d80/fw_patch_table_8800d80.bin",
};

static const char * const aic8800_bt_patch_fallbacks[] = {
            "aic8800d80/fw_patch_8800d80_u02.bin",
            "aic8800d80/fw_patch_8800d80.bin",
};

static const char * const aic8800_bt_patch_ext_fallbacks[] = {
            "aic8800d80/fw_patch_8800d80_u02_ext",
};

static const char * const aic8800_bt_adid_fallbacks[] = {
            "aic8800d80/fw_adid_8800d80_u02.bin",
            "aic8800d80/fw_adid_8800d80.bin",
};

static int aic8800_request_with_fallbacks(struct device *dev,
					const char *preferred,
					const char * const *fallbacks,
					size_t fallback_count)
{
	const struct firmware *fw;
	int ret;
	size_t i;

	if (!dev || !preferred)
		return -EINVAL;

	ret = request_firmware(&fw, preferred, dev);
	if (!ret) {
		release_firmware(fw);
		return 0;
	}

	for (i = 0; i < fallback_count; i++) {
		if (!fallbacks[i] || !strcmp(preferred, fallbacks[i]))
			continue;

		ret = request_firmware(&fw, fallbacks[i], dev);
		if (!ret) {
			release_firmware(fw);
			return 0;
		}
	}

	return ret;
}

int aic8800_bt_request_patch_table(struct device *dev, const char *preferred)
{
	return aic8800_request_with_fallbacks(
		dev,
		preferred,
		aic8800_bt_patch_table_fallbacks,
		ARRAY_SIZE(aic8800_bt_patch_table_fallbacks)
	);
}

int aic8800_bt_request_patch_blob(struct device *dev, const char *preferred)
{
	return aic8800_request_with_fallbacks(
		dev,
		preferred,
		aic8800_bt_patch_fallbacks,
		ARRAY_SIZE(aic8800_bt_patch_fallbacks)
	);
}

int aic8800_bt_request_adid_blob(struct device *dev, const char *preferred)
{
	return aic8800_request_with_fallbacks(
		dev,
		preferred,
		aic8800_bt_adid_fallbacks,
		ARRAY_SIZE(aic8800_bt_adid_fallbacks)
	);
}

int aic8800_bt_request_patch_ext_blob(struct device *dev, const char *preferred)
{
	return aic8800_request_with_fallbacks(
		dev,
		preferred,
		aic8800_bt_patch_ext_fallbacks,
		ARRAY_SIZE(aic8800_bt_patch_ext_fallbacks)
	);
}

EXPORT_SYMBOL_GPL(aic8800_bt_request_patch_table);
EXPORT_SYMBOL_GPL(aic8800_bt_request_patch_blob);
EXPORT_SYMBOL_GPL(aic8800_bt_request_patch_ext_blob);
EXPORT_SYMBOL_GPL(aic8800_bt_request_adid_blob);
