/* SPDX-License-Identifier: GPL-2.0-only */
/* GENERATED FILE - DO NOT EDIT MANUALLY */
/* Generated by: generators/generate_aic8800_upstream.py */

#ifndef AIC8800_BT_FW_H
#define AIC8800_BT_FW_H

#include <linux/device.h>

int aic8800_bt_request_patch_table(struct device *dev, const char *preferred);
int aic8800_bt_request_patch_blob(struct device *dev, const char *preferred);
int aic8800_bt_request_patch_ext_blob(struct device *dev, const char *preferred);
int aic8800_bt_request_adid_blob(struct device *dev, const char *preferred);

#endif
