// SPDX-License-Identifier: GPL-2.0-only
// GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: generators/generate_aic8800_upstream.py

#include <linux/bitops.h>
#include <linux/etherdevice.h>
#include <linux/errno.h>
#include <linux/ieee80211.h>
#include <linux/string.h>
#include <net/cfg80211.h>
#include "cfg80211_core.h"

static struct aic8800_core *aic8800_core_from_wiphy(struct wiphy *wiphy)
{
	if (!wiphy)
		return NULL;

	return *((struct aic8800_core **)wiphy_priv(wiphy));
}

static int aic8800_cfg80211_scan(struct wiphy *wiphy,
				    struct cfg80211_scan_request *request)
{
	struct cfg80211_scan_info info = {
		.aborted = false,
	};

	(void)wiphy;
	if (!request)
		return -EINVAL;

	cfg80211_scan_done(request, &info);
	return 0;
}

static int aic8800_cfg80211_connect(struct wiphy *wiphy,
				       struct net_device *dev,
				       struct cfg80211_connect_params *sme)
{
	struct aic8800_core *core = aic8800_core_from_wiphy(wiphy);

	(void)wiphy;

	if (!dev || !sme || !core)
		return -EINVAL;

	if (sme->bssid)
		ether_addr_copy(core->bssid, sme->bssid);
	else
		eth_zero_addr(core->bssid);

	core->link_up = true;

	cfg80211_connect_result(
		dev,
		core->bssid,
		NULL,
		0,
		NULL,
		0,
		WLAN_STATUS_SUCCESS,
		GFP_KERNEL
	);
	return 0;
}

static int aic8800_cfg80211_disconnect(struct wiphy *wiphy,
					  struct net_device *dev,
					  u16 reason_code)
{
	struct aic8800_core *core = aic8800_core_from_wiphy(wiphy);

	(void)wiphy;

	if (!dev || !core)
		return -EINVAL;

	core->link_up = false;
	eth_zero_addr(core->bssid);

	cfg80211_disconnected(dev, reason_code, NULL, 0, true, GFP_KERNEL);
	return 0;
}

static int aic8800_cfg80211_change_virtual_intf(struct wiphy *wiphy,
						     struct net_device *dev,
						     enum nl80211_iftype type,
						     struct vif_params *params)
{
	(void)wiphy;
	(void)dev;
	(void)params;

	if (type == NL80211_IFTYPE_STATION)
		return 0;

	return -EOPNOTSUPP;
}

static const struct cfg80211_ops aic8800_cfg80211_ops = {
	.scan = aic8800_cfg80211_scan,
	.connect = aic8800_cfg80211_connect,
	.disconnect = aic8800_cfg80211_disconnect,
	.change_virtual_intf = aic8800_cfg80211_change_virtual_intf,
};

int aic8800_cfg80211_register(struct aic8800_core *core)
{
	struct wiphy *wiphy;
	int ret;

	if (!core || !core->dev)
		return -EINVAL;

	wiphy = wiphy_new(&aic8800_cfg80211_ops, sizeof(struct aic8800_core *));
	if (!wiphy)
		return -ENOMEM;

	*((struct aic8800_core **)wiphy_priv(wiphy)) = core;

	set_wiphy_dev(wiphy, core->dev);
	wiphy->max_scan_ssids = 1;
	wiphy->interface_modes = BIT(NL80211_IFTYPE_STATION);
	strscpy(wiphy->fw_version, "aic8800-draft", sizeof(wiphy->fw_version));

	ret = wiphy_register(wiphy);
	if (ret) {
		wiphy_free(wiphy);
		return ret;
	}

	core->wiphy = wiphy;
	return 0;
}

void aic8800_cfg80211_unregister(struct aic8800_core *core)
{
	if (!core || !core->wiphy)
		return;

	wiphy_unregister(core->wiphy);
	wiphy_free(core->wiphy);
	core->wiphy = NULL;
}
