// SPDX-License-Identifier: GPL-2.0-only
// GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: generators/generate_aic8800_upstream.py

#include <linux/errno.h>
#include <linux/firmware.h>
#include <linux/module.h>
#include <linux/string.h>
#include "core_types.h"

static const char * const aic8800_fw_fallbacks[] = {
            "aic8800d80/fmacfw_8800d80.bin",
            "aic8800d80/fmacfw_8800d80_u02.bin",
            "aic8800d80/fmacfw_8800d80_h_u02.bin",
};

static const char *aic8800_core_fw_name(struct aic8800_core *core)
{
	if (!core)
		return NULL;

	if (core->fw_override[0])
		return core->fw_override;

	return core->fw_name;
}

int aic8800_core_release_firmware(struct aic8800_core *core)
{
	int ret = 0;

	if (!core)
		return -EINVAL;

	if (core->fw_hooks && core->fw_hooks->pre_unload) {
		ret = core->fw_hooks->pre_unload(core);
		if (ret)
			return ret;
	}

	if (core->fw_data) {
		release_firmware(core->fw_data);
		core->fw_data = NULL;
	}
	core->fw_loaded[0] = '\0';

	if (core->fw_hooks && core->fw_hooks->post_unload)
		core->fw_hooks->post_unload(core, 0);

	return 0;
}

int aic8800_core_set_fw_override(struct aic8800_core *core, const char *name)
{
	if (!core || !name || !name[0])
		return -EINVAL;

	strscpy(core->fw_override, name, sizeof(core->fw_override));
	return 0;
}

void aic8800_core_clear_fw_override(struct aic8800_core *core)
{
	if (!core)
		return;

	core->fw_override[0] = '\0';
}

const char *aic8800_core_get_fw_active_name(struct aic8800_core *core)
{
	return aic8800_core_fw_name(core);
}

void aic8800_core_set_fw_hooks(struct aic8800_core *core,
				 const struct aic8800_fw_hooks *hooks)
{
	if (!core)
		return;

	core->fw_hooks = hooks;
}

int aic8800_core_request_firmware(struct aic8800_core *core)
{
	const struct firmware *fw;
	const char *req_name;
	int ret;
	int i;

	if (!core || !core->dev)
		return -EINVAL;

	req_name = aic8800_core_fw_name(core);
	if (!req_name)
		return -EINVAL;

	ret = aic8800_core_release_firmware(core);
	if (ret)
		return ret;

	if (core->fw_hooks && core->fw_hooks->pre_load) {
		ret = core->fw_hooks->pre_load(core, req_name);
		if (ret)
			return ret;
	}

	ret = request_firmware(&fw, req_name, core->dev);
	if (!ret) {
		core->fw_data = fw;
		strscpy(core->fw_loaded, req_name, sizeof(core->fw_loaded));
		if (core->fw_hooks && core->fw_hooks->post_load)
			core->fw_hooks->post_load(core, req_name, 0);
		return 0;
	}

	for (i = 0; i < ARRAY_SIZE(aic8800_fw_fallbacks); i++) {
		if (!strcmp(req_name, aic8800_fw_fallbacks[i]))
			continue;

		ret = request_firmware(&fw, aic8800_fw_fallbacks[i], core->dev);
		if (!ret) {
			core->fw_data = fw;
			strscpy(core->fw_loaded, aic8800_fw_fallbacks[i],
				sizeof(core->fw_loaded));
			if (core->fw_hooks && core->fw_hooks->post_load)
				core->fw_hooks->post_load(core, aic8800_fw_fallbacks[i], 0);
			return 0;
		}
	}

	if (core->fw_hooks && core->fw_hooks->post_load)
		core->fw_hooks->post_load(core, req_name, ret);

	return ret;
}

EXPORT_SYMBOL_GPL(aic8800_core_request_firmware);
EXPORT_SYMBOL_GPL(aic8800_core_release_firmware);
EXPORT_SYMBOL_GPL(aic8800_core_set_fw_override);
EXPORT_SYMBOL_GPL(aic8800_core_clear_fw_override);
EXPORT_SYMBOL_GPL(aic8800_core_get_fw_active_name);
EXPORT_SYMBOL_GPL(aic8800_core_set_fw_hooks);
