#!/usr/bin/env python3
"""
Register map extractor from vendor BSP headers.

Automatically parses vendor C header files to extract:
- Register offsets
- Bit field positions and masks
- Clock/reset indices
- Memory map addresses

This eliminates manual transcription of register maps.

Usage:
    python3 generators/extract_registers.py \\
        --input /path/to/vendor/bsp/include \\
        --output generators/data/registers.json
"""

import re
import json
import argparse
from pathlib import Path


class RegisterExtractor:
    """Extract register definitions from vendor C headers."""

    def __init__(self):
        self.registers = {}
        self.clocks = {}
        self.resets = {}
        self.memory_map = {}

    def extract_define(self, line):
        """Extract a #define constant."""
        # Match: #define NAME value
        # Handle hex, decimal, and simple expressions
        match = re.match(r"#define\s+(\w+)\s+(0x[0-9a-fA-F]+|\d+)", line)
        if match:
            name = match.group(1)
            value = match.group(2)
            try:
                return name, int(value, 0)
            except ValueError:
                return None
        return None

    def extract_register_offset(self, line):
        """Extract register offset from patterns like: #define REG_NAME 0x020"""
        result = self.extract_define(line)
        if result:
            name, value = result
            # Filter for register-like names (contain REG, OFFSET, or similar)
            if any(
                keyword in name.upper() for keyword in ["REG", "OFFSET", "BASE", "ADDR"]
            ):
                if value < 0x10000:  # Likely an offset, not an address
                    return name, value
        return None

    def extract_memory_address(self, line):
        """Extract memory mapped addresses."""
        result = self.extract_define(line)
        if result:
            name, value = result
            # Full memory addresses are usually larger
            if value >= 0x01000000:
                return name, hex(value)
        return None

    def parse_file(self, filepath):
        """Parse a single header file."""
        with open(filepath) as f:
            content = f.read()

        category = self._categorize_file(filepath.name)

        for line in content.split("\n"):
            line = line.strip()

            # Extract register offsets
            reg = self.extract_register_offset(line)
            if reg:
                name, offset = reg
                if category not in self.registers:
                    self.registers[category] = {}
                self.registers[category][name] = f"0x{offset:03x}"

            # Extract memory addresses
            addr = self.extract_memory_address(line)
            if addr:
                name, value = addr
                self.memory_map[name] = value

    def _categorize_file(self, filename):
        """Categorize a header file by subsystem."""
        filename = filename.lower()
        if "ccu" in filename or "clock" in filename:
            return "ccu"
        elif "pinctrl" in filename or "gpio" in filename:
            return "pinctrl"
        elif "uart" in filename:
            return "uart"
        elif "mmc" in filename or "sd" in filename:
            return "mmc"
        elif "dma" in filename:
            return "dma"
        elif "thermal" in filename or "ths" in filename:
            return "thermal"
        elif "usb" in filename:
            return "usb"
        elif "gmac" in filename or "eth" in filename:
            return "ethernet"
        else:
            return "misc"

    def to_json(self):
        """Export extracted data as JSON."""
        return {
            "registers": self.registers,
            "memory_map": self.memory_map,
        }

    def to_c_header(self):
        """Export extracted register offsets as a C header."""
        lines = [
            "/* SPDX-License-Identifier: GPL-2.0 */",
            "/* Auto-generated register definitions */",
            "/* Generated by: extract_registers.py */",
            "",
            "#ifndef _SUN60I_A733_REGS_H_",
            "#define _SUN60I_A733_REGS_H_",
            "",
        ]

        for category, regs in sorted(self.registers.items()):
            lines.append(f"/* {category.upper()} registers */")
            for name, offset in sorted(regs.items(), key=lambda x: int(x[1], 0)):
                lines.append(f"#define {name:40s} {offset}")
            lines.append("")

        lines.append("#endif /* _SUN60I_A733_REGS_H_ */")
        lines.append("")

        return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Extract registers from vendor headers"
    )
    parser.add_argument(
        "--input", "-i", required=True, help="Input directory with vendor headers"
    )
    parser.add_argument(
        "--output", "-o", default="registers.json", help="Output JSON file"
    )
    parser.add_argument("--c-header", "-c", help="Also generate C header")
    args = parser.parse_args()

    extractor = RegisterExtractor()
    input_dir = Path(args.input)

    # Parse all .h files
    for header_file in input_dir.rglob("*.h"):
        print(f"Parsing {header_file}...")
        extractor.parse_file(header_file)

    # Write JSON output
    output_path = Path(args.output)
    with open(output_path, "w") as f:
        json.dump(extractor.to_json(), f, indent=2)
    print(f"\nJSON output: {output_path}")

    # Optionally generate C header
    if args.c_header:
        with open(args.c_header, "w") as f:
            f.write(extractor.to_c_header())
        print(f"C header: {args.c_header}")

    # Print summary
    total_regs = sum(len(regs) for regs in extractor.registers.values())
    print(f"\nExtracted:")
    print(f"  {total_regs} register offsets")
    print(f"  {len(extractor.memory_map)} memory addresses")
    print(f"  Across {len(extractor.registers)} categories")


if __name__ == "__main__":
    main()
