#!/usr/bin/env python3
"""
Code generator for sun60i-a733 CCU (Clock Controller Unit) driver.

Reads clock definitions from JSON and generates C code using the
mainline sunxi-ng framework macros.

Usage:
    python3 generators/generate_ccu.py > drivers/clk/sunxi-ng/ccu-sun60i-a733.c
"""

import json
import sys
from pathlib import Path


def generate_ccu_header():
    return """// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (C) 2026 Alexander Grec
 *
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: generators/generate_ccu.py
 * Source data:  generators/data/ccu-main.json
 */

#include <linux/clk-provider.h>
#include <linux/io.h>
#include <linux/module.h>
#include <linux/platform_device.h>

#include <dt-bindings/clock/sun60i-a733-ccu.h>
#include <dt-bindings/reset/sun60i-a733-ccu.h>

#include "../clk.h"
#include "ccu_common.h"
#include "ccu_reset.h"
#include "ccu_div.h"
#include "ccu_gate.h"
#include "ccu_mp.h"
#include "ccu_nkmp.h"

static const struct clk_parent_data osc24M[] = {
	{ .fw_name = "hosc" }
};

"""


def generate_pll(pll):
    """Generate a single PLL definition."""
    name = pll["name"]
    reg = pll["reg"]
    type_ = pll.get("type", "nkmp")

    if type_ == "nkmp":
        return f'''static struct ccu_nkmp {name}_clk = {{
	.enable		= BIT(27),
	.lock		= BIT(28),
	.n		= _SUNXI_CCU_MULT_MIN(8, 8, 11),
	.m		= _SUNXI_CCU_DIV(1, 1),
	.p		= _SUNXI_CCU_DIV(0, 1),
	.common		= {{
		.reg		= 0x{reg:03x},
		.hw.init	= CLK_HW_INIT_PARENTS_DATA("{name.replace("_", "-")}", osc24M,
							   &ccu_nkmp_ops,
							   CLK_SET_RATE_GATE |
							   CLK_IS_CRITICAL),
	}},
}};

'''
    elif type_ == "nm":
        return f'''static struct ccu_nm {name}_clk = {{
	.enable		= BIT(27),
	.lock		= BIT(28),
	.n		= _SUNXI_CCU_MULT_MIN(8, 8, 11),
	.m		= _SUNXI_CCU_DIV(1, 1),
	.common		= {{
		.reg		= 0x{reg:03x},
		.hw.init	= CLK_HW_INIT_PARENTS_DATA("{name.replace("_", "-")}", osc24M, &ccu_nm_ops,
							   CLK_SET_RATE_GATE),
	}},
}};

'''
    return f"/* TODO: PLL type {type_} for {name} */\n\n"


def parse_reg(reg):
    """Parse register offset from string or int."""
    if isinstance(reg, str):
        return int(reg, 0)
    return reg


def generate_divider(clk):
    """Generate a divider clock."""
    name = clk["name"]
    parent = clk["parent"]
    reg = parse_reg(clk["reg"])
    shift = clk.get("shift", 0)
    width = clk.get("width", 3)
    flags = clk.get("flags", [])

    flag_str = ""
    if "critical" in flags:
        flag_str = " | CLK_IS_CRITICAL"

    parent_hws = f"{parent.replace('-', '_')}_hws"

    return f'''static SUNXI_CCU_M_HWS({name.replace("-", "_")}_clk, "{name}",
		       {parent_hws}, 0x{reg:03x}, {shift}, {width}, 0{flag_str});

'''


def generate_fixed_factor(clk):
    """Generate a fixed factor clock."""
    name = clk["name"]
    parent = clk["parent"]
    mult = clk["mult"]
    div = clk["div"]

    parent_hws = f"{parent.replace('-', '_')}_hws"

    return f'''static CLK_FIXED_FACTOR_HWS({name.replace("-", "_")}_clk, "{name}",
				{parent_hws}, {mult}, {div},
				CLK_SET_RATE_PARENT);

'''


def generate_gate(clk):
    """Generate a gate clock."""
    name = clk["name"]
    parent = clk.get("parent", "ahb")
    reg = parse_reg(clk["reg"])
    bit = clk["bit"]
    flags = clk.get("flags", [])

    flag_str = ""
    if "critical" in flags:
        flag_str = " | CLK_IS_CRITICAL"

    parent_hws = f"{parent.replace('-', '_')}_hws"

    return f'''static SUNXI_CCU_GATE_HWS({name.replace("-", "_")}_clk, "{name}",
				{parent_hws},
				0x{reg:03x}, {bit}, 0{flag_str});

'''


def generate_parent_arrays(clocks):
    """Generate parent hw arrays for referenced clocks."""
    arrays = []
    seen = set()

    for clk in clocks:
        if clk["type"] == "pll":
            name = clk["name"].replace("-", "_")
            if name not in seen:
                seen.add(name)
                arrays.append(f"""static const struct clk_hw *{name}_hws[] = {{
	&{name}_clk.common.hw
}};

""")
        elif "parent" in clk:
            parent = clk["parent"].replace("-", "_")
            if parent not in seen and parent != "osc24M":
                seen.add(parent)
                # We'll add arrays as we encounter them
                pass

    return "".join(arrays)


def generate_hw_table(clocks):
    """Generate the clk_hw_onecell_data table."""
    entries = []

    for clk in clocks:
        if clk["type"] == "fixed":
            continue
        name = clk["name"].replace("-", "_")
        entries.append(f"\t[CLK_{clk['id']}]\t= &{name}_clk.common.hw,")

    entries_str = "\n".join(entries)

    return f"""static struct clk_hw_onecell_data a733_hw_clks = {{
	.hws	= {{
{entries_str}
	}},
	.num	= CLK_NUMBER,
}};

"""


def generate_reset_table(data):
    """Generate reset definitions."""
    resets = data.get("resets", [])
    if not resets:
        return "/* No resets defined */\n\n"

    entries = []
    for rst in resets:
        reg = parse_reg(rst["reg"])
        entries.append(f"\t[RST_{rst['id']}]\t= {{ 0x{reg:03x}, {rst['bit']} }},")

    return f"""static struct ccu_reset_map a733_ccu_resets[] = {{
{chr(10).join(entries)}
}};

"""


def generate_probe(data):
    """Generate the probe function."""
    return """static int sun60i_a733_ccu_probe(struct platform_device *pdev)
{
	void __iomem *reg;
	struct clk_hw_onecell_data *hw_data;
	int ret;

	reg = devm_platform_ioremap_resource(pdev, 0);
	if (IS_ERR(reg))
		return PTR_ERR(reg);

	hw_data = devm_kmemdup(&pdev->dev, &a733_hw_clks,
			       sizeof(a733_hw_clks), GFP_KERNEL);
	if (!hw_data)
		return -ENOMEM;

	/* Register all clocks */
	ret = devm_ccu_probe(pdev, reg, hw_data, a733_ccu_resets,
			     ARRAY_SIZE(a733_ccu_resets));
	if (ret)
		return ret;

	return devm_of_clk_add_hw_provider(&pdev->dev, of_clk_hw_onecell_get,
					   hw_data);
}

static const struct of_device_id sun60i_a733_ccu_match[] = {
	{ .compatible = "allwinner,sun60i-a733-ccu" },
	{ }
};

static struct platform_driver sun60i_a733_ccu_driver = {
	.probe	= sun60i_a733_ccu_probe,
	.driver	= {
		.name		= "sun60i-a733-ccu",
		.of_match_table	= sun60i_a733_ccu_match,
	},
};
builtin_platform_driver(sun60i_a733_ccu_driver);
"""


def generate_ccu(data):
    """Generate full CCU driver C code."""
    code = generate_ccu_header()

    # Generate PLLs first
    for clk in data["clocks"]:
        if clk["type"] == "pll":
            code += generate_pll(clk)

    # Generate parent arrays
    code += generate_parent_arrays(data["clocks"])

    # Generate dividers and gates
    for clk in data["clocks"]:
        if clk["type"] == "divider":
            code += generate_divider(clk)
        elif clk["type"] == "gate":
            code += generate_gate(clk)

    # Hardware table
    code += generate_hw_table(data["clocks"])

    # Reset table
    code += generate_reset_table(data)

    # Probe function
    code += generate_probe(data)

    return code


if __name__ == "__main__":
    data_file = Path(__file__).parent / "data" / "ccu-main.json"

    if not data_file.exists():
        print(f"Error: {data_file} not found", file=sys.stderr)
        sys.exit(1)

    with open(data_file) as f:
        data = json.load(f)

    print(generate_ccu(data))
