#!/usr/bin/env python3
"""
Code generator for Allwinner sun60i-a733 mainline Linux drivers.

This script reads structured hardware descriptions and generates
repetitive C driver code using the mainline sunxi-ng and pinctrl-sunxi
frameworks. This minimizes manual C coding and potential bugs.

Usage:
    python3 generators/generate_pinctrl.py > drivers/pinctrl/sunxi/pinctrl-sun60i-a733.c
    python3 generators/generate_ccu.py > drivers/clk/sunxi-ng/ccu-sun60i-a733.c
"""

import json
import sys
from pathlib import Path

# --- Pinctrl Generator ---


def generate_pinctrl(data):
    """Generate pinctrl-sun60i-a733.c from JSON description."""

    banks = data["banks"]
    irq_map = data["irq_bank_map"]
    irq_muxes = data["irq_bank_muxes"]
    flags = data.get("flags", [])

    nr_banks = ", ".join(str(banks.get(f"P{chr(65 + i)}", 0)) for i in range(11))
    irq_map_str = ", ".join(str(x) for x in irq_map)
    irq_muxes_str = ", ".join(str(x) for x in irq_muxes)

    flag_vals = []
    if "new_reg_layout" in flags:
        flag_vals.append("SUNXI_PINCTRL_NEW_REG_LAYOUT")
    if "eleven_banks" in flags:
        flag_vals.append("SUNXI_PINCTRL_ELEVEN_BANKS")

    flag_str = " | ".join(flag_vals) if flag_vals else "0"

    c_code = f"""// SPDX-License-Identifier: GPL-2.0
/*
 * Allwinner A733 SoC pinctrl driver.
 *
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: generators/generate_pinctrl.py
 * Source data:  generators/data/pinctrl-main.json
 */

#include <linux/module.h>
#include <linux/platform_device.h>
#include <linux/of.h>
#include <linux/of_device.h>
#include <linux/pinctrl/pinctrl.h>

#include "pinctrl-sunxi.h"

static const u8 a733_nr_bank_pins[SUNXI_PINCTRL_MAX_BANKS] =
/*	  PA  PB  PC  PD  PE  PF  PG  PH  PI  PJ  PK */
	{{ {nr_banks} }};

static const unsigned int a733_irq_bank_map[] = {{ {irq_map_str} }};

static const u8 a733_irq_bank_muxes[SUNXI_PINCTRL_MAX_BANKS] =
/*	  PA  PB  PC  PD  PE  PF  PG  PH  PI  PJ  PK */
	{{ {irq_muxes_str} }};

static struct sunxi_pinctrl_desc a733_pinctrl_data = {{
	.irq_banks = ARRAY_SIZE(a733_irq_bank_map),
	.irq_bank_map = a733_irq_bank_map,
	.irq_read_needs_mux = true,
	.io_bias_cfg_variant = BIAS_VOLTAGE_PIO_POW_MODE_SEL,
}};

static int a733_pinctrl_probe(struct platform_device *pdev)
{{
	return sunxi_pinctrl_dt_table_init(pdev, a733_nr_bank_pins,
					   a733_irq_bank_muxes,
					   &a733_pinctrl_data,
					   {flag_str});
}}

static const struct of_device_id a733_pinctrl_match[] = {{
	{{ .compatible = "allwinner,sun60i-a733-pinctrl", }},
	{{}}
}};

static struct platform_driver a733_pinctrl_driver = {{
	.probe	= a733_pinctrl_probe,
	.driver	= {{
		.name		= "sun60i-a733-pinctrl",
		.of_match_table	= a733_pinctrl_match,
	}},
}};
builtin_platform_driver(a733_pinctrl_driver);
"""
    return c_code


# --- Main ---

if __name__ == "__main__":
    data_file = Path(__file__).parent / "data" / "pinctrl-main.json"

    if not data_file.exists():
        print(f"Error: {data_file} not found", file=sys.stderr)
        sys.exit(1)

    with open(data_file) as f:
        data = json.load(f)

    print(generate_pinctrl(data))
