#!/usr/bin/env python3
"""Generate AIC8800D80 upstream draft artifacts from JSON data."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from textwrap import dedent


ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "generators" / "data" / "aic8800-upstream.json"


def load_data(path: Path) -> dict:
    return json.loads(path.read_text())


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def gen_wifi_binding(data: dict) -> str:
    c0, c1 = data["wifi_compatible"]
    maint = data["maintainer"]
    return dedent(
        f"""\
        # SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause)
        # GENERATED FILE - DO NOT EDIT MANUALLY
        # Generated by: generators/generate_aic8800_upstream.py
        %YAML 1.2
        ---
        $id: http://devicetree.org/schemas/net/wireless/aicsemi,aic8800.yaml#
        $schema: http://devicetree.org/meta-schemas/core.yaml#

        title: AICsemi AIC8800 SDIO WiFi

        maintainers:
          - {maint['name']} <{maint['email']}>

        description: |
          Binding for AICsemi AIC8800 series WiFi devices connected over SDIO.

        allOf:
          - $ref: /schemas/mmc/mmc-controller.yaml#

        properties:
          compatible:
            items:
              - const: {c0}
              - const: {c1}

          reg:
            maxItems: 1

          interrupts:
            maxItems: 1
            description: Optional OOB host wake interrupt from the WiFi chip.

          interrupt-names:
            items:
              - const: host-wake

          reset-gpios:
            maxItems: 1
            description: Optional reset line to the WiFi device.

          vmmc-supply: true
          vqmmc-supply: true
          wakeup-source: true

        required:
          - compatible
          - reg

        additionalProperties: false

        examples:
          - |
            mmc1: mmc@4021000 {{
              #address-cells = <1>;
              #size-cells = <0>;
              bus-width = <4>;
              non-removable;

              wifi@1 {{
                reg = <1>;
                compatible = "{c0}", "{c1}";
                interrupts-extended = <&pio 6 4 IRQ_TYPE_LEVEL_LOW>;
                interrupt-names = "host-wake";
                reset-gpios = <&r_pio 0 1 GPIO_ACTIVE_LOW>;
                wakeup-source;
              }};
            }};
        """
    )


def gen_bt_binding(data: dict) -> str:
    c0, c1 = data["bt_compatible"]
    speed = data["bt_max_speed"]
    maint = data["maintainer"]
    return dedent(
        f"""\
        # SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause)
        # GENERATED FILE - DO NOT EDIT MANUALLY
        # Generated by: generators/generate_aic8800_upstream.py
        %YAML 1.2
        ---
        $id: http://devicetree.org/schemas/net/bluetooth/aicsemi,aic8800-bt.yaml#
        $schema: http://devicetree.org/meta-schemas/core.yaml#

        title: AICsemi AIC8800 UART Bluetooth

        maintainers:
          - {maint['name']} <{maint['email']}>

        description: |
          Binding for AICsemi AIC8800 series Bluetooth controller exposed through
          a UART (serdev) transport.

        properties:
          compatible:
            items:
              - const: {c0}
              - const: {c1}

          enable-gpios:
            maxItems: 1
            description: Optional Bluetooth enable line.

          host-wakeup-gpios:
            maxItems: 1
            description: Optional wake line from controller to host.

          device-wakeup-gpios:
            maxItems: 1
            description: Optional wake line from host to controller.

          max-speed:
            $ref: /schemas/types.yaml#/definitions/uint32
            description: Maximum operating UART speed after setup.

          firmware-name:
            $ref: /schemas/types.yaml#/definitions/string
            description: Optional firmware path override.

        required:
          - compatible

        additionalProperties: false

        examples:
          - |
            uart1: serial@2500400 {{
              bluetooth {{
                compatible = "{c0}", "{c1}";
                max-speed = <{speed}>;
                enable-gpios = <&r_pio 0 1 GPIO_ACTIVE_HIGH>;
              }};
            }};
        """
    )


def gen_dts_fragment(data: dict) -> str:
    w0, w1 = data["wifi_compatible"]
    b0, b1 = data["bt_compatible"]
    speed = data["bt_max_speed"]
    return dedent(
        f"""\
        /* GENERATED FILE - DO NOT EDIT MANUALLY */
        /* Generated by: generators/generate_aic8800_upstream.py */
        /* Draft fragment for future upstream DTS patch */

        &mmc1 {{
        \t#address-cells = <1>;
        \t#size-cells = <0>;
        \tbus-width = <4>;
        \tnon-removable;
        \tmmc-pwrseq = <&wifi_pwrseq>;
        \tstatus = "okay";

        \twifi@1 {{
        \t\treg = <1>;
        \t\tcompatible = "{w0}", "{w1}";
        \t\tinterrupt-parent = <&pio>;
        \t\tinterrupts = <6 4 IRQ_TYPE_LEVEL_LOW>;
        \t\tinterrupt-names = "host-wake";
        \t\twakeup-source;
        \t}};
        }};

        &uart1 {{
        \tpinctrl-names = "default";
        \tpinctrl-0 = <&uart1_pins>;
        \tuart-has-rtscts;
        \tstatus = "okay";

        \tbluetooth {{
        \t\tcompatible = "{b0}", "{b1}";
        \t\tmax-speed = <{speed}>;
        \t}};
        }};
        """
    )


def gen_kernel_draft_files(data: dict) -> dict[str, str]:
    vendor = data["sdio_id"]["vendor"]
    device = data["sdio_id"]["device"]
    fw_probe = data["wifi_fw_probe_name"]
    fw_dl_addr = data.get("wifi_fw_download_addr", "0x00120000")
    tx_port_addr = data.get("wifi_tx_port_addr", "0x00000000")
    rx_len_port_addr = data.get("wifi_rx_len_port_addr", "0x00000000")
    rx_data_port_addr = data.get("wifi_rx_data_port_addr", "0x00000000")
    rx_budget = str(data.get("wifi_rx_budget", 8))
    rx_work_max_batches = str(data.get("wifi_rx_work_max_batches", 32))
    rx_queue_limit = str(data.get("wifi_rx_queue_limit", 256))
    rx_submit_budget = str(data.get("wifi_rx_submit_budget", 128))
    rx_max_frame_len = str(data.get("wifi_rx_max_frame_len", 2304))
    rx_use_meta_header = "1" if data.get("wifi_rx_use_meta_header", False) else "0"
    rx_meta_len = str(data.get("wifi_rx_meta_len", 4))
    rx_meta_len_off = str(data.get("wifi_rx_meta_len_offset", 0))
    rx_sync_enable = "1" if data.get("wifi_rx_sync_enable", False) else "0"
    rx_sync_off = str(data.get("wifi_rx_sync_offset", 0))
    rx_sync_val = str(data.get("wifi_rx_sync_value", 0xAA))
    tx_retry_max = str(data.get("wifi_tx_retry_max", 3))
    tx_retry_delay_us = str(data.get("wifi_tx_retry_delay_us", 200))
    tx_queue_limit = str(data.get("wifi_tx_queue_limit", 512))
    tx_queue_wake_threshold = str(data.get("wifi_tx_queue_wake_threshold", 128))
    tx_reinit_stall_th = str(data.get("wifi_tx_reinit_stall_threshold", 3))
    tx_reinit_cooldown_ms = str(data.get("wifi_tx_reinit_cooldown_ms", 5000))
    fw_fallback = data.get("wifi_fw_fallback_names", [fw_probe])
    bt_patch_table = data.get("bt_patch_table_fallback_names", [])
    bt_patch = data.get("bt_patch_fallback_names", [])
    bt_patch_ext = data.get("bt_patch_ext_fallback_names", [])
    bt_adid = data.get("bt_adid_fallback_names", [])

    def to_c_lines(names: list[str]) -> str:
        return "\n".join(f'            "{name}",' for name in names)

    fw_fallback_c = to_c_lines(fw_fallback)
    bt_patch_table_c = to_c_lines(bt_patch_table)
    bt_patch_c = to_c_lines(bt_patch)
    bt_patch_ext_c = to_c_lines(bt_patch_ext)
    bt_adid_c = to_c_lines(bt_adid)
    return {
        "drivers/net/wireless/aicsemi/Kconfig": dedent(
            """\
            # GENERATED FILE - DO NOT EDIT MANUALLY
            # Generated by: generators/generate_aic8800_upstream.py
            config WLAN_VENDOR_AICSEMI
            \tbool "AICsemi devices"
            \tdefault y
            \thelp
            \t  This option enables support for wireless devices from AICsemi.

            if WLAN_VENDOR_AICSEMI

            source "drivers/net/wireless/aicsemi/aic8800/Kconfig"

            endif
            """
        ),
        "drivers/net/wireless/aicsemi/Makefile": dedent(
            """\
            # GENERATED FILE - DO NOT EDIT MANUALLY
            # Generated by: generators/generate_aic8800_upstream.py
            obj-$(CONFIG_AIC8800_CORE) += aic8800/
            """
        ),
        "drivers/net/wireless/aicsemi/aic8800/Kconfig": dedent(
            """\
            # GENERATED FILE - DO NOT EDIT MANUALLY
            # Generated by: generators/generate_aic8800_upstream.py
            config AIC8800_CORE
            \ttristate "AIC8800 core WiFi support"
            \tdepends on CFG80211 && MAC80211
            \thelp
            \t  Core support for AICsemi AIC8800 wireless devices.
            \t  Transport backends (such as SDIO) are introduced in follow-up patches.

            config AIC8800_SDIO
            \ttristate "AIC8800 SDIO transport"
            \tdepends on MMC
            \tdepends on AIC8800_CORE
            \thelp
            \t  SDIO transport backend for AIC8800 WiFi devices.
            """
        ),
        "drivers/net/wireless/aicsemi/aic8800/Makefile": dedent(
            """\
            # GENERATED FILE - DO NOT EDIT MANUALLY
            # Generated by: generators/generate_aic8800_upstream.py
            obj-$(CONFIG_AIC8800_CORE) += aic8800_core.o
            aic8800_core-y := core_main.o core_fw.o bt_fw.o cfg80211_core.o netdev_core.o

            obj-$(CONFIG_AIC8800_SDIO) += aic8800_sdio.o
            aic8800_sdio-y := sdio_probe.o sdio_io.o
            """
        ),
        "drivers/net/wireless/aicsemi/aic8800/core_types.h": dedent(
            """\
            /* SPDX-License-Identifier: GPL-2.0-only */
            /* GENERATED FILE - DO NOT EDIT MANUALLY */
            /* Generated by: generators/generate_aic8800_upstream.py */

            #ifndef AIC8800_CORE_TYPES_H
            #define AIC8800_CORE_TYPES_H

            #include <linux/device.h>
            #include <linux/firmware.h>
            #include <linux/if_ether.h>
            #include <linux/types.h>

            struct wiphy;
            struct net_device;
            struct sk_buff;
            struct aic8800_core;

            struct aic8800_fw_hooks {
            \tint (*pre_load)(struct aic8800_core *core, const char *name);
            \tvoid (*post_load)(struct aic8800_core *core, const char *name, int ret);
            \tint (*pre_unload)(struct aic8800_core *core);
            \tvoid (*post_unload)(struct aic8800_core *core, int ret);
            \tint (*pre_start)(struct aic8800_core *core, const char *name);
            \tvoid (*post_start)(struct aic8800_core *core, const char *name, int ret);
            };

            typedef int (*aic8800_tx_frame_t)(struct aic8800_core *core,
            \t\t\t\t      const u8 *data, size_t len);
            typedef int (*aic8800_rx_submit_t)(struct aic8800_core *core,
            \t\t\t\t       struct sk_buff *skb);

            struct aic8800_core {
            \tstruct device *dev;
            \tconst char *fw_name;
            \tconst struct firmware *fw_data;
            \tstruct wiphy *wiphy;
            \tstruct net_device *ndev;
            \tvoid *bus_priv;
            \tconst struct aic8800_fw_hooks *fw_hooks;
            \tchar fw_override[128];
            \tchar fw_loaded[128];
            \taic8800_tx_frame_t tx_frame;
            \taic8800_rx_submit_t rx_submit;
            \tu64 irq_count;
            \tu64 rx_batches;
            \tu64 rx_frames;
            \tu64 rx_empty;
            \tu64 rx_malformed;
            \tu64 rx_resync;
            \tu64 rx_errors;
            \tu64 rx_submit_runs;
            \tu64 rx_q_high_water;
            \tu64 tx_frames;
            \tu64 tx_retries;
            \tu64 tx_errors;
            \tu64 tx_q_full;
            \tu64 rx_drop_queue_full;
            \tu64 rx_drop_malformed;
            \tu64 tx_drop_queue_full;
            \tu64 tx_stall_events;
            \tu64 tx_recoveries;
            \tu64 tx_reinit_events;
            \tbool link_up;
            \tu8 bssid[ETH_ALEN];
            };

            int aic8800_core_register(struct aic8800_core *core);
            void aic8800_core_unregister(struct aic8800_core *core);
            int aic8800_core_request_firmware(struct aic8800_core *core);
            int aic8800_core_release_firmware(struct aic8800_core *core);
            int aic8800_core_set_fw_override(struct aic8800_core *core, const char *name);
            void aic8800_core_clear_fw_override(struct aic8800_core *core);
            const char *aic8800_core_get_fw_active_name(struct aic8800_core *core);
            void aic8800_core_set_fw_hooks(struct aic8800_core *core,
            \t\t\t\t  const struct aic8800_fw_hooks *hooks);

            #endif
            """
        ),
        "drivers/net/wireless/aicsemi/aic8800/cfg80211_core.h": dedent(
            """\
            /* SPDX-License-Identifier: GPL-2.0-only */
            /* GENERATED FILE - DO NOT EDIT MANUALLY */
            /* Generated by: generators/generate_aic8800_upstream.py */

            #ifndef AIC8800_CFG80211_CORE_H
            #define AIC8800_CFG80211_CORE_H

            #include "core_types.h"

            int aic8800_cfg80211_register(struct aic8800_core *core);
            void aic8800_cfg80211_unregister(struct aic8800_core *core);

            #endif
            """
        ),
        "drivers/net/wireless/aicsemi/aic8800/netdev_core.h": dedent(
            """\
            /* SPDX-License-Identifier: GPL-2.0-only */
            /* GENERATED FILE - DO NOT EDIT MANUALLY */
            /* Generated by: generators/generate_aic8800_upstream.py */

            #ifndef AIC8800_NETDEV_CORE_H
            #define AIC8800_NETDEV_CORE_H

            #include "core_types.h"

            int aic8800_netdev_register(struct aic8800_core *core);
            void aic8800_netdev_unregister(struct aic8800_core *core);

            #endif
            """
        ),
        "drivers/net/wireless/aicsemi/aic8800/core_main.c": dedent(
            """\
            // SPDX-License-Identifier: GPL-2.0-only
            // GENERATED FILE - DO NOT EDIT MANUALLY
            // Generated by: generators/generate_aic8800_upstream.py

            #include <linux/errno.h>
            #include <linux/module.h>
            #include <linux/string.h>
            #include "core_types.h"
            #include "cfg80211_core.h"
            #include "netdev_core.h"

            int aic8800_core_register(struct aic8800_core *core)
            {
            \tint ret;

            \tif (!core || !core->dev)
            \t\treturn -EINVAL;

            \tcore->wiphy = NULL;
            \tcore->ndev = NULL;
            \tcore->fw_data = NULL;
            \tcore->fw_hooks = NULL;
            \tcore->fw_override[0] = '\\0';
            \tcore->fw_loaded[0] = '\\0';
            \tcore->bus_priv = NULL;
            \tcore->tx_frame = NULL;
            \tcore->rx_submit = NULL;
            \tcore->irq_count = 0;
            \tcore->rx_batches = 0;
            \tcore->rx_frames = 0;
            \tcore->rx_empty = 0;
            \tcore->rx_malformed = 0;
            \tcore->rx_resync = 0;
            \tcore->rx_errors = 0;
            \tcore->rx_submit_runs = 0;
            \tcore->rx_q_high_water = 0;
            \tcore->tx_frames = 0;
            \tcore->tx_retries = 0;
            \tcore->tx_errors = 0;
            \tcore->tx_q_full = 0;
            \tcore->rx_drop_queue_full = 0;
            \tcore->rx_drop_malformed = 0;
            \tcore->tx_drop_queue_full = 0;
            \tcore->tx_stall_events = 0;
            \tcore->tx_recoveries = 0;
            \tcore->tx_reinit_events = 0;
            \tcore->link_up = false;
            \tmemset(core->bssid, 0, sizeof(core->bssid));

            \tret = aic8800_cfg80211_register(core);
            \tif (ret)
            \t\treturn ret;

            \tret = aic8800_netdev_register(core);
            \tif (ret)
            \t\tgoto err_cfg;

            \treturn 0;

            err_cfg:
            \taic8800_cfg80211_unregister(core);
            \treturn ret;
            }

            void aic8800_core_unregister(struct aic8800_core *core)
            {
            \tif (!core)
            \t\treturn;

            \taic8800_netdev_unregister(core);
            \taic8800_cfg80211_unregister(core);
            \tif (core->dev)
            \t\tdev_info(core->dev,
            \t\t	"aic8800 io summary: irq=%llu rx_batches=%llu rx_frames=%llu rx_empty=%llu rx_malformed=%llu rx_resync=%llu rx_err=%llu rx_submit_runs=%llu rx_q_hwm=%llu rx_drop_qfull=%llu rx_drop_malformed=%llu tx_frames=%llu tx_retries=%llu tx_q_full=%llu tx_drop_qfull=%llu tx_stall=%llu tx_recoveries=%llu tx_reinit=%llu tx_err=%llu\\n",
            \t\t	(unsigned long long)core->irq_count,
            \t\t	(unsigned long long)core->rx_batches,
            \t\t	(unsigned long long)core->rx_frames,
            \t\t	(unsigned long long)core->rx_empty,
            \t\t	(unsigned long long)core->rx_malformed,
            \t\t	(unsigned long long)core->rx_resync,
            \t\t	(unsigned long long)core->rx_errors,
            \t\t	(unsigned long long)core->rx_submit_runs,
            \t\t	(unsigned long long)core->rx_q_high_water,
            \t\t	(unsigned long long)core->rx_drop_queue_full,
            \t\t	(unsigned long long)core->rx_drop_malformed,
            \t\t	(unsigned long long)core->tx_frames,
            \t\t	(unsigned long long)core->tx_retries,
            \t\t	(unsigned long long)core->tx_q_full,
            \t\t	(unsigned long long)core->tx_drop_queue_full,
            \t\t	(unsigned long long)core->tx_stall_events,
            \t\t	(unsigned long long)core->tx_recoveries,
            \t\t	(unsigned long long)core->tx_reinit_events,
            \t\t	(unsigned long long)core->tx_errors);
            \tif (core->fw_data) {
            \t\trelease_firmware(core->fw_data);
            \t\tcore->fw_data = NULL;
            \t\tcore->fw_loaded[0] = '\\0';
            \t}
            }

            EXPORT_SYMBOL_GPL(aic8800_core_register);
            EXPORT_SYMBOL_GPL(aic8800_core_unregister);
            MODULE_LICENSE("GPL");
            MODULE_DESCRIPTION("AIC8800 core WiFi support");
            """
        ),
        "drivers/net/wireless/aicsemi/aic8800/core_fw.c": dedent(
            """\
            // SPDX-License-Identifier: GPL-2.0-only
            // GENERATED FILE - DO NOT EDIT MANUALLY
            // Generated by: generators/generate_aic8800_upstream.py

            #include <linux/errno.h>
            #include <linux/firmware.h>
            #include <linux/module.h>
            #include <linux/string.h>
            #include "core_types.h"

            static const char * const aic8800_fw_fallbacks[] = {
            __FW_FALLBACKS__
            };

            static const char *aic8800_core_fw_name(struct aic8800_core *core)
            {
            \tif (!core)
            \t\treturn NULL;

            \tif (core->fw_override[0])
            \t\treturn core->fw_override;

            \treturn core->fw_name;
            }

            int aic8800_core_release_firmware(struct aic8800_core *core)
            {
            \tint ret = 0;

            \tif (!core)
            \t\treturn -EINVAL;

            \tif (core->fw_hooks && core->fw_hooks->pre_unload) {
            \t\tret = core->fw_hooks->pre_unload(core);
            \t\tif (ret)
            \t\t\treturn ret;
            \t}

            \tif (core->fw_data) {
            \t\trelease_firmware(core->fw_data);
            \t\tcore->fw_data = NULL;
            \t}
            \tcore->fw_loaded[0] = '\\0';

            \tif (core->fw_hooks && core->fw_hooks->post_unload)
            \t\tcore->fw_hooks->post_unload(core, 0);

            \treturn 0;
            }

            int aic8800_core_set_fw_override(struct aic8800_core *core, const char *name)
            {
            \tif (!core || !name || !name[0])
            \t\treturn -EINVAL;

            \tstrscpy(core->fw_override, name, sizeof(core->fw_override));
            \treturn 0;
            }

            void aic8800_core_clear_fw_override(struct aic8800_core *core)
            {
            \tif (!core)
            \t\treturn;

            \tcore->fw_override[0] = '\\0';
            }

            const char *aic8800_core_get_fw_active_name(struct aic8800_core *core)
            {
            \treturn aic8800_core_fw_name(core);
            }

            void aic8800_core_set_fw_hooks(struct aic8800_core *core,
            \t\t\t\t const struct aic8800_fw_hooks *hooks)
            {
            \tif (!core)
            \t\treturn;

            \tcore->fw_hooks = hooks;
            }

            int aic8800_core_request_firmware(struct aic8800_core *core)
            {
            \tconst struct firmware *fw;
            \tconst char *req_name;
            \tint ret;
            \tint i;

            \tif (!core || !core->dev)
            \t\treturn -EINVAL;

            \treq_name = aic8800_core_fw_name(core);
            \tif (!req_name)
            \t\treturn -EINVAL;

            \tret = aic8800_core_release_firmware(core);
            \tif (ret)
            \t\treturn ret;

            \tif (core->fw_hooks && core->fw_hooks->pre_load) {
            \t\tret = core->fw_hooks->pre_load(core, req_name);
            \t\tif (ret)
            \t\t\treturn ret;
            \t}

            \tret = request_firmware(&fw, req_name, core->dev);
            \tif (!ret) {
            \t\tcore->fw_data = fw;
            \t\tstrscpy(core->fw_loaded, req_name, sizeof(core->fw_loaded));
            \t\tif (core->fw_hooks && core->fw_hooks->post_load)
            \t\t\tcore->fw_hooks->post_load(core, req_name, 0);
            \t\treturn 0;
            \t}

            \tfor (i = 0; i < ARRAY_SIZE(aic8800_fw_fallbacks); i++) {
            \t\tif (!strcmp(req_name, aic8800_fw_fallbacks[i]))
            \t\t\tcontinue;

            \t\tret = request_firmware(&fw, aic8800_fw_fallbacks[i], core->dev);
            \t\tif (!ret) {
            \t\t\tcore->fw_data = fw;
            \t\t\tstrscpy(core->fw_loaded, aic8800_fw_fallbacks[i],
            \t\t\t\tsizeof(core->fw_loaded));
            \t\t\tif (core->fw_hooks && core->fw_hooks->post_load)
            \t\t\t\tcore->fw_hooks->post_load(core, aic8800_fw_fallbacks[i], 0);
            \t\t\treturn 0;
            \t\t}
            \t}

            \tif (core->fw_hooks && core->fw_hooks->post_load)
            \t\tcore->fw_hooks->post_load(core, req_name, ret);

            \treturn ret;
            }

            EXPORT_SYMBOL_GPL(aic8800_core_request_firmware);
            EXPORT_SYMBOL_GPL(aic8800_core_release_firmware);
            EXPORT_SYMBOL_GPL(aic8800_core_set_fw_override);
            EXPORT_SYMBOL_GPL(aic8800_core_clear_fw_override);
            EXPORT_SYMBOL_GPL(aic8800_core_get_fw_active_name);
            EXPORT_SYMBOL_GPL(aic8800_core_set_fw_hooks);
            """
        ).replace("__FW_FALLBACKS__", fw_fallback_c),
        "drivers/net/wireless/aicsemi/aic8800/bt_fw.h": dedent(
            """\
            /* SPDX-License-Identifier: GPL-2.0-only */
            /* GENERATED FILE - DO NOT EDIT MANUALLY */
            /* Generated by: generators/generate_aic8800_upstream.py */

            #ifndef AIC8800_BT_FW_H
            #define AIC8800_BT_FW_H

            #include <linux/device.h>

            int aic8800_bt_request_patch_table(struct device *dev, const char *preferred);
            int aic8800_bt_request_patch_blob(struct device *dev, const char *preferred);
            int aic8800_bt_request_patch_ext_blob(struct device *dev, const char *preferred);
            int aic8800_bt_request_adid_blob(struct device *dev, const char *preferred);

            #endif
            """
        ),
        "drivers/net/wireless/aicsemi/aic8800/bt_fw.c": dedent(
            """\
            // SPDX-License-Identifier: GPL-2.0-only
            // GENERATED FILE - DO NOT EDIT MANUALLY
            // Generated by: generators/generate_aic8800_upstream.py

            #include <linux/errno.h>
            #include <linux/firmware.h>
            #include <linux/module.h>
            #include <linux/string.h>
            #include "bt_fw.h"

            static const char * const aic8800_bt_patch_table_fallbacks[] = {
            __BT_PATCH_TABLE_FALLBACKS__
            };

            static const char * const aic8800_bt_patch_fallbacks[] = {
            __BT_PATCH_FALLBACKS__
            };

            static const char * const aic8800_bt_patch_ext_fallbacks[] = {
            __BT_PATCH_EXT_FALLBACKS__
            };

            static const char * const aic8800_bt_adid_fallbacks[] = {
            __BT_ADID_FALLBACKS__
            };

            static int aic8800_request_with_fallbacks(struct device *dev,
            \t\t\t\t\tconst char *preferred,
            \t\t\t\t\tconst char * const *fallbacks,
            \t\t\t\t\tsize_t fallback_count)
            {
            \tconst struct firmware *fw;
            \tint ret;
            \tsize_t i;

            \tif (!dev || !preferred)
            \t\treturn -EINVAL;

            \tret = request_firmware(&fw, preferred, dev);
            \tif (!ret) {
            \t\trelease_firmware(fw);
            \t\treturn 0;
            \t}

            \tfor (i = 0; i < fallback_count; i++) {
            \t\tif (!fallbacks[i] || !strcmp(preferred, fallbacks[i]))
            \t\t\tcontinue;

            \t\tret = request_firmware(&fw, fallbacks[i], dev);
            \t\tif (!ret) {
            \t\t\trelease_firmware(fw);
            \t\t\treturn 0;
            \t\t}
            \t}

            \treturn ret;
            }

            int aic8800_bt_request_patch_table(struct device *dev, const char *preferred)
            {
            \treturn aic8800_request_with_fallbacks(
            \t\tdev,
            \t\tpreferred,
            \t\taic8800_bt_patch_table_fallbacks,
            \t\tARRAY_SIZE(aic8800_bt_patch_table_fallbacks)
            \t);
            }

            int aic8800_bt_request_patch_blob(struct device *dev, const char *preferred)
            {
            \treturn aic8800_request_with_fallbacks(
            \t\tdev,
            \t\tpreferred,
            \t\taic8800_bt_patch_fallbacks,
            \t\tARRAY_SIZE(aic8800_bt_patch_fallbacks)
            \t);
            }

            int aic8800_bt_request_adid_blob(struct device *dev, const char *preferred)
            {
            \treturn aic8800_request_with_fallbacks(
            \t\tdev,
            \t\tpreferred,
            \t\taic8800_bt_adid_fallbacks,
            \t\tARRAY_SIZE(aic8800_bt_adid_fallbacks)
            \t);
            }

            int aic8800_bt_request_patch_ext_blob(struct device *dev, const char *preferred)
            {
            \treturn aic8800_request_with_fallbacks(
            \t\tdev,
            \t\tpreferred,
            \t\taic8800_bt_patch_ext_fallbacks,
            \t\tARRAY_SIZE(aic8800_bt_patch_ext_fallbacks)
            \t);
            }

            EXPORT_SYMBOL_GPL(aic8800_bt_request_patch_table);
            EXPORT_SYMBOL_GPL(aic8800_bt_request_patch_blob);
            EXPORT_SYMBOL_GPL(aic8800_bt_request_patch_ext_blob);
            EXPORT_SYMBOL_GPL(aic8800_bt_request_adid_blob);
            """
        )
        .replace("__BT_PATCH_TABLE_FALLBACKS__", bt_patch_table_c)
        .replace("__BT_PATCH_FALLBACKS__", bt_patch_c)
        .replace("__BT_PATCH_EXT_FALLBACKS__", bt_patch_ext_c)
        .replace("__BT_ADID_FALLBACKS__", bt_adid_c),
        "drivers/net/wireless/aicsemi/aic8800/cfg80211_core.c": dedent(
            """\
            // SPDX-License-Identifier: GPL-2.0-only
            // GENERATED FILE - DO NOT EDIT MANUALLY
            // Generated by: generators/generate_aic8800_upstream.py

            #include <linux/bitops.h>
            #include <linux/etherdevice.h>
            #include <linux/errno.h>
            #include <linux/ieee80211.h>
            #include <linux/string.h>
            #include <net/cfg80211.h>
            #include "cfg80211_core.h"

            static struct aic8800_core *aic8800_core_from_wiphy(struct wiphy *wiphy)
            {
            \tif (!wiphy)
            \t\treturn NULL;

            \treturn *((struct aic8800_core **)wiphy_priv(wiphy));
            }

            static int aic8800_cfg80211_scan(struct wiphy *wiphy,
            \t\t\t\t    struct cfg80211_scan_request *request)
            {
            \tstruct cfg80211_scan_info info = {
            \t\t.aborted = false,
            \t};

            \t(void)wiphy;
            \tif (!request)
            \t\treturn -EINVAL;

            \tcfg80211_scan_done(request, &info);
            \treturn 0;
            }

            static int aic8800_cfg80211_connect(struct wiphy *wiphy,
            \t\t\t\t       struct net_device *dev,
            \t\t\t\t       struct cfg80211_connect_params *sme)
            {
            \tstruct aic8800_core *core = aic8800_core_from_wiphy(wiphy);

            \t(void)wiphy;

            \tif (!dev || !sme || !core)
            \t\treturn -EINVAL;

            \tif (sme->bssid)
            \t\tether_addr_copy(core->bssid, sme->bssid);
            \telse
            \t\teth_zero_addr(core->bssid);

            \tcore->link_up = true;

            \tcfg80211_connect_result(
            \t\tdev,
            \t\tcore->bssid,
            \t\tNULL,
            \t\t0,
            \t\tNULL,
            \t\t0,
            \t\tWLAN_STATUS_SUCCESS,
            \t\tGFP_KERNEL
            \t);
            \treturn 0;
            }

            static int aic8800_cfg80211_disconnect(struct wiphy *wiphy,
            \t\t\t\t\t  struct net_device *dev,
            \t\t\t\t\t  u16 reason_code)
            {
            \tstruct aic8800_core *core = aic8800_core_from_wiphy(wiphy);

            \t(void)wiphy;

            \tif (!dev || !core)
            \t\treturn -EINVAL;

            \tcore->link_up = false;
            \teth_zero_addr(core->bssid);

            \tcfg80211_disconnected(dev, reason_code, NULL, 0, true, GFP_KERNEL);
            \treturn 0;
            }

            static int aic8800_cfg80211_change_virtual_intf(struct wiphy *wiphy,
            \t\t\t\t\t\t     struct net_device *dev,
            \t\t\t\t\t\t     enum nl80211_iftype type,
            \t\t\t\t\t\t     struct vif_params *params)
            {
            \t(void)wiphy;
            \t(void)dev;
            \t(void)params;

            \tif (type == NL80211_IFTYPE_STATION)
            \t\treturn 0;

            \treturn -EOPNOTSUPP;
            }

            static const struct cfg80211_ops aic8800_cfg80211_ops = {
            \t.scan = aic8800_cfg80211_scan,
            \t.connect = aic8800_cfg80211_connect,
            \t.disconnect = aic8800_cfg80211_disconnect,
            \t.change_virtual_intf = aic8800_cfg80211_change_virtual_intf,
            };

            int aic8800_cfg80211_register(struct aic8800_core *core)
            {
            \tstruct wiphy *wiphy;
            \tint ret;

            \tif (!core || !core->dev)
            \t\treturn -EINVAL;

            \twiphy = wiphy_new(&aic8800_cfg80211_ops, sizeof(struct aic8800_core *));
            \tif (!wiphy)
            \t\treturn -ENOMEM;

            \t*((struct aic8800_core **)wiphy_priv(wiphy)) = core;

            \tset_wiphy_dev(wiphy, core->dev);
            \twiphy->max_scan_ssids = 1;
            \twiphy->interface_modes = BIT(NL80211_IFTYPE_STATION);
            \tstrscpy(wiphy->fw_version, "aic8800-draft", sizeof(wiphy->fw_version));

            \tret = wiphy_register(wiphy);
            \tif (ret) {
            \t\twiphy_free(wiphy);
            \t\treturn ret;
            \t}

            \tcore->wiphy = wiphy;
            \treturn 0;
            }

            void aic8800_cfg80211_unregister(struct aic8800_core *core)
            {
            \tif (!core || !core->wiphy)
            \t\treturn;

            \twiphy_unregister(core->wiphy);
            \twiphy_free(core->wiphy);
            \tcore->wiphy = NULL;
            }
            """
        ),
        "drivers/net/wireless/aicsemi/aic8800/netdev_core.c": dedent(
            """\
            // SPDX-License-Identifier: GPL-2.0-only
            // GENERATED FILE - DO NOT EDIT MANUALLY
            // Generated by: generators/generate_aic8800_upstream.py

            #include <linux/errno.h>
            #include <linux/etherdevice.h>
            #include <linux/netdevice.h>
            #include <net/cfg80211.h>
            #include "netdev_core.h"

            struct aic8800_vif {
            \tstruct wireless_dev wdev;
            \tstruct aic8800_core *core;
            };

            static int aic8800_ndo_open(struct net_device *ndev)
            {
            \tnetif_start_queue(ndev);
            \treturn 0;
            }

            static int aic8800_ndo_stop(struct net_device *ndev)
            {
            \tnetif_stop_queue(ndev);
            \treturn 0;
            }

            static netdev_tx_t aic8800_ndo_start_xmit(struct sk_buff *skb,
            \t\t\t\t      struct net_device *ndev)
            {
            \tstruct aic8800_vif *vif = netdev_priv(ndev);
            \tint ret;

            \tif (!vif || !vif->core || !vif->core->tx_frame) {
            \t\tndev->stats.tx_dropped++;
            \t\tdev_kfree_skb_any(skb);
            \t\treturn NETDEV_TX_OK;
            \t}

            \tret = vif->core->tx_frame(vif->core, skb->data, skb->len);
            \tif (ret == -ENOSPC) {
            \t\tvif->core->tx_drop_queue_full++;
            \t\tnetif_stop_queue(ndev);
            \t\treturn NETDEV_TX_BUSY;
            \t}

            \tif (ret) {
            \t\tndev->stats.tx_dropped++;
            \t\tdev_kfree_skb_any(skb);
            \t\treturn NETDEV_TX_OK;
            \t}

            \tndev->stats.tx_packets++;
            \tndev->stats.tx_bytes += skb->len;
            \tdev_kfree_skb_any(skb);
            \treturn NETDEV_TX_OK;
            }

            static const struct net_device_ops aic8800_netdev_ops = {
            \t.ndo_open = aic8800_ndo_open,
            \t.ndo_stop = aic8800_ndo_stop,
            \t.ndo_start_xmit = aic8800_ndo_start_xmit,
            \t.ndo_set_mac_address = eth_mac_addr,
            \t.ndo_validate_addr = eth_validate_addr,
            };

            int aic8800_netdev_register(struct aic8800_core *core)
            {
            \tstruct net_device *ndev;
            \tstruct aic8800_vif *vif;
            \tu8 mac_addr[ETH_ALEN];
            \tint ret;

            \tif (!core || !core->wiphy || !core->dev)
            \t\treturn -EINVAL;

            \tndev = alloc_etherdev(sizeof(*vif));
            \tif (!ndev)
            \t\treturn -ENOMEM;

            \tvif = netdev_priv(ndev);
            \tvif->core = core;
            \tvif->wdev.wiphy = core->wiphy;
            \tvif->wdev.netdev = ndev;
            \tvif->wdev.iftype = NL80211_IFTYPE_STATION;
            \tndev->ieee80211_ptr = &vif->wdev;
            \tndev->netdev_ops = &aic8800_netdev_ops;
            \tSET_NETDEV_DEV(ndev, core->dev);

            \tstrscpy(ndev->name, "wlan%d", IFNAMSIZ);
            \tret = eth_platform_get_mac_address(core->dev, mac_addr);
            \tif (!ret && is_valid_ether_addr(mac_addr))
            \t\teth_hw_addr_set(ndev, mac_addr);
            \telse
            \t\teth_hw_addr_random(ndev);

            \tret = cfg80211_register_netdevice(ndev);
            \tif (ret) {
            \t\tfree_netdev(ndev);
            \t\treturn ret;
            \t}

            \tcore->ndev = ndev;
            \treturn 0;
            }

            void aic8800_netdev_unregister(struct aic8800_core *core)
            {
            \tif (!core || !core->ndev)
            \t\treturn;

            \tcfg80211_unregister_netdevice(core->ndev);
            \tcore->ndev = NULL;
            }
            """
        ),
        "drivers/net/wireless/aicsemi/aic8800/sdio_io.h": dedent(
            """\
            /* SPDX-License-Identifier: GPL-2.0-only */
            /* GENERATED FILE - DO NOT EDIT MANUALLY */
            /* Generated by: generators/generate_aic8800_upstream.py */

            #ifndef AIC8800_SDIO_IO_H
            #define AIC8800_SDIO_IO_H

            #include <linux/mmc/sdio_func.h>
            #include "core_types.h"

            int aic8800_sdio_io_init(struct sdio_func *func);
            void aic8800_sdio_io_deinit(struct sdio_func *func);
            int aic8800_sdio_fw_download(struct sdio_func *func,
            \t\t\t     u32 addr, const u8 *data, size_t len);
            int aic8800_sdio_start_firmware(struct sdio_func *func, u32 entry);
            int aic8800_sdio_tx_write(struct sdio_func *func,
            \t\t\t const u8 *data, size_t len);
            int aic8800_sdio_tx_frame(struct aic8800_core *core,
            \t\t\t const u8 *data, size_t len);
            int aic8800_sdio_rx_drain(struct aic8800_core *core, int budget);
            u8  aic8800_crc8_ponl_107(const u8 *buf, size_t len);

            #endif
            """
        ),
        "drivers/net/wireless/aicsemi/aic8800/sdio_probe.c": dedent(
            """\
            // SPDX-License-Identifier: GPL-2.0-only
            // GENERATED FILE - DO NOT EDIT MANUALLY
            // Generated by: generators/generate_aic8800_upstream.py

            #include <linux/errno.h>
            #include <linux/delay.h>
            #include <linux/debugfs.h>
            #include <linux/etherdevice.h>
            #include <linux/fs.h>
            #include <linux/gpio/consumer.h>
            #include <linux/interrupt.h>
            #include <linux/jiffies.h>
            #include <linux/module.h>
            #include <linux/mutex.h>
            #include <linux/mmc/sdio_func.h>
            #include <linux/netdevice.h>
            #include <linux/of_irq.h>
            #include <linux/regulator/consumer.h>
            #include <linux/skbuff.h>
            #include <linux/slab.h>
            #include <linux/seq_file.h>
            #include <linux/string.h>
            #include <linux/sys_soc.h>
            #include <linux/uaccess.h>
            #include <linux/workqueue.h>
            #include "core_types.h"
            #include "sdio_io.h"

            struct aic8800_sdio {
            \tstruct aic8800_core core;
            \tstruct work_struct rx_work;
            \tstruct work_struct rx_submit_work;
            \tstruct work_struct tx_work;
            \tstruct delayed_work tx_watchdog_work;
            \tstruct sk_buff_head rxq;
            \tstruct sk_buff_head txq;
            \tstruct sk_buff *tx_skb;
            \tu64 tx_watch_last_frames;
            \tu32 tx_watch_stall_ticks;
            \tu32 tx_recover_fail_streak;
            \tunsigned long tx_reinit_cooldown_until;
            \tstruct mutex recovery_lock;
            \tbool tx_reinit_in_progress;
            \tstruct dentry *dbg_dir;
            \tstruct regulator *vddio;
            \tstruct gpio_desc *reset_gpio;
            \tint oob_irq;
            \tbool rx_stopping;
            \tbool tx_stopping;
            };

            static int aic8800_sdio_tx_recover(struct aic8800_sdio *sdio);
            static int aic8800_sdio_reinit_transport(struct aic8800_sdio *sdio,
            \t\t\t\t\t bool force);
            static int aic8800_sdio_power_on(struct aic8800_sdio *sdio);
            static void aic8800_sdio_power_off(struct aic8800_sdio *sdio);
            static int aic8800_sdio_fw_load(struct aic8800_sdio *sdio, bool reload);
            static int aic8800_sdio_fw_start(struct aic8800_sdio *sdio);
            static int aic8800_sdio_fw_load_and_start(struct aic8800_sdio *sdio,
            \t\t\t\t\t bool reload);
            static int aic8800_sdio_send_mem_write(struct sdio_func *func,
            \t\t\t\t  u32 addr, u32 value);
            static void aic8800_sdio_rx_purge(struct aic8800_sdio *sdio);
            static void aic8800_sdio_irq_handler(struct sdio_func *func);
            static irqreturn_t aic8800_sdio_oob_irq_thread(int irq, void *data);

            static const struct soc_device_attribute aic8800_sdio_soc_match[] = {
            \t{ .family = "Allwinner" },
            \t{ }
            };

            static int aic8800_sdio_dbg_stats_show(struct seq_file *m, void *v)
            {
            \tstruct aic8800_sdio *sdio = m->private;
            \tstruct aic8800_core *core = &sdio->core;
            \tunsigned long now;
            \tu32 cooldown_left_ms;
            \tbool reinit_in_progress;

            \tmutex_lock(&sdio->recovery_lock);
            \tnow = jiffies;
            \treinit_in_progress = sdio->tx_reinit_in_progress;
            \tif (time_before(now, sdio->tx_reinit_cooldown_until))
            \t\tcooldown_left_ms = jiffies_to_msecs(
            \t\t\tsdio->tx_reinit_cooldown_until - now);
            \telse
            \t\tcooldown_left_ms = 0;
            \tmutex_unlock(&sdio->recovery_lock);

            \tseq_printf(m, "irq_count=%llu\\n", (unsigned long long)core->irq_count);
            \tseq_printf(m, "rx_batches=%llu\\n", (unsigned long long)core->rx_batches);
            \tseq_printf(m, "rx_frames=%llu\\n", (unsigned long long)core->rx_frames);
            \tseq_printf(m, "rx_empty=%llu\\n", (unsigned long long)core->rx_empty);
            \tseq_printf(m, "rx_malformed=%llu\\n", (unsigned long long)core->rx_malformed);
            \tseq_printf(m, "rx_resync=%llu\\n", (unsigned long long)core->rx_resync);
            \tseq_printf(m, "rx_errors=%llu\\n", (unsigned long long)core->rx_errors);
            \tseq_printf(m, "rx_submit_runs=%llu\\n", (unsigned long long)core->rx_submit_runs);
            \tseq_printf(m, "rx_q_high_water=%llu\\n", (unsigned long long)core->rx_q_high_water);
            \tseq_printf(m, "rx_drop_queue_full=%llu\\n", (unsigned long long)core->rx_drop_queue_full);
            \tseq_printf(m, "rx_drop_malformed=%llu\\n", (unsigned long long)core->rx_drop_malformed);
            \tseq_printf(m, "tx_frames=%llu\\n", (unsigned long long)core->tx_frames);
            \tseq_printf(m, "tx_retries=%llu\\n", (unsigned long long)core->tx_retries);
            \tseq_printf(m, "tx_q_full=%llu\\n", (unsigned long long)core->tx_q_full);
            \tseq_printf(m, "tx_drop_queue_full=%llu\\n", (unsigned long long)core->tx_drop_queue_full);
            \tseq_printf(m, "tx_stall_events=%llu\\n", (unsigned long long)core->tx_stall_events);
            \tseq_printf(m, "tx_recoveries=%llu\\n", (unsigned long long)core->tx_recoveries);
            \tseq_printf(m, "tx_reinit_events=%llu\\n", (unsigned long long)core->tx_reinit_events);
            \tseq_printf(m, "tx_reinit_in_progress=%u\\n", reinit_in_progress ? 1 : 0);
            \tseq_printf(m, "tx_reinit_cooldown_ms_left=%u\\n", cooldown_left_ms);
            \tseq_printf(m, "tx_errors=%llu\\n", (unsigned long long)core->tx_errors);
            \tseq_printf(m, "rx_queue_len=%u\\n", skb_queue_len(&sdio->rxq));
            \tseq_printf(m, "tx_queue_len=%u\\n", skb_queue_len(&sdio->txq));
            \tseq_printf(m, "fw_active=%s\\n",
            \t\taic8800_core_get_fw_active_name(core) ?
            \t\taic8800_core_get_fw_active_name(core) : "<none>");
            \tseq_printf(m, "fw_loaded=%s\\n",
            \t\tcore->fw_loaded[0] ? core->fw_loaded : "<none>");
            \tseq_printf(m, "fw_loaded_size=%zu\\n",
            \t\tcore->fw_data ? core->fw_data->size : 0UL);

            \treturn 0;
            }

            static int aic8800_sdio_dbg_stats_open(struct inode *inode, struct file *file)
            {
            \treturn single_open(file, aic8800_sdio_dbg_stats_show, inode->i_private);
            }

            static const struct file_operations aic8800_sdio_dbg_stats_fops = {
            \t.owner = THIS_MODULE,
            \t.open = aic8800_sdio_dbg_stats_open,
            \t.read = seq_read,
            \t.llseek = seq_lseek,
            \t.release = single_release,
            };

            static ssize_t aic8800_sdio_dbg_control_write(struct file *file,
            \t\t\t\t\t const char __user *ubuf,
            \t\t\t\t\t size_t count,
            \t\t\t\t\t loff_t *ppos)
            {
            \tstruct aic8800_sdio *sdio = file->private_data;
            \tchar cmd[192];
            \tchar *arg;
            \tchar *nl;
            \tsize_t n = min_t(size_t, count, sizeof(cmd) - 1);
            \tint ret = 0;

            \tif (!sdio)
            \t\treturn -EINVAL;

            \tif (copy_from_user(cmd, ubuf, n))
            \t\treturn -EFAULT;
            \tcmd[n] = '\\0';
            \tnl = strpbrk(cmd, "\\r\\n");
            \tif (nl)
            \t\t*nl = '\\0';

            \targ = strchr(cmd, ' ');
            \tif (arg) {
            \t\t*arg = '\\0';
            \t\targ++;
            \t\twhile (*arg == ' ')
            \t\t\targ++;
            \t\tif (!*arg)
            \t\t\targ = NULL;
            \t}

            \tif (!strcmp(cmd, "tx_recover")) {
            \t\tret = aic8800_sdio_tx_recover(sdio);
            \t} else if (!strcmp(cmd, "reinit")) {
            \t\tret = aic8800_sdio_reinit_transport(sdio, true);
            \t} else if (!strcmp(cmd, "rx_purge")) {
            \t\taic8800_sdio_rx_purge(sdio);
            \t} else if (!strcmp(cmd, "rx_kick")) {
            \t\tschedule_work(&sdio->rx_work);
            \t} else if (!strcmp(cmd, "fw_set")) {
            \t\tif (!arg)
            \t\t\treturn -EINVAL;
            \t\tret = aic8800_core_set_fw_override(&sdio->core, arg);
            \t} else if (!strcmp(cmd, "fw_clear")) {
            \t\taic8800_core_clear_fw_override(&sdio->core);
            \t} else if (!strcmp(cmd, "fw_load")) {
            \t\tret = aic8800_sdio_fw_load(sdio, false);
            \t} else if (!strcmp(cmd, "fw_reload")) {
            \t\tret = aic8800_sdio_fw_load(sdio, true);
            \t} else if (!strcmp(cmd, "fw_unload")) {
            \t\tret = aic8800_core_release_firmware(&sdio->core);
            \t} else if (!strcmp(cmd, "fw_start")) {
            \t\tret = aic8800_sdio_fw_start(sdio);
            \t} else if (!strcmp(cmd, "fw_cycle")) {
            \t\tret = aic8800_sdio_fw_load_and_start(sdio, true);
            \t} else {
            \t\treturn -EINVAL;
            \t}

            \tif (ret < 0)
            \t\treturn ret;

            \treturn count;
            }

            static const struct file_operations aic8800_sdio_dbg_control_fops = {
            \t.owner = THIS_MODULE,
            \t.open = simple_open,
            \t.write = aic8800_sdio_dbg_control_write,
            \t.llseek = noop_llseek,
            };

            static void aic8800_sdio_debugfs_init(struct aic8800_sdio *sdio)
            {
            \tsdio->dbg_dir = debugfs_create_dir("aic8800_sdio", NULL);
            \tif (IS_ERR_OR_NULL(sdio->dbg_dir))
            \t\treturn;

            \tdebugfs_create_file("stats", 0444, sdio->dbg_dir, sdio,
            \t\t\t    &aic8800_sdio_dbg_stats_fops);
            \tdebugfs_create_file("control", 0200, sdio->dbg_dir, sdio,
            \t\t\t    &aic8800_sdio_dbg_control_fops);
            }

            static void aic8800_sdio_debugfs_deinit(struct aic8800_sdio *sdio)
            {
            \tdebugfs_remove_recursive(sdio->dbg_dir);
            \tsdio->dbg_dir = NULL;
            }

            static int aic8800_sdio_power_on(struct aic8800_sdio *sdio)
            {
            \tint ret;

            \tif (!sdio)
            \t\treturn -EINVAL;

            \tif (sdio->vddio) {
            \t\tret = regulator_enable(sdio->vddio);
            \t\tif (ret)
            \t\t\treturn ret;
            \t}

            \tif (sdio->reset_gpio) {
            \t\tgpiod_set_value_cansleep(sdio->reset_gpio, 1);
            \t\tmsleep(20);
            \t\tgpiod_set_value_cansleep(sdio->reset_gpio, 0);
            \t\tmsleep(20);
            \t}

            \treturn 0;
            }

            static void aic8800_sdio_power_off(struct aic8800_sdio *sdio)
            {
            \tif (!sdio)
            \t\treturn;

            \tif (sdio->reset_gpio)
            \t\tgpiod_set_value_cansleep(sdio->reset_gpio, 1);

            \tif (sdio->vddio)
            \t\tregulator_disable(sdio->vddio);
            }

            static irqreturn_t aic8800_sdio_oob_irq_thread(int irq, void *data)
            {
            \tstruct aic8800_sdio *sdio = data;

            \tif (!sdio)
            \t\treturn IRQ_NONE;

            \tsdio->core.irq_count++;
            \tif (!sdio->rx_stopping)
            \t\tschedule_work(&sdio->rx_work);

            \treturn IRQ_HANDLED;
            }

            static int aic8800_sdio_fw_load(struct aic8800_sdio *sdio, bool reload)
            {
            \tif (!sdio)
            \t\treturn -EINVAL;

            \tif (!reload && sdio->core.fw_data)
            \t\treturn 0;

            \treturn aic8800_core_request_firmware(&sdio->core);
            }

            static int aic8800_sdio_send_mem_write(struct sdio_func *func,
            \t\t\t\t  u32 addr, u32 value)
            {
            \tu8 msg[24] = {0};
            \tint ret;

            \tmsg[0] = 20 & 0xFF;
            \tmsg[1] = 0;
            \tmsg[2] = 0x11;
            \tmsg[3] = aic8800_crc8_ponl_107(msg, 3);
            \tmsg[8]  = 0x02;
            \tmsg[9]  = 0x04;
            \tmsg[10] = 1;
            \tmsg[12] = 100;
            \tmsg[14] = 8;
            \tmsg[16] = addr & 0xFF;
            \tmsg[17] = (addr >> 8) & 0xFF;
            \tmsg[18] = (addr >> 16) & 0xFF;
            \tmsg[19] = (addr >> 24) & 0xFF;
            \tmsg[20] = value & 0xFF;
            \tmsg[21] = (value >> 8) & 0xFF;
            \tmsg[22] = (value >> 16) & 0xFF;
            \tmsg[23] = (value >> 24) & 0xFF;

            \t{
            \t\tu8 *buf = kzalloc(512, GFP_KERNEL);
            \t\tif (!buf) return -ENOMEM;
            \t\tmemcpy(buf, msg, sizeof(msg));
            \t\tsdio_claim_host(func);
            \t\tret = sdio_writesb(func, 0x10, buf, 512);
            \t\tsdio_release_host(func);
            \t\tkfree(buf);
            \t}

            \treturn ret;
            }

            static int aic8800_sdio_fw_start(struct aic8800_sdio *sdio)
            {
            \tstruct sdio_func *func;
            \tconst char *fw_name;
            \tint ret;

            \tif (!sdio)
            \t\treturn -EINVAL;

            \tif (!sdio->core.fw_data)
            \t\treturn -ENOENT;

            \tif (!sdio->core.dev)
            \t\treturn -ENODEV;

            \tfunc = dev_to_sdio_func(sdio->core.dev);
            \tif (!func)
            \t\treturn -ENODEV;

            \tfw_name = sdio->core.fw_loaded[0] ?
            \t\t  sdio->core.fw_loaded : aic8800_core_get_fw_active_name(&sdio->core);

            \tif (sdio->core.fw_hooks && sdio->core.fw_hooks->pre_start) {
            \t\tret = sdio->core.fw_hooks->pre_start(&sdio->core, fw_name);
            \t\tif (ret)
            \t\t\treturn ret;
            \t}

            \tret = aic8800_sdio_fw_download(
            \t\tfunc, __FW_ADDR__,
            \t\tsdio->core.fw_data->data, sdio->core.fw_data->size);
            \tif (ret)
            \t\tgoto out_start;

            \t/* Pre-start system config: GPIO/OOB register setup
            \t * required before bootrom handoff for 8800D80 */
            \tret = aic8800_sdio_send_mem_write(func, 0x40504084, 0x00000006);
            \tif (ret) goto out_start;
            \tret = aic8800_sdio_send_mem_write(func, 0x40500040, 0x00000000);
            \tif (ret) goto out_start;
            \tret = aic8800_sdio_send_mem_write(func, 0x40100030, 0x00000001);
            \tif (ret) goto out_start;
            \tret = aic8800_sdio_send_mem_write(func, 0x40241020, 0x00000001);
            \tif (ret) goto out_start;
            \tret = aic8800_sdio_send_mem_write(func, 0x40240030, 0x00000004);
            \tif (ret) goto out_start;
            \tret = aic8800_sdio_send_mem_write(func, 0x40240020, 0x03020700);
            \tif (ret) goto out_start;

            \tret = aic8800_sdio_start_firmware(func, __FW_ADDR__);

            out_start:
            \tif (sdio->core.fw_hooks && sdio->core.fw_hooks->post_start)
            \t\tsdio->core.fw_hooks->post_start(&sdio->core, fw_name, ret);

            \treturn ret;
            }

            static int aic8800_sdio_fw_load_and_start(struct aic8800_sdio *sdio,
            \t\t\t\t\t bool reload)
            {
            \tint ret;

            \tret = aic8800_sdio_fw_load(sdio, reload);
            \tif (ret)
            \t\treturn ret;

            \treturn aic8800_sdio_fw_start(sdio);
            }

            static void aic8800_sdio_rx_submit_work(struct work_struct *work)
            {
            \tstruct aic8800_sdio *sdio =
            \t\tcontainer_of(work, struct aic8800_sdio, rx_submit_work);
            \tint done = 0;

            \tsdio->core.rx_submit_runs++;

            \twhile (done < __RX_SUBMIT_BUDGET__) {
            \t\tstruct sk_buff *skb = skb_dequeue(&sdio->rxq);

            \t\tif (!skb)
            \t\t\tbreak;

            \t\tskb->dev = sdio->core.ndev;
            \t\tskb->protocol = eth_type_trans(skb, sdio->core.ndev);
            \t\tskb->ip_summed = CHECKSUM_NONE;

            \t\tsdio->core.ndev->stats.rx_packets++;
            \t\tsdio->core.ndev->stats.rx_bytes += skb->len;
            \t\tnetif_rx(skb);
            \t\tdone++;
            \t}

            \tif (!sdio->rx_stopping && !skb_queue_empty(&sdio->rxq))
            \t\tschedule_work(&sdio->rx_submit_work);
            }

            static int aic8800_sdio_rx_submit(struct aic8800_core *core,
            \t\t\t      struct sk_buff *skb)
            {
            \tstruct aic8800_sdio *sdio;
            \tu32 qlen;

            \tif (!core || !core->bus_priv || !skb)
            \t\treturn -EINVAL;

            \tsdio = core->bus_priv;
            \tif (sdio->rx_stopping)
            \t\treturn -ESHUTDOWN;

            \tqlen = skb_queue_len(&sdio->rxq);
            \tif (qlen >= __RX_QUEUE_LIMIT__) {
            \t\tcore->rx_drop_queue_full++;
            \t\treturn -ENOSPC;
            \t}

            \tif ((qlen + 1) > core->rx_q_high_water)
            \t\tcore->rx_q_high_water = qlen + 1;

            \tskb_queue_tail(&sdio->rxq, skb);
            \tschedule_work(&sdio->rx_submit_work);
            \treturn 0;
            }

            static void aic8800_sdio_tx_watchdog_work(struct work_struct *work)
            {
            \tstruct aic8800_sdio *sdio =
            \t\tcontainer_of(to_delayed_work(work),
            \t\t\t     struct aic8800_sdio, tx_watchdog_work);
            \tu32 qlen;

            \tif (sdio->tx_stopping)
            \t\treturn;

            \tqlen = skb_queue_len(&sdio->txq) + (sdio->tx_skb ? 1 : 0);
            \tif (qlen && sdio->tx_watch_last_frames == sdio->core.tx_frames) {
            \t\tsdio->tx_watch_stall_ticks++;
            \t\tif (sdio->tx_watch_stall_ticks >= 4) {
            \t\tint ret;

            \t\tsdio->core.tx_stall_events++;
            \t\tsdio->tx_watch_stall_ticks = 0;
            \t\tdev_warn_ratelimited(sdio->core.dev,
            \t\t\t"SDIO TX stall suspected, qlen=%u\\n", qlen);
            \t\tif (!sdio->tx_stopping) {
            \t\t\tsdio->tx_recover_fail_streak++;
            \t\t\tif (sdio->tx_recover_fail_streak >= __TX_REINIT_STALL_TH__) {
            \t\t\t\tret = aic8800_sdio_reinit_transport(sdio, false);
            \t\t\t\tif (ret == 0)
            \t\t\t\t\tsdio->tx_recover_fail_streak = 0;
            \t\t\t\telse if (ret != -EAGAIN && ret != -EALREADY)
            \t\t\t\t\tsdio->core.tx_errors++;
            \t\t\t} else if (aic8800_sdio_tx_recover(sdio) != 0) {
            \t\t\t\tsdio->core.tx_errors++;
            \t\t\t}
            \t\t}
            \t\t}
            \t} else {
            \t\tsdio->tx_watch_stall_ticks = 0;
            \t\tsdio->tx_recover_fail_streak = 0;
            \t}

            \tsdio->tx_watch_last_frames = sdio->core.tx_frames;
            \tschedule_delayed_work(&sdio->tx_watchdog_work,
            \t\t\t      msecs_to_jiffies(500));
            }

            static void aic8800_sdio_tx_work(struct work_struct *work)
            {
            \tstruct aic8800_sdio *sdio =
            \t\tcontainer_of(work, struct aic8800_sdio, tx_work);
            \tstruct sdio_func *func;

            \tif (!sdio->core.dev)
            \t\treturn;

            \tfunc = dev_to_sdio_func(sdio->core.dev);
            \tif (!func)
            \t\treturn;

            \twhile (!sdio->tx_stopping) {
            \t\tint ret;
            \t\tint tries = 0;

            \t\tif (!sdio->tx_skb) {
            \t\t\tsdio->tx_skb = skb_dequeue(&sdio->txq);
            \t\t\tif (!sdio->tx_skb)
            \t\t\t\tbreak;
            \t\t}

            \t\t/* Flow control: read available TX buffers */
            \t\t{
            \t\t\tu8 fc_reg;
            \t\t\tint fc_retries = 0;

            \t\t\tsdio_claim_host(func);
            \t\t\tret = sdio_readsb(func, &fc_reg, 0x03, 1);
            \t\t\tsdio_release_host(func);
            \t\t\tif (ret)
            \t\t\t\tbreak;

            \t\t\twhile (fc_reg <= 2 && fc_retries < 50 &&
            \t\t\t       !sdio->tx_stopping) {
            \t\t\t\tif (fc_retries < 30)
            \t\t\t\t\tudelay(200);
            \t\t\t\telse if (fc_retries < 40)
            \t\t\t\t\tmsleep(2);
            \t\t\t\telse
            \t\t\t\t\tmsleep(10);
            \t\t\t\tfc_retries++;
            \t\t\t\tsdio_claim_host(func);
            \t\t\t\tret = sdio_readsb(func, &fc_reg, 0x03, 1);
            \t\t\t\tsdio_release_host(func);
            \t\t\t\tif (ret)
            \t\t\t\t\tbreak;
            \t\t\t}
            \t\t}

            \t\tdo {
            \t\t\tret = aic8800_sdio_tx_write(func, sdio->tx_skb->data,
            \t\t\t\t\t\t      sdio->tx_skb->len);
            \t\t\tif (!ret)
            \t\t\t\tbreak;

            \t\t\ttries++;
            \t\t\tsdio->core.tx_retries++;
            \t\t\tif (tries <= __TX_RETRY_MAX__)
            \t\t\t\tusleep_range(__TX_RETRY_DELAY_US__,
            \t\t\t\t\t     __TX_RETRY_DELAY_US__ + 200);
            \t\t} while (tries <= __TX_RETRY_MAX__ && !sdio->tx_stopping);

            \t\tif (ret)
            \t\t\tsdio->core.tx_errors++;
            \t\telse {
            \t\t\tsdio->core.tx_frames++;
            \t\t\tsdio->tx_recover_fail_streak = 0;
            \t\t}

            \t\tif (sdio->core.ndev &&
            \t\t    netif_queue_stopped(sdio->core.ndev) &&
            \t\t    skb_queue_len(&sdio->txq) <= __TX_QUEUE_WAKE_TH__) {
            \t\t\tnetif_wake_queue(sdio->core.ndev);
            \t\t}

            \t\tdev_kfree_skb_any(sdio->tx_skb);
            \t\tsdio->tx_skb = NULL;

            \t\tif (ret)
            \t\t\tbreak;
            \t}
            }

            int aic8800_sdio_tx_frame(struct aic8800_core *core,
            \t\t\t const u8 *data, size_t len)
            {
            \tstruct aic8800_sdio *sdio;
            \tstruct sk_buff *skb;

            \tif (!core || !core->bus_priv || !data || !len)
            \t\treturn -EINVAL;

            \tsdio = core->bus_priv;
            \tif (sdio->tx_stopping)
            \t\treturn -ESHUTDOWN;

            \tif (skb_queue_len(&sdio->txq) >= __TX_QUEUE_LIMIT__) {
            \t\tcore->tx_q_full++;
            \t\treturn -ENOSPC;
            \t}

            \tskb = alloc_skb(len, GFP_ATOMIC);
            \tif (!skb)
            \t\treturn -ENOMEM;

            \tskb_put_data(skb, data, len);
            \tskb_queue_tail(&sdio->txq, skb);
            \tschedule_work(&sdio->tx_work);
            \treturn 0;
            }

            static void aic8800_sdio_tx_flush(struct aic8800_sdio *sdio)
            {
            \tsdio->tx_stopping = true;
            \tcancel_delayed_work_sync(&sdio->tx_watchdog_work);
            \tcancel_work_sync(&sdio->tx_work);

            \tif (sdio->tx_skb) {
            \t\tdev_kfree_skb_any(sdio->tx_skb);
            \t\tsdio->tx_skb = NULL;
            \t}

            \tskb_queue_purge(&sdio->txq);
            }

            static int aic8800_sdio_tx_recover(struct aic8800_sdio *sdio)
            {
            \tif (!sdio || sdio->tx_stopping)
            \t\treturn -EINVAL;

            \tcancel_work_sync(&sdio->tx_work);

            \tif (sdio->tx_skb) {
            \t\tdev_kfree_skb_any(sdio->tx_skb);
            \t\tsdio->tx_skb = NULL;
            \t}

            \tskb_queue_purge(&sdio->txq);
            \tsdio->core.tx_recoveries++;
            \tif (sdio->core.ndev && netif_queue_stopped(sdio->core.ndev))
            \t\tnetif_wake_queue(sdio->core.ndev);

            \tschedule_work(&sdio->tx_work);
            \treturn 0;
            }

            static int aic8800_sdio_reinit_transport(struct aic8800_sdio *sdio,
            \t\t\t\t\t bool force)
            {
            \tstruct sdio_func *func;
            \tint ret = 0;
            \tu32 preserved_txq;
            \tunsigned long now;

            \tif (!sdio || sdio->tx_stopping || sdio->rx_stopping)
            \t\treturn -EINVAL;

            \tif (!sdio->core.dev)
            \t\treturn -ENODEV;

            \tfunc = dev_to_sdio_func(sdio->core.dev);
            \tif (!func)
            \t\treturn -ENODEV;

            \tmutex_lock(&sdio->recovery_lock);
            \tif (sdio->tx_reinit_in_progress) {
            \t\tret = -EALREADY;
            \t\tgoto out_unlock;
            \t}

            \tnow = jiffies;
            \tif (!force && time_before(now, sdio->tx_reinit_cooldown_until)) {
            \t\tret = -EAGAIN;
            \t\tgoto out_unlock;
            \t}

            \tsdio->tx_reinit_in_progress = true;
            \tsdio->tx_reinit_cooldown_until =
            \t\tnow + msecs_to_jiffies(__TX_REINIT_COOLDOWN_MS__);
            \tmutex_unlock(&sdio->recovery_lock);

            \tdev_warn_ratelimited(sdio->core.dev,
            \t\t"SDIO transport reinit requested\\n");

            \tcancel_work_sync(&sdio->tx_work);
            \tcancel_work_sync(&sdio->rx_work);
            \tcancel_work_sync(&sdio->rx_submit_work);

            \tif (sdio->tx_skb) {
            \t\tskb_queue_head(&sdio->txq, sdio->tx_skb);
            \t\tsdio->tx_skb = NULL;
            \t}
            \tpreserved_txq = skb_queue_len(&sdio->txq);
            \tif (preserved_txq)
            \t\tdev_info_ratelimited(sdio->core.dev,
            \t\t\t"preserving %u queued TX frames across reinit\\n",
            \t\t\tpreserved_txq);
            \tskb_queue_purge(&sdio->rxq);

            \tsdio_claim_host(func);
            \tret = sdio_release_irq(func);
            \tsdio_release_host(func);
            \tif (ret)
            \t\tdev_warn_ratelimited(sdio->core.dev,
            \t\t\t"sdio_release_irq during reinit returned %d\\n", ret);

            \taic8800_sdio_io_deinit(func);
            \tret = aic8800_sdio_io_init(func);
            \tif (ret)
            \t\tgoto out_finish;

            \tsdio_claim_host(func);
            \tret = sdio_claim_irq(func, aic8800_sdio_irq_handler);
            \tsdio_release_host(func);
            \tif (ret) {
            \t\taic8800_sdio_io_deinit(func);
            \t\tgoto out_finish;
            \t}

            \tsdio->core.tx_reinit_events++;
            \tsdio->tx_watch_stall_ticks = 0;
            \tsdio->tx_watch_last_frames = sdio->core.tx_frames;
            \tsdio->tx_recover_fail_streak = 0;
            \tif (sdio->core.ndev && netif_queue_stopped(sdio->core.ndev))
            \t\tnetif_wake_queue(sdio->core.ndev);

            \tschedule_work(&sdio->rx_work);
            \tschedule_work(&sdio->tx_work);
            \tret = 0;

            out_finish:
            \tmutex_lock(&sdio->recovery_lock);
            \tsdio->tx_reinit_in_progress = false;
            out_unlock:
            \tmutex_unlock(&sdio->recovery_lock);
            \treturn ret;
            }

            static void aic8800_sdio_rx_work(struct work_struct *work)
            {
            \tstruct aic8800_sdio *sdio =
            \t\tcontainer_of(work, struct aic8800_sdio, rx_work);
            \tint rounds = 0;

            \twhile (!sdio->rx_stopping && rounds < __RX_WORK_MAX_BATCHES__) {
            \t\tint ret;

            \t\tret = aic8800_sdio_rx_drain(&sdio->core, __RX_BUDGET__);
            \t\tif (ret == -ENODATA)
            \t\t\tbreak;

            \t\tif (ret < 0) {
            \t\t\tsdio->core.rx_errors++;
            \t\t\tdev_warn_ratelimited(sdio->core.dev,
            \t\t\t\t"SDIO RX drain failed: %d\\n", ret);
            \t\t\tbreak;
            \t\t}

            \t\trounds++;
            \t}
            }

            static void aic8800_sdio_rx_flush(struct aic8800_sdio *sdio)
            {
            \tsdio->rx_stopping = true;
            \tcancel_work_sync(&sdio->rx_work);
            \tcancel_work_sync(&sdio->rx_submit_work);
            \tskb_queue_purge(&sdio->rxq);
            }

            static void aic8800_sdio_rx_purge(struct aic8800_sdio *sdio)
            {
            \tif (!sdio || sdio->rx_stopping)
            \t\treturn;

            \tcancel_work_sync(&sdio->rx_work);
            \tcancel_work_sync(&sdio->rx_submit_work);
            \tskb_queue_purge(&sdio->rxq);
            \tschedule_work(&sdio->rx_work);
            }

            static void aic8800_sdio_irq_handler(struct sdio_func *func)
            {
            \tstruct aic8800_sdio *sdio = sdio_get_drvdata(func);
            \tu8 pending;

            \tif (!sdio)
            \t\treturn;

            \tsdio->core.irq_count++;

            \t/* Clear pending interrupt bit 0 in INTR_PENDING_REG_V3 (0x01) */
            \tsdio_claim_host(func);
            \tif (sdio_readsb(func, &pending, 0x01, 1) == 0) {
            \t\tpending &= ~0x01;
            \t\tsdio_writesb(func, 0x01, &pending, 1);
            \t}
            \tsdio_release_host(func);

            \tif (!sdio->rx_stopping)
            \t\tschedule_work(&sdio->rx_work);
            }

            static int aic8800_sdio_probe(struct sdio_func *func,
                                          const struct sdio_device_id *id)
            {
            \tstruct aic8800_sdio *sdio;
            \tconst struct soc_device_attribute *soc;
            \tbool bootloader_mode;
            \tint ret;

            \tif (!func)
            \t\treturn -EINVAL;

            \tbootloader_mode = (func->device == 0x0182);

            \tsdio = devm_kzalloc(&func->dev, sizeof(*sdio), GFP_KERNEL);
            \tif (!sdio)
            \t\treturn -ENOMEM;

            \tsdio->core.dev = &func->dev;
            \tsdio->core.fw_name = "__FW__";
            \tsdio->oob_irq = -ENXIO;
            \tINIT_WORK(&sdio->rx_work, aic8800_sdio_rx_work);
            \tINIT_WORK(&sdio->rx_submit_work, aic8800_sdio_rx_submit_work);
            \tINIT_WORK(&sdio->tx_work, aic8800_sdio_tx_work);
            \tINIT_DELAYED_WORK(&sdio->tx_watchdog_work,
            \t\t\t       aic8800_sdio_tx_watchdog_work);
            \tskb_queue_head_init(&sdio->rxq);
            \tskb_queue_head_init(&sdio->txq);
            \tsdio->tx_skb = NULL;
            \tsdio->tx_watch_last_frames = 0;
            \tsdio->tx_watch_stall_ticks = 0;
            \tsdio->tx_recover_fail_streak = 0;
            \tsdio->tx_reinit_cooldown_until = 0;
            \tsdio->tx_reinit_in_progress = false;
            \tmutex_init(&sdio->recovery_lock);
            \tsdio->rx_stopping = false;
            \tsdio->tx_stopping = false;

            \tsoc = soc_device_match(aic8800_sdio_soc_match);
            \tif (!soc)
            \t\tdev_warn_once(&func->dev,
            \t\t\t"SoC match unavailable, using generic AIC8800 path\\n");

            \tsdio->vddio = devm_regulator_get_optional(&func->dev, "vddio");
            \tif (IS_ERR(sdio->vddio)) {
            \t\tif (PTR_ERR(sdio->vddio) == -ENODEV)
            \t\t\tsdio->vddio = NULL;
            \t\telse
            \t\t\treturn PTR_ERR(sdio->vddio);
            \t}

            \tsdio->reset_gpio = devm_gpiod_get_optional(&func->dev, "reset",
            \t\t\t\t\t       GPIOD_OUT_LOW);
            \tif (IS_ERR(sdio->reset_gpio))
            \t\treturn PTR_ERR(sdio->reset_gpio);

            \tret = aic8800_sdio_power_on(sdio);
            \tif (ret)
            \t\treturn ret;

            \tif (bootloader_mode) {
            \t\tdev_info(&func->dev,
            \t\t\t"bootloader mode, loading firmware\\n");
            \t\tret = aic8800_sdio_io_init(func);
            \t\tif (ret)
            \t\t\tgoto err_power;
            \t\tret = aic8800_sdio_fw_load_and_start(sdio, false);
            \t\taic8800_sdio_io_deinit(func);
            \t\tif (ret) {
            \t\t\tdev_err(&func->dev,
            \t\t\t\t"firmware start failed: %d\\n", ret);
            \t\t\tgoto err_power;
            \t\t}
            \t\tdev_info(&func->dev,
            \t\t\t"firmware started, waiting for re-enumeration\\n");
            \t\treturn 0;
            \t}

            \t/* Normal mode: firmware already running, full setup */
            \tdev_info(&func->dev, "normal mode probe\\n");

            \tret = aic8800_core_register(&sdio->core);
            \tif (ret)
            \t\tgoto err_power;

            \tsdio->core.bus_priv = sdio;
            \tsdio->core.tx_frame = aic8800_sdio_tx_frame;
            \tsdio->core.rx_submit = aic8800_sdio_rx_submit;
            \tschedule_delayed_work(&sdio->tx_watchdog_work,
            \t\t\t      msecs_to_jiffies(500));
            \taic8800_sdio_debugfs_init(sdio);

            \tret = aic8800_sdio_io_init(func);
            \tif (ret)
            \t\tgoto err_unregister;

            \tsdio_claim_host(func);
            \tret = sdio_claim_irq(func, aic8800_sdio_irq_handler);
            \tsdio_release_host(func);
            \tif (ret)
            \t\tgoto err_io;

            \t/* Enable master interrupt on CCCR func0 for 8800D80 */
            \tsdio_claim_host(func);
            \tsdio_f0_writeb(func, 0x07, 0x04, &ret);
            \tsdio_release_host(func);
            \tif (ret)
            \t\tdev_warn(&func->dev,
            \t\t\t"CCCR int enable returned %d\\n", ret);

            \tsdio->oob_irq = of_irq_get(func->dev.of_node, 0);
            \tif (sdio->oob_irq > 0) {
            \t\tunsigned long irq_flags = irq_get_trigger_type(sdio->oob_irq);

            \t\tret = devm_request_threaded_irq(&func->dev, sdio->oob_irq,
            \t\t\t\t\tNULL, aic8800_sdio_oob_irq_thread,
            \t\t\t\t\tirq_flags | IRQF_ONESHOT,
            \t\t\t\t\t"aic8800-oob", sdio);
            \t\tif (ret) {
            \t\t\tdev_warn(&func->dev,
            \t\t\t\t"failed to request OOB IRQ %d: %d\\n",
            \t\t\t\tsdio->oob_irq, ret);
            \t\t\tsdio->oob_irq = -ENXIO;
            \t\t}
            \t}

            \tsdio_set_drvdata(func, sdio);
            \treturn 0;

            err_io:
            \taic8800_sdio_debugfs_deinit(sdio);
            \taic8800_sdio_rx_flush(sdio);
            \taic8800_sdio_tx_flush(sdio);
            \taic8800_sdio_io_deinit(func);
            err_unregister:
            \taic8800_core_unregister(&sdio->core);
            err_power:
            \taic8800_sdio_power_off(sdio);
            \treturn ret;
            }

            static void aic8800_sdio_remove(struct sdio_func *func)
            {
            \tstruct aic8800_sdio *sdio = sdio_get_drvdata(func);

            \tif (!sdio)
            \t\treturn;

            \t/* Bootloader mode: no core/netdev/irq were set up */
            \tif (sdio->core.ndev || sdio->core.wiphy) {
            \t\tsdio_claim_host(func);
            \t\tsdio_release_irq(func);
            \t\tsdio_release_host(func);
            \t\taic8800_sdio_debugfs_deinit(sdio);
            \t\taic8800_sdio_rx_flush(sdio);
            \t\taic8800_sdio_tx_flush(sdio);
            \t\taic8800_sdio_io_deinit(func);
            \t\tsdio->core.bus_priv = NULL;
            \t\tsdio->core.tx_frame = NULL;
            \t\tsdio->core.rx_submit = NULL;
            \t\taic8800_core_unregister(&sdio->core);
            \t}

            \taic8800_sdio_power_off(sdio);
            }

            static const struct sdio_device_id aic8800_sdio_ids[] = {
            \t{ SDIO_DEVICE(__VENDOR__, __DEVICE__) },
            \t{ SDIO_DEVICE(__VENDOR__, __NORMAL_PID__) },
            \t{ }
            };
            MODULE_DEVICE_TABLE(sdio, aic8800_sdio_ids);

            static struct sdio_driver aic8800_sdio_driver = {
            \t.name = "aic8800_sdio",
            \t.id_table = aic8800_sdio_ids,
            \t.probe = aic8800_sdio_probe,
            \t.remove = aic8800_sdio_remove,
            };
            module_sdio_driver(aic8800_sdio_driver);

            MODULE_LICENSE("GPL");
            MODULE_DESCRIPTION("AIC8800 SDIO transport");
            """
        )
        .replace("__VENDOR__", vendor)
        .replace("__DEVICE__", device)
        .replace("__NORMAL_PID__", "0x0082")
        .replace("__FW__", fw_probe)
        .replace("__FW_ADDR__", fw_dl_addr)
        .replace("__RX_BUDGET__", rx_budget)
        .replace("__RX_WORK_MAX_BATCHES__", rx_work_max_batches)
        .replace("__RX_QUEUE_LIMIT__", rx_queue_limit)
        .replace("__RX_SUBMIT_BUDGET__", rx_submit_budget)
        .replace("__TX_QUEUE_LIMIT__", tx_queue_limit)
        .replace("__TX_QUEUE_WAKE_TH__", tx_queue_wake_threshold)
        .replace("__TX_RETRY_MAX__", tx_retry_max)
        .replace("__TX_REINIT_STALL_TH__", tx_reinit_stall_th)
        .replace("__TX_REINIT_COOLDOWN_MS__", tx_reinit_cooldown_ms)
        .replace("__TX_RETRY_DELAY_US__", tx_retry_delay_us),
        "drivers/net/wireless/aicsemi/aic8800/sdio_io.c": dedent(
            """\
            // SPDX-License-Identifier: GPL-2.0-only
            // GENERATED FILE - DO NOT EDIT MANUALLY
            // Generated by: generators/generate_aic8800_upstream.py

            #include <linux/errno.h>
            #include <linux/delay.h>
            #include <linux/etherdevice.h>
            #include <linux/if_ether.h>
            #include <linux/kernel.h>
            #include <linux/mmc/card.h>
            #include <linux/mmc/sdio.h>
            #include <linux/mmc/sdio_func.h>
            #include <linux/netdevice.h>
            #include <linux/skbuff.h>
            #include <linux/slab.h>
            #include <linux/string.h>
            #include <linux/types.h>
            #include "sdio_io.h"

            u8 aic8800_crc8_ponl_107(const u8 *buf, size_t len);

            u8 aic8800_crc8_ponl_107(const u8 *buf, size_t len)
            {
            \t/* Vendor bit-serial CRC-8 with polynomial X8+X2+X+1 (0x107)
            \t * MSB-first within each byte, double-XOR data bit into poly */
            \tu8 i;
            \tu8 crc = 0;

            \tif (!len)
            \t\treturn 0;

            \twhile (len--) {
            \t\tfor (i = 0x80; i > 0; i /= 2) {
            \t\t\tif (crc & 0x80) {
            \t\t\t\tcrc *= 2;
            \t\t\t\tcrc ^= 0x07;
            \t\t\t} else {
            \t\t\t\tcrc *= 2;
            \t\t\t}
            \t\t\tif (*buf & i)
            \t\t\t\tcrc ^= 0x07;
            \t\t}
            \t\tbuf++;
            \t}

            \treturn crc;
            }

            int aic8800_sdio_io_init(struct sdio_func *func)
            {
            \tu8 val;
            \tint ret;

            \tif (!func)
            \t\treturn -EINVAL;

            \tsdio_claim_host(func);

            \tfunc->card->quirks |= MMC_QUIRK_LENIENT_FN0;

            \tret = sdio_set_block_size(func, 512);
            \tif (ret) {
            \t\tsdio_release_host(func);
            \t\treturn ret;
            \t}

            \tret = sdio_enable_func(func);
            \tif (ret) {
            \t\tsdio_release_host(func);
            \t\treturn ret;
            \t}

            \tsdio_release_host(func);

            \tsdio_claim_host(func);
            \tret = sdio_writesb(func, __INTR_ENABLE_REG__, "\x07", 1);
            \tsdio_release_host(func);
            \tif (ret)
            \t\treturn ret;

            \tsdio_claim_host(func);
            \tret = sdio_writesb(func, __BYTEMODE_ENABLE_REG__, "\x01", 1);
            \tsdio_release_host(func);
            \tif (ret)
            \t\treturn ret;

            \tsdio_claim_host(func);
            \tret = sdio_writesb(func, __WAKEUP_REG__, "\x11", 1);
            \tsdio_release_host(func);
            \tif (ret)
            \t\treturn ret;

            \tmsleep(10);

            \tsdio_claim_host(func);
            \tret = sdio_readsb(func, &val, __SLEEP_REG__, 1);
            \tsdio_release_host(func);
            \tif (ret)
            \t\treturn ret;

            \tif (!(val & 0x10)) {
            \t\tdev_err(&func->dev,
            \t\t\t"chip not ready after init (sleep_reg=0x%02x)\\n", val);
            \t\treturn -ETIMEDOUT;
            \t}

            \treturn 0;
            }

            void aic8800_sdio_io_deinit(struct sdio_func *func)
            {
            \tif (!func)
            \t\treturn;

            \tsdio_claim_host(func);
            \tsdio_disable_func(func);
            \tsdio_release_host(func);
            }

            int aic8800_sdio_fw_download(struct sdio_func *func,
            \t\t\t     u32 addr, const u8 *data, size_t len)
            {
            \tint ret;

            \tif (!func || !data || !len)
            \t\treturn -EINVAL;

            \tsdio_claim_host(func);
            \tret = sdio_memcpy_toio(func, addr, (void *)data, len);
            \tsdio_release_host(func);

            \tif (ret)
            \t\tdev_err(&func->dev,
            \t\t\t "firmware download to 0x%08x failed: %d\\n",
            \t\t\t addr, ret);

            \treturn ret;
            }

            int aic8800_sdio_start_firmware(struct sdio_func *func, u32 entry)
            {
            \t/* IPC message: 16-byte transport header + 8-byte lmac_msg + 8-byte param
            \t * DBG_START_APP_REQ = 0x040D. bootaddr + boottype (both u32 LE) */
            \tu8  msg[24] = {0};
            \tu16 payload_len = 20;
            \tu16 msg_id = 0x040D;
            \tint ret;

            \tif (!func || !entry)
            \t\treturn -EINVAL;

            \tmsg[0] = payload_len & 0xFF;
            \tmsg[1] = ((payload_len >> 8) & 0x0F);
            \tmsg[2] = 0x11;
            \tmsg[3] = aic8800_crc8_ponl_107(msg, 3);
            \t/* msg[4..7] already 0 (dummy word) */
            \tmsg[8]  = msg_id & 0xFF;
            \tmsg[9]  = (msg_id >> 8) & 0xFF;
            \tmsg[10] = 1;  /* dest = TASK_DBG */
            \tmsg[12] = 100; /* src = DRV_TASK_ID */
            \tmsg[14] = 8;                /* param_len LE */
            \tmsg[16] = entry & 0xFF;     /* bootaddr u32 LE */
            \tmsg[17] = (entry >> 8) & 0xFF;
            \tmsg[18] = (entry >> 16) & 0xFF;
            \tmsg[19] = (entry >> 24) & 0xFF;
            \tmsg[20] = 1;                /* boottype u32 LE = HOST_START_APP_AUTO */
            \t/* msg[21..23] already 0 */

            \tsdio_claim_host(func);
            \t{
            \t\tu8 *buf = kzalloc(512, GFP_KERNEL);
            \t\tif (!buf) { sdio_release_host(func); return -ENOMEM; }
            \t\tmemcpy(buf, msg, sizeof(msg));
            \t\tret = sdio_writesb(func, __TX_PORT__, buf, 512);
            \t\tkfree(buf);
            \t}
            \tsdio_release_host(func);
            \tif (ret) {
            \t\tdev_err(&func->dev,
            \t\t\t"START_APP IPC failed: %d\\n", ret);
            \t\treturn ret;
            \t}

            \treturn 0;
            }

            int aic8800_sdio_tx_write(struct sdio_func *func,
            \t\t\t const u8 *data, size_t len)
            {
            \t/* TX frame: 4-byte header + payload, padded to 512 blocks
            \t * [0-1] LE16 len (total payload bytes)
            \t * [2]   type = 0x01 (data)
            \t * [3]   CRC8 of bytes 0-2 (8800D80)
            \t */
            \tu8 hdr[4];
            \tu16 plen = (u16)len;
            \tsize_t block_len;
            \tint ret;

            \tif (!func || !data || !len)
            \t\treturn -EINVAL;

            \thdr[0] = plen & 0xFF;
            \thdr[1] = (plen >> 8) & 0xFF;
            \thdr[2] = 0x01;
            \thdr[3] = aic8800_crc8_ponl_107(hdr, 3);

            \tblock_len = roundup(sizeof(hdr) + len, 512);

            \t{
            \t\tu8 *buf = kzalloc(block_len, GFP_KERNEL);

            \t\tif (!buf)
            \t\t\treturn -ENOMEM;

            \t\tmemcpy(buf, hdr, sizeof(hdr));
            \t\tmemcpy(buf + sizeof(hdr), data, len);

            \t\tsdio_claim_host(func);
            \t\tret = sdio_writesb(func, __TX_PORT__, buf, block_len);
            \t\tsdio_release_host(func);
            \t\tkfree(buf);
            \t}

            \tif (ret)
            \t\tdev_err(&func->dev, "TX write failed: %d\\n", ret);

            \treturn ret;
            }

            int aic8800_sdio_rx_drain(struct aic8800_core *core, int budget)
            {
            \tstruct sdio_func *func;
            \tint frames = 0;
            \tint ret = 0;

            \tif (!core || !core->dev || !core->ndev)
            \t\treturn -EINVAL;

            \tif (budget <= 0)
            \t\tbudget = 1;

            \tfunc = dev_to_sdio_func(core->dev);
            \tif (!func)
            \t\treturn -ENODEV;

            \twhile (frames < budget) {
            \t\tstruct sk_buff *skb;
            \t\tu8 int_status;
            \t\tu32 data_len;
            \t\tbool byte_mode;

            \t\t/* Read V3 MISC_INT_STATUS_REG to determine data size */
            \t\tsdio_claim_host(func);
            \t\tret = sdio_readsb(func, &int_status, __INT_STATUS_REG__, 1);
            \t\tsdio_release_host(func);
            \t\tif (ret) {
            \t\t\tif (ret == -ENOMEDIUM)
            \t\t\t\tbreak;
            \t\t\treturn ret;
            \t\t}

            \t\tbyte_mode = (int_status >= 120);
            \t\tif (byte_mode) {
            \t\t\tu8 byte_len;

            \t\t\tsdio_claim_host(func);
            \t\t\tret = sdio_readsb(func, &byte_len,
            \t\t\t\t\t   __RX_LEN_PORT__, 1);
            \t\t\tsdio_release_host(func);
            \t\t\tif (ret)
            \t\t\t\treturn ret;

            \t\t\tdata_len = byte_len * 4;
            \t\t} else {
            \t\t\tdata_len = (int_status & 0x7F) * 512;
            \t\t}

            \t\tif (!data_len || data_len > __RX_MAX_LEN__)
            \t\t\tbreak;

            \t\tskb = netdev_alloc_skb(core->ndev, data_len + NET_IP_ALIGN);
            \t\tif (!skb)
            \t\t\treturn -ENOMEM;

            \t\tskb_reserve(skb, NET_IP_ALIGN);
            \t\tsdio_claim_host(func);
            \t\tret = sdio_readsb(func, skb_put(skb, data_len),
            \t\t\t\t   __RX_DATA_PORT__, data_len);
            \t\tsdio_release_host(func);
            \t\tif (ret) {
            \t\t\tdev_kfree_skb_any(skb);
            \t\t\treturn ret;
            \t\t}

            \t\tif (skb->len < ETH_HLEN) {
            \t\t\tcore->rx_malformed++;
            \t\t\tcore->rx_drop_malformed++;
            \t\t\tcore->ndev->stats.rx_dropped++;
            \t\t\tdev_kfree_skb_any(skb);
            \t\t\tframes++;
            \t\t\tcontinue;
            \t\t}

            \t\tif (core->rx_submit) {
            \t\t\tret = core->rx_submit(core, skb);
            \t\t\tif (ret) {
            \t\t\t\tif (ret == -ENOSPC)
            \t\t\t\t\tcore->rx_drop_queue_full++;
            \t\t\t\tcore->ndev->stats.rx_dropped++;
            \t\t\t\tcore->rx_errors++;
            \t\t\t\tdev_kfree_skb_any(skb);
            \t\t\t}
            \t\t} else {
            \t\t\tcore->ndev->stats.rx_dropped++;
            \t\t\tcore->rx_errors++;
            \t\t\tdev_kfree_skb_any(skb);
            \t\t}
            \t\tframes++;
            \t}

            \tif (!frames) {
            \t\tcore->rx_empty++;
            \t\treturn -ENODATA;
            \t}

            \tcore->rx_batches++;
            \tcore->rx_frames += frames;

            \treturn frames;
            }
            """
        )
        .replace("__TX_PORT__", tx_port_addr)
        .replace("__RX_LEN_PORT__", rx_len_port_addr)
        .replace("__RX_DATA_PORT__", rx_data_port_addr)
        .replace("__INT_STATUS_REG__", "0x04")
        .replace("__INTR_ENABLE_REG__", "0x00")
        .replace("__BYTEMODE_ENABLE_REG__", "0x07")
        .replace("__WAKEUP_REG__", "0x02")
        .replace("__SLEEP_REG__", "0x01")
        .replace("__RX_MAX_LEN__", rx_max_frame_len)
        .replace("__RX_USE_META__", rx_use_meta_header)
        .replace("__RX_META_LEN__", rx_meta_len)
        .replace("__RX_META_LEN_OFF__", rx_meta_len_off)
        .replace("__RX_SYNC_ENABLE__", rx_sync_enable)
        .replace("__RX_SYNC_OFF__", rx_sync_off)
        .replace("__RX_SYNC_VAL__", rx_sync_val),
        "drivers/bluetooth/hci_aic8800.c": dedent(
            """\
            // SPDX-License-Identifier: GPL-2.0-only
            // GENERATED FILE - DO NOT EDIT MANUALLY
            // Generated by: generators/generate_aic8800_upstream.py

            #include <linux/errno.h>
            #include <linux/module.h>
            #include <linux/of.h>
            #include <linux/serdev.h>
            #include <linux/skbuff.h>
            #include <linux/unaligned.h>
            #include <linux/workqueue.h>
            #include <net/bluetooth/bluetooth.h>
            #include <net/bluetooth/hci_core.h>

            enum aic_h4_len_type {
            \tAIC_H4_NO_LEN,
            \tAIC_H4_LEN_U8,
            \tAIC_H4_LEN_U16,
            };

            struct aic_bt_data {
            \tstruct hci_dev *hdev;
            \tstruct serdev_device *serdev;
            \tstruct work_struct tx_work;
            \tstruct sk_buff_head txq;
            \tstruct sk_buff *tx_skb;
            \tstruct sk_buff *rx_skb;
            \tu16 rx_expect;
            \tu8 rx_hdr_len;
            \tu8 rx_len_off;
            \tu8 rx_type;
            \tenum aic_h4_len_type rx_len_type;
            };

            static void aic_bt_update_tx_stats(struct hci_dev *hdev, u8 pkt_type)
            {
            \tswitch (pkt_type) {
            \tcase HCI_COMMAND_PKT:
            \t\thdev->stat.cmd_tx++;
            \t\tbreak;
            \tcase HCI_ACLDATA_PKT:
            \t\thdev->stat.acl_tx++;
            \t\tbreak;
            \tcase HCI_SCODATA_PKT:
            \t\thdev->stat.sco_tx++;
            \t\tbreak;
            \tdefault:
            \t\tbreak;
            \t}
            }

            static void aic_bt_tx_work(struct work_struct *work)
            {
            \tstruct aic_bt_data *data = container_of(work, struct aic_bt_data, tx_work);
            \tstruct hci_dev *hdev = data->hdev;

            \twhile (1) {
            \t\tint written;
            \t\tu8 pkt_type;

            \t\tif (!data->tx_skb) {
            \t\t\tdata->tx_skb = skb_dequeue(&data->txq);
            \t\t\tif (!data->tx_skb)
            \t\t\t\tbreak;
            \t\t}

            \t\tpkt_type = hci_skb_pkt_type(data->tx_skb);
            \t\twritten = serdev_device_write_buf(data->serdev,
            \t\t\t\t\t\t data->tx_skb->data,
            \t\t\t\t\t\t data->tx_skb->len);
            \t\tif (written <= 0)
            \t\t\tbreak;

            \t\thdev->stat.byte_tx += written;
            \t\tskb_pull(data->tx_skb, written);
            \t\tif (data->tx_skb->len)
            \t\t\tbreak;

            \t\taic_bt_update_tx_stats(hdev, pkt_type);
            \t\tkfree_skb(data->tx_skb);
            \t\tdata->tx_skb = NULL;
            \t}
            }

            static void aic_bt_reset_rx_state(struct aic_bt_data *data)
            {
            \tdata->rx_expect = 0;
            \tdata->rx_hdr_len = 0;
            \tdata->rx_len_off = 0;
            \tdata->rx_len_type = AIC_H4_NO_LEN;
            \tdata->rx_type = 0;
            \tkfree_skb(data->rx_skb);
            \tdata->rx_skb = NULL;
            }

            static int aic_bt_config_pkt(struct aic_bt_data *data, u8 type)
            {
            \tdata->rx_type = type;
            \tswitch (type) {
            \tcase HCI_EVENT_PKT:
            \t\tdata->rx_hdr_len = HCI_EVENT_HDR_SIZE;
            \t\tdata->rx_len_off = 1;
            \t\tdata->rx_len_type = AIC_H4_LEN_U8;
            \t\tbreak;
            \tcase HCI_ACLDATA_PKT:
            \t\tdata->rx_hdr_len = HCI_ACL_HDR_SIZE;
            \t\tdata->rx_len_off = 2;
            \t\tdata->rx_len_type = AIC_H4_LEN_U16;
            \t\tbreak;
            \tcase HCI_SCODATA_PKT:
            \t\tdata->rx_hdr_len = HCI_SCO_HDR_SIZE;
            \t\tdata->rx_len_off = 2;
            \t\tdata->rx_len_type = AIC_H4_LEN_U8;
            \t\tbreak;
            \tcase HCI_ISODATA_PKT:
            \t\tdata->rx_hdr_len = HCI_ISO_HDR_SIZE;
            \t\tdata->rx_len_off = 2;
            \t\tdata->rx_len_type = AIC_H4_LEN_U16;
            \t\tbreak;
            \tdefault:
            \t\treturn -EILSEQ;
            \t}

            \tdata->rx_expect = data->rx_hdr_len;
            \tdata->rx_skb = bt_skb_alloc(HCI_MAX_FRAME_SIZE, GFP_ATOMIC);
            \tif (!data->rx_skb)
            \t\treturn -ENOMEM;

            \thci_skb_pkt_type(data->rx_skb) = type;
            \treturn 0;
            }

            static int aic_bt_try_complete_rx(struct aic_bt_data *data)
            {
            \tstruct sk_buff *skb = data->rx_skb;
            \tu16 payload_len = 0;

            \tif (!skb || skb->len < data->rx_expect)
            \t\treturn 0;

            \tif (data->rx_expect == data->rx_hdr_len) {
            \t\tswitch (data->rx_len_type) {
            \t\tcase AIC_H4_NO_LEN:
            \t\t\tpayload_len = 0;
            \t\t\tbreak;
            \t\tcase AIC_H4_LEN_U8:
            \t\t\tpayload_len = skb->data[data->rx_len_off];
            \t\t\tbreak;
            \t\tcase AIC_H4_LEN_U16:
            \t\t\tpayload_len = get_unaligned_le16(skb->data + data->rx_len_off);
            \t\t\tbreak;
            \t\t}

            \t\tif (payload_len > skb_tailroom(skb)) {
            \t\t\taic_bt_reset_rx_state(data);
            \t\t\treturn -EMSGSIZE;
            \t\t}

            \t\tif (payload_len) {
            \t\t\tdata->rx_expect += payload_len;
            \t\t\treturn 0;
            \t\t}
            \t}

            \tdata->rx_skb = NULL;
            \tdata->rx_expect = 0;
            \tdata->rx_hdr_len = 0;
            \tdata->rx_len_type = AIC_H4_NO_LEN;
            \treturn hci_recv_frame(data->hdev, skb);
            }

            static size_t aic_bt_receive_buf(struct serdev_device *serdev,
            \t\t\t\t     const u8 *buf, size_t count)
            {
            \tstruct aic_bt_data *data = serdev_device_get_drvdata(serdev);
            \tconst u8 *p = buf;
            \tint ret;

            \tif (!data || !data->hdev)
            \t\treturn count;

            \twhile (count) {
            \t\tint copy_len;

            \t\tif (!data->rx_skb) {
            \t\t\tret = aic_bt_config_pkt(data, *p++);
            \t\t\tcount--;
            \t\t\tif (ret)
            \t\t\t\tcontinue;
            \t\t\tif (!count)
            \t\t\t\tbreak;
            \t\t}

            \t\tcopy_len = min_t(int, data->rx_expect - data->rx_skb->len, count);
            \t\tskb_put_data(data->rx_skb, p, copy_len);
            \t\tp += copy_len;
            \t\tcount -= copy_len;

            \t\tret = aic_bt_try_complete_rx(data);
            \t\tif (ret)
            \t\t\taic_bt_reset_rx_state(data);
            \t}

            \tdata->hdev->stat.byte_rx += p - buf;
            \treturn p - buf;
            }

            static void aic_bt_write_wakeup(struct serdev_device *serdev)
            {
            \tstruct aic_bt_data *data = serdev_device_get_drvdata(serdev);
            \tschedule_work(&data->tx_work);
            }

            static const struct serdev_device_ops aic_bt_serdev_ops = {
            \t.receive_buf = aic_bt_receive_buf,
            \t.write_wakeup = aic_bt_write_wakeup,
            };

            static int aic_bt_flush(struct hci_dev *hdev)
            {
            \tstruct aic_bt_data *data = hci_get_drvdata(hdev);
            \tstruct sk_buff *skb;

            \tcancel_work_sync(&data->tx_work);
            \tserdev_device_write_flush(data->serdev);

            \tif (data->tx_skb) {
            \t\tkfree_skb(data->tx_skb);
            \t\tdata->tx_skb = NULL;
            \t}

            \twhile ((skb = skb_dequeue(&data->txq)))
            \t\tkfree_skb(skb);

            \taic_bt_reset_rx_state(data);
            \treturn 0;
            }

            static int aic_bt_open(struct hci_dev *hdev)
            {
            \tstruct aic_bt_data *data = hci_get_drvdata(hdev);

            \tserdev_device_set_flow_control(data->serdev, true);
            \tserdev_device_set_baudrate(data->serdev, __BT_UART_SPEED__);
            \treturn 0;
            }

            static int aic_bt_close(struct hci_dev *hdev)
            {
            \treturn aic_bt_flush(hdev);
            }

            static int aic_bt_setup(struct hci_dev *hdev)
            {
            \tstruct sk_buff *skb;

            \tskb = __hci_cmd_sync(hdev, HCI_OP_RESET, 0, NULL, HCI_INIT_TIMEOUT);
            \tif (IS_ERR(skb))
            \t\treturn PTR_ERR(skb);

            \tkfree_skb(skb);
            \treturn 0;
            }

            static int aic_bt_send_frame(struct hci_dev *hdev, struct sk_buff *skb)
            {
            \tstruct aic_bt_data *data;
            \tstruct sk_buff *nskb;
            \tu8 pkt_type;

            \tif (!skb)
            \t\treturn -EINVAL;

            \tdata = hci_get_drvdata(hdev);
            \tpkt_type = hci_skb_pkt_type(skb);

            \tnskb = bt_skb_alloc(skb->len + 1, GFP_ATOMIC);
            \tif (!nskb) {
            \t\tkfree_skb(skb);
            \t\treturn -ENOMEM;
            \t}

            \thci_skb_pkt_type(nskb) = pkt_type;
            \tskb_put_u8(nskb, pkt_type);
            \tskb_put_data(nskb, skb->data, skb->len);
            \tkfree_skb(skb);

            \tskb_queue_tail(&data->txq, nskb);
            \tschedule_work(&data->tx_work);
            \treturn 0;
            }

            static int aic_bt_serdev_probe(struct serdev_device *serdev)
            {
            \tstruct aic_bt_data *data;
            \tstruct hci_dev *hdev;
            \tint ret;

            \tdata = devm_kzalloc(&serdev->dev, sizeof(*data), GFP_KERNEL);
            \tif (!data)
            \t\treturn -ENOMEM;

            \tdata->serdev = serdev;
            \tserdev_device_set_drvdata(serdev, data);
            \tserdev_device_set_client_ops(serdev, &aic_bt_serdev_ops);

            \tINIT_WORK(&data->tx_work, aic_bt_tx_work);
            \tskb_queue_head_init(&data->txq);
            \taic_bt_reset_rx_state(data);

            \thdev = hci_alloc_dev();
            \tif (!hdev)
            \t\treturn -ENOMEM;

            \tdata->hdev = hdev;
            \thdev->bus = HCI_UART;
            \tSET_HCIDEV_DEV(hdev, &serdev->dev);

            \thdev->open  = aic_bt_open;
            \thdev->close = aic_bt_close;
            \thdev->setup = aic_bt_setup;
            \thdev->flush = aic_bt_flush;
            \thdev->send = aic_bt_send_frame;
            \thdev->manufacturer = 0x00;

            \thci_set_drvdata(hdev, data);

            \tret = serdev_device_open(serdev);
            \tif (ret) {
            \t\thci_free_dev(hdev);
            \t\treturn ret;
            \t}

            \tserdev_device_set_flow_control(serdev, true);
            \tserdev_device_set_baudrate(serdev, __BT_UART_SPEED__);

            \tret = hci_register_dev(hdev);
            \tif (ret) {
            \t\thci_free_dev(hdev);
            \t\tcancel_work_sync(&data->tx_work);
            \t\tserdev_device_close(serdev);
            \t\treturn ret;
            \t}

            \treturn 0;
            }

            static void aic_bt_serdev_remove(struct serdev_device *serdev)
            {
            \tstruct aic_bt_data *data = serdev_device_get_drvdata(serdev);

            \tif (!data || !data->hdev)
            \t\treturn;

            \tcancel_work_sync(&data->tx_work);
            \thci_unregister_dev(data->hdev);
            \thci_free_dev(data->hdev);
            \taic_bt_reset_rx_state(data);

            \tif (data->tx_skb) {
            \t\tkfree_skb(data->tx_skb);
            \t\tdata->tx_skb = NULL;
            \t}

            \tskb_queue_purge(&data->txq);
            \tserdev_device_close(serdev);
            }

            static const struct of_device_id aic_bt_of_match[] = {
            \t{ .compatible = "aicsemi,aic8800d80-bt" },
            \t{ }
            };
            MODULE_DEVICE_TABLE(of, aic_bt_of_match);

            static struct serdev_device_driver aic_bt_serdev_driver = {
            \t.probe = aic_bt_serdev_probe,
            \t.remove = aic_bt_serdev_remove,
            \t.driver = {
            \t\t.name = "hci_aic8800",
            \t\t.of_match_table = aic_bt_of_match,
            \t},
            };
            module_serdev_device_driver(aic_bt_serdev_driver);

            MODULE_LICENSE("GPL");
            MODULE_DESCRIPTION("AIC8800 Bluetooth UART transport");
            """
        ).replace("__BT_UART_SPEED__", str(data["bt_uart_speed"])),
    }


def write_bsp_csv(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["file", "symbol", "reason", "upstream_replacement"],
        )
        writer.writeheader()
        for row in data["bsp_debt"]:
            writer.writerow(row)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--data",
        type=Path,
        default=DATA_PATH,
        help="Path to source JSON data",
    )
    parser.add_argument(
        "--docs-root",
        type=Path,
        default=ROOT / "docs" / "upstream-drafts",
        help="Destination root for generated draft docs",
    )
    args = parser.parse_args()

    data = load_data(args.data)

    docs_root = args.docs_root

    write_text(docs_root / "aicsemi,aic8800.yaml", gen_wifi_binding(data))
    write_text(docs_root / "aicsemi,aic8800-bt.yaml", gen_bt_binding(data))
    write_text(
        docs_root / "sun60i-a733-orangepi-4-pro-aic8800d80.dts.fragment",
        gen_dts_fragment(data),
    )

    kernel_root = docs_root / "kernel-files"
    for rel_path, content in gen_kernel_draft_files(data).items():
        write_text(kernel_root / rel_path, content)
        write_text(ROOT / rel_path, content)

    write_bsp_csv(ROOT / "docs" / "aic8800d80-bsp-debt.csv", data)


if __name__ == "__main__":
    main()
