#!/usr/bin/env python3
"""
Code generator for Allwinner sun60i-a733 mainline Linux drivers.

This script reads structured hardware descriptions and generates
repetitive C driver code using the mainline sunxi-ng and pinctrl-sunxi
frameworks. This minimizes manual C coding and potential bugs.

Usage:
    python3 generators/generate_pinctrl.py > drivers/pinctrl/sunxi/pinctrl-sun60i-a733.c
    python3 generators/generate_pinctrl.py --with-pinmux=dt > drivers/pinctrl/sunxi/pinctrl-sun60i-a733.c
    python3 generators/generate_pinctrl.py --with-pinmux=c > drivers/pinctrl/sunxi/pinctrl-sun60i-a733.c
    python3 generators/generate_ccu.py > drivers/clk/sunxi-ng/ccu-sun60i-a733.c
"""

import argparse
import json
import sys
from pathlib import Path

# Try to import the pinmux emitter plugin
_PINMUX_AVAILABLE = False
try:
    sys.path.insert(0, str(Path(__file__).parent))
    from plugins import pinmux_emitter

    _PINMUX_AVAILABLE = True
except Exception:
    pass

# --- Pinctrl Generator ---


def io_bias_cfg_variant(data):
    """Return the sunxi pinctrl I/O-bias selector named by the SoC data."""

    variants = {
        "pio_pow_mode_ctl": "BIAS_VOLTAGE_PIO_POW_MODE_CTL",
        "pio_pow_mode_sel": "BIAS_VOLTAGE_PIO_POW_MODE_SEL",
    }
    try:
        return variants[data["io_bias_cfg_variant"]]
    except KeyError as exc:
        valid = ", ".join(sorted(variants))
        raise ValueError(
            f"unsupported io_bias_cfg_variant {data.get('io_bias_cfg_variant')!r}; "
            f"expected one of: {valid}"
        ) from exc


def pinctrl_flags(data, continuation_indent):
    """Return the pinctrl feature flags as a wrap-safe C expression."""

    flag_names = {
        "new_reg_layout": "SUNXI_PINCTRL_NEW_REG_LAYOUT",
        "sun60_layout": "SUNXI_PINCTRL_SUN60_LAYOUT",
        "portf_switch": "SUNXI_PINCTRL_PORTF_SWITCH",
        "eleven_banks": "SUNXI_PINCTRL_ELEVEN_BANKS",
        "auto_power_switch": "SUNXI_PINCTRL_AUTO_POWER_SWITCH",
    }
    values = [
        flag_names[flag]
        for flag in (
            "new_reg_layout",
            "sun60_layout",
            "portf_switch",
            "eleven_banks",
            "auto_power_switch",
        )
        if flag in data.get("flags", [])
    ]
    return f" |\n{continuation_indent}".join(values) if values else "0"


def generate_pinctrl_dt(data):
    """Generate DT-mode pinctrl driver (base driver without pinmux tables)."""

    banks = data["banks"]
    irq_map = data["irq_bank_map"]
    irq_muxes = data["irq_bank_muxes"]
    bias_cfg_variant = io_bias_cfg_variant(data)

    nr_banks = ", ".join(str(banks.get(f"P{chr(65 + i)}", 0)) for i in range(11))
    irq_map_str = ", ".join(str(x) for x in irq_map)
    irq_muxes_str = ", ".join(str(x) for x in irq_muxes)

    flag_str = pinctrl_flags(data, "\t\t\t\t\t   ")

    return f"""// SPDX-License-Identifier: GPL-2.0
/*
 * Allwinner A733 SoC pinctrl driver.
 *
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: generators/generate_pinctrl.py
 * Source data:  generators/data/pinctrl-main.json
 */

#include <linux/module.h>
#include <linux/platform_device.h>
#include <linux/of.h>
#include <linux/of_device.h>
#include <linux/pinctrl/pinctrl.h>

#include "pinctrl-sunxi.h"

static const u8 a733_nr_bank_pins[SUNXI_PINCTRL_MAX_BANKS] =
/*	  PA  PB  PC  PD  PE  PF  PG  PH  PI  PJ  PK */
	{{ {nr_banks} }};

static const unsigned int a733_irq_bank_map[] = {{ {irq_map_str} }};

static const u8 a733_irq_bank_muxes[SUNXI_PINCTRL_MAX_BANKS] =
/*	  PA  PB  PC  PD  PE  PF  PG  PH  PI  PJ  PK */
	{{ {irq_muxes_str} }};

static struct sunxi_pinctrl_desc a733_pinctrl_data = {{
	.irq_banks = ARRAY_SIZE(a733_irq_bank_map),
	.irq_bank_map = a733_irq_bank_map,
	.irq_read_needs_mux = true,
	.io_bias_cfg_variant = {bias_cfg_variant},
}};

static int a733_pinctrl_probe(struct platform_device *pdev)
{{
	return sunxi_pinctrl_dt_table_init(pdev, a733_nr_bank_pins,
					   a733_irq_bank_muxes,
					   &a733_pinctrl_data,
					   {flag_str});
}}

static const struct of_device_id a733_pinctrl_match[] = {{
	{{ .compatible = "allwinner,sun60i-a733-pinctrl", }},
	{{}}
}};

static struct platform_driver a733_pinctrl_driver = {{
	.probe	= a733_pinctrl_probe,
	.driver	= {{
		.name		= "sun60i-a733-pinctrl",
		.of_match_table	= a733_pinctrl_match,
	}},
}};
builtin_platform_driver(a733_pinctrl_driver);
"""


def generate_pinctrl_c(data, pinmux_section):
    """Generate C-array-mode pinctrl driver with integrated pinmux tables."""

    irq_map = data["irq_bank_map"]
    bias_cfg_variant = io_bias_cfg_variant(data)

    irq_map_str = ", ".join(str(x) for x in irq_map)

    flag_str = pinctrl_flags(data, "\t\t\t\t\t     ")

    return f"""// SPDX-License-Identifier: GPL-2.0
/*
 * Allwinner A733 SoC pinctrl driver.
 *
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: generators/generate_pinctrl.py
 * Source data:  generators/data/pinctrl-main.json
 */

#include <linux/module.h>
#include <linux/platform_device.h>
#include <linux/of.h>
#include <linux/of_device.h>
#include <linux/pinctrl/pinctrl.h>

#include "pinctrl-sunxi.h"

{pinmux_section}

static const unsigned int a733_irq_bank_map[] = {{ {irq_map_str} }};

static struct sunxi_pinctrl_desc a733_pinctrl_data = {{
	.pins = sun60i_a733_pins,
	.npins = ARRAY_SIZE(sun60i_a733_pins),
	.irq_banks = ARRAY_SIZE(a733_irq_bank_map),
	.irq_bank_map = a733_irq_bank_map,
	.irq_read_needs_mux = true,
	.io_bias_cfg_variant = {bias_cfg_variant},
}};

static int a733_pinctrl_probe(struct platform_device *pdev)
{{
	return sunxi_pinctrl_init_with_flags(pdev, &a733_pinctrl_data,
					     {flag_str});
}}

static const struct of_device_id a733_pinctrl_match[] = {{
	{{ .compatible = "allwinner,sun60i-a733-pinctrl", }},
	{{}}
}};

static struct platform_driver a733_pinctrl_driver = {{
	.probe	= a733_pinctrl_probe,
	.driver	= {{
		.name		= "sun60i-a733-pinctrl",
		.of_match_table	= a733_pinctrl_match,
	}},
}};
builtin_platform_driver(a733_pinctrl_driver);
"""


# --- Main ---

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate pinctrl driver C code")
    parser.add_argument(
        "--with-pinmux",
        choices=["c", "dt", "none"],
        default="none",
        help="Embed pinmux tables emitted by the pinmux_emitter plugin (default: none)",
    )
    args = parser.parse_args()

    data_file = Path(__file__).parent / "data" / "pinctrl-main.json"

    if not data_file.exists():
        print(f"Error: {data_file} not found", file=sys.stderr)
        sys.exit(1)

    with open(data_file) as f:
        data = json.load(f)

    if args.with_pinmux == "c":
        if not _PINMUX_AVAILABLE:
            print(
                "/* ERROR: pinmux_emitter plugin not available */",
                file=sys.stderr,
            )
            sys.exit(1)

        try:
            pinmux_data = pinmux_emitter.get_pinmux_data()
            # Override IRQ data with pinctrl-main.json for consistency
            pinmux_data["irq"]["bank_map"] = data["irq_bank_map"]
            pinmux_data["irq"]["bank_mux"] = data["irq_bank_muxes"]
            errors = pinmux_emitter.validate_emission(pinmux_data)
            if errors:
                print("/* Pinmux validation errors:", file=sys.stderr)
                for e in errors:
                    print(f"   - {e}", file=sys.stderr)
                print(" */", file=sys.stderr)
                sys.exit(1)

            pinmux_output = pinmux_emitter.emit_pinmux_section(pinmux_data, mode="c")
            print(generate_pinctrl_c(data, pinmux_output))
        except Exception as exc:
            print(f"/* ERROR generating pinmux: {exc} */", file=sys.stderr)
            sys.exit(1)
    else:
        print(generate_pinctrl_dt(data))

        if args.with_pinmux == "dt":
            if not _PINMUX_AVAILABLE:
                print(
                    "/* ERROR: pinmux_emitter plugin not available */",
                    file=sys.stderr,
                )
                sys.exit(1)

            try:
                pinmux_data = pinmux_emitter.get_pinmux_data()
                errors = pinmux_emitter.validate_emission(pinmux_data)
                if errors:
                    print("/* Pinmux validation errors:", file=sys.stderr)
                    for e in errors:
                        print(f"   - {e}", file=sys.stderr)
                    print(" */", file=sys.stderr)
                    sys.exit(1)

                pinmux_output = pinmux_emitter.emit_pinmux_section(
                    pinmux_data, mode="dt"
                )
                print()
                print(f"/* --- Pinmux table ({args.with_pinmux}) --- */")
                print(pinmux_output)
            except Exception as exc:
                print(f"/* ERROR generating pinmux: {exc} */", file=sys.stderr)
                sys.exit(1)
