// SPDX-License-Identifier: GPL-2.0-only
// GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: generators/generate_aic8800_upstream.py

#include <linux/errno.h>
#include <linux/module.h>
#include <linux/string.h>
#include "core_types.h"
#include "cfg80211_core.h"
#include "fw_protocol.h"
#include "netdev_core.h"

int aic8800_core_register(struct aic8800_core *core)
{
	int ret;

	if (!core || !core->dev)
		return -EINVAL;

	core->wiphy = NULL;
	core->ndev = NULL;
	core->protocol = NULL;
	core->fw_data = NULL;
	core->fw_hooks = NULL;
	core->fw_override[0] = '\0';
	core->fw_loaded[0] = '\0';
	core->irq_count = 0;
	core->rx_batches = 0;
	core->rx_frames = 0;
	core->rx_empty = 0;
	core->rx_malformed = 0;
	core->rx_resync = 0;
	core->rx_errors = 0;
	core->rx_submit_runs = 0;
	core->rx_q_high_water = 0;
	core->tx_frames = 0;
	core->tx_retries = 0;
	core->tx_errors = 0;
	core->tx_q_full = 0;
	core->rx_drop_queue_full = 0;
	core->rx_drop_malformed = 0;
	core->tx_drop_queue_full = 0;
	core->tx_stall_events = 0;
	core->tx_recoveries = 0;
	core->tx_reinit_events = 0;
	core->link_up = false;
	memset(core->bssid, 0, sizeof(core->bssid));

	ret = aic8800_protocol_init(core);
	if (ret)
		return ret;

	ret = aic8800_cfg80211_register(core);
	if (ret)
		goto err_protocol;

	ret = aic8800_netdev_register(core);
	if (ret)
		goto err_cfg;

	return 0;

err_cfg:
	aic8800_cfg80211_unregister(core);
err_protocol:
	aic8800_protocol_deinit(core);
	return ret;
}

void aic8800_core_unregister(struct aic8800_core *core)
{
	if (!core)
		return;

	aic8800_netdev_unregister(core);
	aic8800_protocol_deinit(core);
	aic8800_cfg80211_unregister(core);
	if (core->dev)
		dev_info(core->dev,
			"aic8800 io summary: irq=%llu rx_batches=%llu rx_frames=%llu rx_empty=%llu rx_malformed=%llu rx_resync=%llu rx_err=%llu rx_submit_runs=%llu rx_q_hwm=%llu rx_drop_qfull=%llu rx_drop_malformed=%llu tx_frames=%llu tx_retries=%llu tx_q_full=%llu tx_drop_qfull=%llu tx_stall=%llu tx_recoveries=%llu tx_reinit=%llu tx_err=%llu\n",
			(unsigned long long)core->irq_count,
			(unsigned long long)core->rx_batches,
			(unsigned long long)core->rx_frames,
			(unsigned long long)core->rx_empty,
			(unsigned long long)core->rx_malformed,
			(unsigned long long)core->rx_resync,
			(unsigned long long)core->rx_errors,
			(unsigned long long)core->rx_submit_runs,
			(unsigned long long)core->rx_q_high_water,
			(unsigned long long)core->rx_drop_queue_full,
			(unsigned long long)core->rx_drop_malformed,
			(unsigned long long)core->tx_frames,
			(unsigned long long)core->tx_retries,
			(unsigned long long)core->tx_q_full,
			(unsigned long long)core->tx_drop_queue_full,
			(unsigned long long)core->tx_stall_events,
			(unsigned long long)core->tx_recoveries,
			(unsigned long long)core->tx_reinit_events,
			(unsigned long long)core->tx_errors);
	if (core->fw_data) {
		release_firmware(core->fw_data);
		core->fw_data = NULL;
		core->fw_loaded[0] = '\0';
	}
}

EXPORT_SYMBOL_GPL(aic8800_core_register);
EXPORT_SYMBOL_GPL(aic8800_core_unregister);
MODULE_LICENSE("GPL");
MODULE_DESCRIPTION("AIC8800 core WiFi support");
