// SPDX-License-Identifier: GPL-2.0-only
// GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: generators/generate_aic8800_upstream.py

#include <linux/errno.h>
#include <linux/delay.h>
#include <linux/etherdevice.h>
#include <linux/if_ether.h>
#include <linux/kernel.h>
#include <linux/mmc/card.h>
#include <linux/mmc/sdio.h>
#include <linux/mmc/sdio_func.h>
#include <linux/netdevice.h>
#include <linux/skbuff.h>
#include <linux/slab.h>
#include <linux/string.h>
#include <linux/types.h>
#include "fw_protocol.h"
#include "sdio_io.h"

u8 aic8800_sdio_crc8(const u8 *buf, size_t len);

u8 aic8800_sdio_crc8(const u8 *buf, size_t len)
{
	/* AIC SDIO header CRC-8 with polynomial X8+X2+X+1 (0x107),
	 * MSB-first within each byte, double-XOR data bit into poly */
	u8 i;
	u8 crc = 0;

	if (!len)
		return 0;

	while (len--) {
		for (i = 0x80; i > 0; i /= 2) {
			if (crc & 0x80) {
				crc *= 2;
				crc ^= 0x07;
			} else {
				crc *= 2;
			}
			if (*buf & i)
				crc ^= 0x07;
		}
		buf++;
	}

	return crc;
}

int aic8800_sdio_readb(struct sdio_func *func, unsigned int addr,
			 u8 *val)
{
	int ret;

	if (!func || !val)
		return -EINVAL;

	sdio_claim_host(func);
	*val = sdio_readb(func, addr, &ret);
	sdio_release_host(func);

	return ret;
}

int aic8800_sdio_writeb(struct sdio_func *func, unsigned int addr,
			 u8 val)
{
	int ret;

	if (!func)
		return -EINVAL;

	sdio_claim_host(func);
	sdio_writeb(func, val, addr, &ret);
	sdio_release_host(func);

	return ret;
}

int aic8800_sdio_io_init(struct sdio_func *func)
{
	int ret;

	if (!func)
		return -EINVAL;

	sdio_claim_host(func);

	/* The pad configuration below writes function 0 below 0xf0. */
	func->card->quirks |= MMC_QUIRK_LENIENT_FN0;

	ret = sdio_set_block_size(func, AIC8800_SDIO_BLOCK_SIZE);
	if (ret) {
		sdio_release_host(func);
		return ret;
	}

	ret = sdio_enable_func(func);
	if (ret) {
		sdio_release_host(func);
		return ret;
	}

	/* Device I/O pad drive and delay selection. */
	sdio_f0_writeb(func, 0x7f, 0xf2, &ret);
	if (ret)
		goto err_disable;

	sdio_f0_writeb(func, 0x80, 0xf1, &ret);
	if (ret)
		goto err_disable;

	sdio_release_host(func);

	/* Let the pad setting settle before the first register access. */
	usleep_range(1000, 2000);

	/* Select block mode; this driver does not use byte mode. */
	ret = aic8800_sdio_writeb(func, AIC8800_SDIO_BYTEMODE_ENABLE_REG,
				  AIC8800_SDIO_BYTEMODE_DISABLE);
	if (ret) {
		dev_err(&func->dev,
			"failed to select SDIO block mode: %d\n", ret);
		sdio_claim_host(func);
		goto err_disable;
	}

	return 0;

err_disable:
	sdio_disable_func(func);
	sdio_release_host(func);
	return ret;
}

void aic8800_sdio_io_deinit(struct sdio_func *func)
{
	if (!func)
		return;

	sdio_claim_host(func);
	sdio_disable_func(func);
	sdio_release_host(func);
}

int aic8800_sdio_flow_ctrl(struct sdio_func *func, const bool *abort)
{
	unsigned int count = 0;
	u8 fc_reg;
	int ret;

	if (!func)
		return -EINVAL;

	for (;;) {
		ret = aic8800_sdio_readb(func,
					 AIC8800_SDIO_FLOW_CTRL_Q1_REG,
					 &fc_reg);
		if (ret)
			return ret;

		/* Buffers beyond the reserve are available to us. */
		if (fc_reg > AIC8800_SDIO_FLOW_CTRL_THRESH)
			return fc_reg;

		if (count >= AIC8800_SDIO_FLOW_CTRL_RETRY ||
		    (abort && *abort))
			return -EBUSY;

		/* Spin while the firmware is likely to drain quickly,
		 * then back off to sleeping waits.
		 */
		if (count < 30)
			udelay(200);
		else if (count < 40)
			usleep_range(2000, 3000);
		else
			usleep_range(10000, 11000);
		count++;
	}
}

int aic8800_sdio_tx_write(struct sdio_func *func,
			 const u8 *data, size_t len)
{
	/*
	 * Wire format of one frame:
	 *   [0-1] payload length, little endian, 12 significant bits
	 *   [2]   0x01, data
	 *   [3]   CRC8 (polynomial 0x107) over bytes 0-2
	 *   payload, zero padded to a 4-byte boundary
	 *   a zero terminator word when the result is not already a
	 *   whole number of blocks, then zero padding to the block size
	 */
	size_t aligned_len;
	size_t block_len;
	u8 *buf;
	int ret;

	if (!func || !data || !len)
		return -EINVAL;

	if (len > AIC8800_SDIO_TX_MAX_PAYLOAD)
		return -EMSGSIZE;

	aligned_len = ALIGN(AIC8800_SDIO_TX_HDR_LEN + len,
			    AIC8800_SDIO_TX_ALIGNMENT);
	if (aligned_len % AIC8800_SDIO_BLOCK_SIZE)
		aligned_len += AIC8800_SDIO_TX_TAIL_LEN;
	block_len = ALIGN(aligned_len, AIC8800_SDIO_BLOCK_SIZE);

	/* kzalloc supplies both the alignment padding and the zero
	 * terminator word the firmware uses to end the chain.
	 */
	buf = kzalloc(block_len, GFP_KERNEL);
	if (!buf)
		return -ENOMEM;

	buf[0] = len & 0xff;
	buf[1] = (len >> 8) & 0x0f;
	buf[2] = 0x01;
	buf[3] = aic8800_sdio_crc8(buf, 3);
	memcpy(buf + AIC8800_SDIO_TX_HDR_LEN, data, len);

	sdio_claim_host(func);
	ret = sdio_writesb(func, AIC8800_SDIO_WR_FIFO_ADDR, buf,
			   block_len);
	sdio_release_host(func);
	kfree(buf);

	if (ret)
		dev_err(&func->dev, "TX write failed: %d\n", ret);

	return ret;
}

int aic8800_sdio_rx_drain(struct aic8800_core *core, int budget)
{
	struct sdio_func *func;
	int frames = 0;
	int ret = 0;

	if (!core || !core->dev)
		return -EINVAL;

	if (!core->protocol)
		return -ENODATA;

	if (budget <= 0)
		budget = 1;

	func = dev_to_sdio_func(core->dev);
	if (!func)
		return -ENODEV;

	while (frames < budget) {
		u8 *frame;
		u8 int_status;
		u8 block_mask;
		u32 data_len;
		bool byte_mode = false;

		ret = aic8800_sdio_readb(func,
					 AIC8800_SDIO_MISC_INT_STATUS_REG,
					 &int_status);
		if (ret) {
			if (ret == -ENOMEDIUM)
				break;
			return ret;
		}

		/* A soft interrupt is acknowledged separately, in the
		 * pending register, and carries no payload of its own.
		 */
		if (int_status & AIC8800_SDIO_OTHER_INTERRUPT) {
			u8 pending;

			ret = aic8800_sdio_readb(func,
						 AIC8800_SDIO_INTR_PENDING_REG,
						 &pending);
			if (ret)
				return ret;

			pending &= ~AIC8800_SDIO_INTR_PENDING_SOFT;
			ret = aic8800_sdio_writeb(func,
						  AIC8800_SDIO_INTR_PENDING_REG,
						  pending);
			if (ret)
				return ret;
		}

		if (!int_status)
			break;

		/* The status byte encodes both the source and the size.
		 * Forcing bit 3 set separates the function 2 range, which
		 * uses a narrower block count. Either range has a marker
		 * value that means the length comes from a register in
		 * units of four bytes instead.
		 */
		if ((int_status | BIT(3)) > AIC8800_SDIO_BYTEMODE_MARK_F1) {
			byte_mode = (int_status | BIT(3)) ==
				    AIC8800_SDIO_BYTEMODE_MARK_F2;
			block_mask = AIC8800_SDIO_BLOCK_CNT_MASK_F2;
		} else {
			byte_mode = int_status ==
				    AIC8800_SDIO_BYTEMODE_MARK_F1;
			block_mask = AIC8800_SDIO_BLOCK_CNT_MASK_F1;
		}

		if (byte_mode) {
			u8 byte_len;

			ret = aic8800_sdio_readb(func,
						 AIC8800_SDIO_BYTEMODE_LEN_REG,
						 &byte_len);
			if (ret)
				return ret;

			data_len = byte_len * 4;
		} else {
			data_len = (int_status & block_mask) *
				   AIC8800_SDIO_BLOCK_SIZE;
		}

		if (!data_len)
			break;

		/* Bounded by the encoding above, but check anyway: the
		 * length comes from the device.
		 */
		if (data_len > AIC8800_SDIO_RX_MAX_LEN)
			return -EPROTO;

		frame = kmalloc(data_len, GFP_KERNEL);
		if (!frame)
			return -ENOMEM;

		/* Always drain what the device announced. Leaving bytes
		 * in the read FIFO wedges it for good.
		 */
		sdio_claim_host(func);
		ret = sdio_readsb(func, frame, AIC8800_SDIO_RD_FIFO_ADDR,
				  data_len);
		sdio_release_host(func);
		if (ret) {
			kfree(frame);
			return ret;
		}

		if (data_len > 2304) {
			dev_warn_ratelimited(core->dev,
				"discarding %u byte RX frame\n", data_len);
			core->rx_malformed++;
			kfree(frame);
			frames++;
			continue;
		}

		ret = aic8800_protocol_rx(core, frame, data_len);
		kfree(frame);
		if (ret < 0)
			core->rx_malformed++;
		frames++;
	}

	if (!frames) {
		core->rx_empty++;
		return -ENODATA;
	}

	core->rx_batches++;
	core->rx_frames += frames;

	return frames;
}
