 // SPDX-License-Identifier: GPL-2.0-only
// GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: generators/generate_aic8800_upstream.py

#include <linux/errno.h>
#include <linux/delay.h>
#include <linux/debugfs.h>
#include <linux/etherdevice.h>
#include <linux/fs.h>
#include <linux/interrupt.h>
#include <linux/jiffies.h>
#include <linux/module.h>
#include <linux/mutex.h>
#include <linux/mmc/card.h>
#include <linux/mmc/host.h>
#include <linux/mmc/sdio.h>
#include <linux/mmc/sdio_func.h>
#include <linux/netdevice.h>
#include <linux/skbuff.h>
#include <linux/slab.h>
#include <linux/seq_file.h>
#include <linux/string.h>
#include <linux/sys_soc.h>
#include <linux/uaccess.h>
#include <linux/workqueue.h>
#include "core_types.h"
#include "fw_protocol.h"
#include "sdio_io.h"

struct aic8800_sdio {
	struct aic8800_core core;
	struct work_struct rx_work;
	struct work_struct rx_submit_work;
	struct work_struct tx_work;
	struct delayed_work tx_watchdog_work;
	struct sk_buff_head rxq;
	struct sk_buff_head txq;
	struct sk_buff *tx_skb;
	u64 tx_watch_last_frames;
	u32 tx_watch_stall_ticks;
	u32 tx_recover_fail_streak;
	unsigned long tx_reinit_cooldown_until;
	struct mutex recovery_lock;
	bool tx_reinit_in_progress;
	struct dentry *dbg_dir;
	bool rx_stopping;
	bool tx_stopping;
};

static int aic8800_sdio_tx_recover(struct aic8800_sdio *sdio);
static int aic8800_sdio_reinit_transport(struct aic8800_sdio *sdio,
					 bool force);
static void aic8800_sdio_rx_purge(struct aic8800_sdio *sdio);
static void aic8800_sdio_irq_handler(struct sdio_func *func);

static const struct soc_device_attribute aic8800_sdio_soc_match[] = {
	{ .family = "Allwinner" },
	{ }
};

static int aic8800_sdio_dbg_stats_show(struct seq_file *m, void *v)
{
	struct aic8800_sdio *sdio = m->private;
	struct aic8800_core *core = &sdio->core;
	unsigned long now;
	u32 cooldown_left_ms;
	bool reinit_in_progress;

	mutex_lock(&sdio->recovery_lock);
	now = jiffies;
	reinit_in_progress = sdio->tx_reinit_in_progress;
	if (time_before(now, sdio->tx_reinit_cooldown_until))
		cooldown_left_ms = jiffies_to_msecs(
			sdio->tx_reinit_cooldown_until - now);
	else
		cooldown_left_ms = 0;
	mutex_unlock(&sdio->recovery_lock);

	seq_printf(m, "irq_count=%llu\n", (unsigned long long)core->irq_count);
	seq_printf(m, "rx_batches=%llu\n", (unsigned long long)core->rx_batches);
	seq_printf(m, "rx_frames=%llu\n", (unsigned long long)core->rx_frames);
	seq_printf(m, "rx_empty=%llu\n", (unsigned long long)core->rx_empty);
	seq_printf(m, "rx_malformed=%llu\n", (unsigned long long)core->rx_malformed);
	seq_printf(m, "rx_resync=%llu\n", (unsigned long long)core->rx_resync);
	seq_printf(m, "rx_errors=%llu\n", (unsigned long long)core->rx_errors);
	seq_printf(m, "rx_submit_runs=%llu\n", (unsigned long long)core->rx_submit_runs);
	seq_printf(m, "rx_q_high_water=%llu\n", (unsigned long long)core->rx_q_high_water);
	seq_printf(m, "rx_drop_queue_full=%llu\n", (unsigned long long)core->rx_drop_queue_full);
	seq_printf(m, "rx_drop_malformed=%llu\n", (unsigned long long)core->rx_drop_malformed);
	seq_printf(m, "tx_frames=%llu\n", (unsigned long long)core->tx_frames);
	seq_printf(m, "tx_retries=%llu\n", (unsigned long long)core->tx_retries);
	seq_printf(m, "tx_q_full=%llu\n", (unsigned long long)core->tx_q_full);
	seq_printf(m, "tx_drop_queue_full=%llu\n", (unsigned long long)core->tx_drop_queue_full);
	seq_printf(m, "tx_stall_events=%llu\n", (unsigned long long)core->tx_stall_events);
	seq_printf(m, "tx_recoveries=%llu\n", (unsigned long long)core->tx_recoveries);
	seq_printf(m, "tx_reinit_events=%llu\n", (unsigned long long)core->tx_reinit_events);
	seq_printf(m, "tx_reinit_in_progress=%u\n", reinit_in_progress ? 1 : 0);
	seq_printf(m, "tx_reinit_cooldown_ms_left=%u\n", cooldown_left_ms);
	seq_printf(m, "tx_errors=%llu\n", (unsigned long long)core->tx_errors);
	seq_printf(m, "rx_queue_len=%u\n", skb_queue_len(&sdio->rxq));
	seq_printf(m, "tx_queue_len=%u\n", skb_queue_len(&sdio->txq));
	seq_printf(m, "fw_active=%s\n",
		aic8800_core_get_fw_active_name(core) ?
		aic8800_core_get_fw_active_name(core) : "<none>");
	seq_printf(m, "fw_loaded=%s\n",
		core->fw_loaded[0] ? core->fw_loaded : "<none>");
	seq_printf(m, "fw_loaded_size=%zu\n",
		core->fw_data ? core->fw_data->size : 0UL);

	return 0;
}

static int aic8800_sdio_dbg_stats_open(struct inode *inode, struct file *file)
{
	return single_open(file, aic8800_sdio_dbg_stats_show, inode->i_private);
}

static const struct file_operations aic8800_sdio_dbg_stats_fops = {
	.owner = THIS_MODULE,
	.open = aic8800_sdio_dbg_stats_open,
	.read = seq_read,
	.llseek = seq_lseek,
	.release = single_release,
};

static ssize_t aic8800_sdio_dbg_control_write(struct file *file,
					 const char __user *ubuf,
					 size_t count,
					 loff_t *ppos)
{
	struct aic8800_sdio *sdio = file->private_data;
	char cmd[192];
	char *arg;
	char *nl;
	size_t n = min_t(size_t, count, sizeof(cmd) - 1);
	int ret = 0;

	if (!sdio)
		return -EINVAL;

	if (copy_from_user(cmd, ubuf, n))
		return -EFAULT;
	cmd[n] = '\0';
	nl = strpbrk(cmd, "\r\n");
	if (nl)
		*nl = '\0';

	arg = strchr(cmd, ' ');
	if (arg) {
		*arg = '\0';
		arg++;
		while (*arg == ' ')
			arg++;
		if (!*arg)
			arg = NULL;
	}

	if (!strcmp(cmd, "tx_recover")) {
		ret = aic8800_sdio_tx_recover(sdio);
	} else if (!strcmp(cmd, "reinit")) {
		ret = aic8800_sdio_reinit_transport(sdio, true);
	} else if (!strcmp(cmd, "rx_purge")) {
		aic8800_sdio_rx_purge(sdio);
	} else if (!strcmp(cmd, "rx_kick")) {
		schedule_work(&sdio->rx_work);
	} else if (!strcmp(cmd, "fw_set")) {
		if (!arg)
			return -EINVAL;
		ret = aic8800_core_set_fw_override(&sdio->core, arg);
	} else if (!strcmp(cmd, "fw_clear")) {
		aic8800_core_clear_fw_override(&sdio->core);
	} else {
		return -EINVAL;
	}

	if (ret < 0)
		return ret;

	return count;
}

static const struct file_operations aic8800_sdio_dbg_control_fops = {
	.owner = THIS_MODULE,
	.open = simple_open,
	.write = aic8800_sdio_dbg_control_write,
	.llseek = noop_llseek,
};

static void aic8800_sdio_debugfs_init(struct aic8800_sdio *sdio)
{
	sdio->dbg_dir = debugfs_create_dir("aic8800_sdio", NULL);
	if (IS_ERR_OR_NULL(sdio->dbg_dir))
		return;

	debugfs_create_file("stats", 0444, sdio->dbg_dir, sdio,
			    &aic8800_sdio_dbg_stats_fops);
	debugfs_create_file("control", 0200, sdio->dbg_dir, sdio,
			    &aic8800_sdio_dbg_control_fops);
}

static void aic8800_sdio_debugfs_deinit(struct aic8800_sdio *sdio)
{
	debugfs_remove_recursive(sdio->dbg_dir);
	sdio->dbg_dir = NULL;
}

static void aic8800_sdio_rx_submit_work(struct work_struct *work)
{
	struct aic8800_sdio *sdio =
		container_of(work, struct aic8800_sdio, rx_submit_work);
	int done = 0;

	sdio->core.rx_submit_runs++;

	while (done < 128) {
		struct sk_buff *skb = skb_dequeue(&sdio->rxq);

		if (!skb)
			break;

		skb->dev = sdio->core.ndev;
		skb->protocol = eth_type_trans(skb, sdio->core.ndev);
		skb->ip_summed = CHECKSUM_NONE;

		sdio->core.ndev->stats.rx_packets++;
		sdio->core.ndev->stats.rx_bytes += skb->len;
		netif_rx(skb);
		done++;
	}

	if (!sdio->rx_stopping && !skb_queue_empty(&sdio->rxq))
		schedule_work(&sdio->rx_submit_work);
}

static int aic8800_sdio_rx_submit(struct aic8800_core *core,
			      struct sk_buff *skb)
{
	struct aic8800_sdio *sdio;
	u32 qlen;

	if (!core || !core->bus_priv || !skb)
		return -EINVAL;

	sdio = core->bus_priv;
	if (sdio->rx_stopping)
		return -ESHUTDOWN;

	qlen = skb_queue_len(&sdio->rxq);
	if (qlen >= 256) {
		core->rx_drop_queue_full++;
		return -ENOSPC;
	}

	if ((qlen + 1) > core->rx_q_high_water)
		core->rx_q_high_water = qlen + 1;

	skb_queue_tail(&sdio->rxq, skb);
	schedule_work(&sdio->rx_submit_work);
	return 0;
}

static void aic8800_sdio_tx_watchdog_work(struct work_struct *work)
{
	struct aic8800_sdio *sdio =
		container_of(to_delayed_work(work),
			     struct aic8800_sdio, tx_watchdog_work);
	u32 qlen;

	if (sdio->tx_stopping)
		return;

	qlen = skb_queue_len(&sdio->txq) + (sdio->tx_skb ? 1 : 0);
	if (qlen && sdio->tx_watch_last_frames == sdio->core.tx_frames) {
		sdio->tx_watch_stall_ticks++;
		if (sdio->tx_watch_stall_ticks >= 4) {
		int ret;

		sdio->core.tx_stall_events++;
		sdio->tx_watch_stall_ticks = 0;
		dev_warn_ratelimited(sdio->core.dev,
			"SDIO TX stall suspected, qlen=%u\n", qlen);
		if (!sdio->tx_stopping) {
			sdio->tx_recover_fail_streak++;
			if (sdio->tx_recover_fail_streak >= 3) {
				ret = aic8800_sdio_reinit_transport(sdio, false);
				if (ret == 0)
					sdio->tx_recover_fail_streak = 0;
				else if (ret != -EAGAIN && ret != -EALREADY)
					sdio->core.tx_errors++;
			} else if (aic8800_sdio_tx_recover(sdio) != 0) {
				sdio->core.tx_errors++;
			}
		}
		}
	} else {
		sdio->tx_watch_stall_ticks = 0;
		sdio->tx_recover_fail_streak = 0;
	}

	sdio->tx_watch_last_frames = sdio->core.tx_frames;
	schedule_delayed_work(&sdio->tx_watchdog_work,
			      msecs_to_jiffies(500));
}

static void aic8800_sdio_tx_work(struct work_struct *work)
{
	struct aic8800_sdio *sdio =
		container_of(work, struct aic8800_sdio, tx_work);
	struct sdio_func *func;

	if (!sdio->core.dev)
		return;

	func = dev_to_sdio_func(sdio->core.dev);
	if (!func)
		return;

	while (!sdio->tx_stopping) {
		int avail;
		int ret;
		int tries = 0;

		if (!sdio->tx_skb) {
			sdio->tx_skb = skb_dequeue(&sdio->txq);
			if (!sdio->tx_skb)
				break;
		}

		/* Wait for the firmware to advertise free TX buffers. */
		avail = aic8800_sdio_flow_ctrl(func, &sdio->tx_stopping);
		if (avail < 0) {
			if (avail != -EBUSY)
				sdio->core.tx_errors++;
			break;
		}

		/* Do not start a frame the firmware cannot hold. */
		if (sdio->tx_skb->len + AIC8800_SDIO_TX_HDR_LEN >
		    (u32)avail * AIC8800_SDIO_BUFFER_SIZE)
			break;

		do {
			ret = aic8800_sdio_tx_write(func, sdio->tx_skb->data,
						      sdio->tx_skb->len);
			if (!ret)
				break;

			tries++;
			sdio->core.tx_retries++;
			if (tries <= 3)
				usleep_range(200,
					     200 + 200);
		} while (tries <= 3 && !sdio->tx_stopping);

		if (ret)
			sdio->core.tx_errors++;
		else {
			sdio->core.tx_frames++;
			sdio->tx_recover_fail_streak = 0;
		}

		if (sdio->core.ndev &&
		    netif_queue_stopped(sdio->core.ndev) &&
		    skb_queue_len(&sdio->txq) <= 128) {
			netif_wake_queue(sdio->core.ndev);
		}

		dev_kfree_skb_any(sdio->tx_skb);
		sdio->tx_skb = NULL;

		if (ret)
			break;
	}
}

int aic8800_sdio_tx_frame(struct aic8800_core *core,
			 const u8 *data, size_t len)
{
	struct aic8800_sdio *sdio;
	struct sk_buff *skb;

	if (!core || !core->bus_priv || !data || !len)
		return -EINVAL;

	sdio = core->bus_priv;
	if (sdio->tx_stopping)
		return -ESHUTDOWN;

	if (skb_queue_len(&sdio->txq) >= 512) {
		core->tx_q_full++;
		return -ENOSPC;
	}

	skb = alloc_skb(len, GFP_ATOMIC);
	if (!skb)
		return -ENOMEM;

	skb_put_data(skb, data, len);
	skb_queue_tail(&sdio->txq, skb);
	schedule_work(&sdio->tx_work);
	return 0;
}

static void aic8800_sdio_tx_flush(struct aic8800_sdio *sdio)
{
	sdio->tx_stopping = true;
	cancel_delayed_work_sync(&sdio->tx_watchdog_work);
	cancel_work_sync(&sdio->tx_work);

	if (sdio->tx_skb) {
		dev_kfree_skb_any(sdio->tx_skb);
		sdio->tx_skb = NULL;
	}

	skb_queue_purge(&sdio->txq);
}

static int aic8800_sdio_tx_recover(struct aic8800_sdio *sdio)
{
	if (!sdio || sdio->tx_stopping)
		return -EINVAL;

	cancel_work_sync(&sdio->tx_work);

	if (sdio->tx_skb) {
		dev_kfree_skb_any(sdio->tx_skb);
		sdio->tx_skb = NULL;
	}

	skb_queue_purge(&sdio->txq);
	sdio->core.tx_recoveries++;
	if (sdio->core.ndev && netif_queue_stopped(sdio->core.ndev))
		netif_wake_queue(sdio->core.ndev);

	schedule_work(&sdio->tx_work);
	return 0;
}

static int aic8800_sdio_reinit_transport(struct aic8800_sdio *sdio,
					 bool force)
{
	struct sdio_func *func;
	int ret = 0;
	u32 preserved_txq;
	unsigned long now;

	if (!sdio || sdio->tx_stopping || sdio->rx_stopping)
		return -EINVAL;

	if (!sdio->core.dev)
		return -ENODEV;

	func = dev_to_sdio_func(sdio->core.dev);
	if (!func)
		return -ENODEV;

	mutex_lock(&sdio->recovery_lock);
	if (sdio->tx_reinit_in_progress) {
		ret = -EALREADY;
		goto out_unlock;
	}

	now = jiffies;
	if (!force && time_before(now, sdio->tx_reinit_cooldown_until)) {
		ret = -EAGAIN;
		goto out_unlock;
	}

	sdio->tx_reinit_in_progress = true;
	sdio->tx_reinit_cooldown_until =
		now + msecs_to_jiffies(5000);
	mutex_unlock(&sdio->recovery_lock);

	dev_warn_ratelimited(sdio->core.dev,
		"SDIO transport reinit requested\n");

	cancel_work_sync(&sdio->tx_work);
	cancel_work_sync(&sdio->rx_work);
	cancel_work_sync(&sdio->rx_submit_work);

	if (sdio->tx_skb) {
		skb_queue_head(&sdio->txq, sdio->tx_skb);
		sdio->tx_skb = NULL;
	}
	preserved_txq = skb_queue_len(&sdio->txq);
	if (preserved_txq)
		dev_info_ratelimited(sdio->core.dev,
			"preserving %u queued TX frames across reinit\n",
			preserved_txq);
	skb_queue_purge(&sdio->rxq);

	sdio_claim_host(func);
	ret = sdio_release_irq(func);
	sdio_release_host(func);
	if (ret)
		dev_warn_ratelimited(sdio->core.dev,
			"sdio_release_irq during reinit returned %d\n", ret);

	aic8800_sdio_io_deinit(func);
	ret = aic8800_sdio_io_init(func);
	if (ret)
		goto out_finish;

	sdio_claim_host(func);
	ret = sdio_claim_irq(func, aic8800_sdio_irq_handler);
	sdio_release_host(func);
	if (ret) {
		aic8800_sdio_io_deinit(func);
		goto out_finish;
	}

	ret = aic8800_sdio_writeb(func, AIC8800_SDIO_INTR_ENABLE_REG,
				  AIC8800_SDIO_INTR_ENABLE_VAL);
	if (ret) {
		sdio_claim_host(func);
		sdio_release_irq(func);
		sdio_release_host(func);
		aic8800_sdio_io_deinit(func);
		goto out_finish;
	}

	sdio->core.tx_reinit_events++;
	sdio->tx_watch_stall_ticks = 0;
	sdio->tx_watch_last_frames = sdio->core.tx_frames;
	sdio->tx_recover_fail_streak = 0;
	if (sdio->core.ndev && netif_queue_stopped(sdio->core.ndev))
		netif_wake_queue(sdio->core.ndev);

	schedule_work(&sdio->rx_work);
	schedule_work(&sdio->tx_work);
	ret = 0;

out_finish:
	mutex_lock(&sdio->recovery_lock);
	sdio->tx_reinit_in_progress = false;
out_unlock:
	mutex_unlock(&sdio->recovery_lock);
	return ret;
}

static void aic8800_sdio_rx_work(struct work_struct *work)
{
	struct aic8800_sdio *sdio =
		container_of(work, struct aic8800_sdio, rx_work);
	int rounds = 0;

	while (!sdio->rx_stopping && rounds < 32) {
		int ret;

		ret = aic8800_sdio_rx_drain(&sdio->core, 8);
		if (ret == -ENODATA)
			break;

		if (ret < 0) {
			sdio->core.rx_errors++;
			dev_warn_ratelimited(sdio->core.dev,
				"SDIO RX drain failed: %d\n", ret);
			break;
		}

		rounds++;
	}
}

static void aic8800_sdio_rx_flush(struct aic8800_sdio *sdio)
{
	sdio->rx_stopping = true;
	cancel_work_sync(&sdio->rx_work);
	cancel_work_sync(&sdio->rx_submit_work);
	skb_queue_purge(&sdio->rxq);
}

static void aic8800_sdio_rx_purge(struct aic8800_sdio *sdio)
{
	if (!sdio || sdio->rx_stopping)
		return;

	cancel_work_sync(&sdio->rx_work);
	cancel_work_sync(&sdio->rx_submit_work);
	skb_queue_purge(&sdio->rxq);
	schedule_work(&sdio->rx_work);
}

static void aic8800_sdio_irq_handler(struct sdio_func *func)
{
	struct aic8800_sdio *sdio = sdio_get_drvdata(func);

	if (!sdio)
		return;

	sdio->core.irq_count++;

	/* The SDIO core calls this with the host claimed, so the
	 * status read and the FIFO drain are left to the RX work,
	 * which also acknowledges a soft interrupt if one is set.
	 */
	if (!sdio->rx_stopping)
		schedule_work(&sdio->rx_work);
}

static int aic8800_sdio_probe(struct sdio_func *func,
			      const struct sdio_device_id *id)
{
	struct aic8800_sdio *sdio;
	const struct soc_device_attribute *soc;
	struct sdio_func *bound_func;
	bool bootloader_mode;
	int ret;

	if (!func)
		return -EINVAL;

	bound_func = func;
	bootloader_mode = (func->device == 0x0182);
	if (bootloader_mode) {
		if (func->num != 2 || !func->card || !func->card->sdio_func[0])
			return dev_err_probe(&func->dev, -ENODEV,
				"bootloader requires SDIO function 1 transport\n");
		func = func->card->sdio_func[0];
	}

	sdio = devm_kzalloc(&bound_func->dev, sizeof(*sdio), GFP_KERNEL);
	if (!sdio)
		return -ENOMEM;

	sdio->core.dev = &func->dev;
	sdio->core.fw_name = "aic8800d80/fmacfw_8800d80.bin";
	INIT_WORK(&sdio->rx_work, aic8800_sdio_rx_work);
	INIT_WORK(&sdio->rx_submit_work, aic8800_sdio_rx_submit_work);
	INIT_WORK(&sdio->tx_work, aic8800_sdio_tx_work);
	INIT_DELAYED_WORK(&sdio->tx_watchdog_work,
			       aic8800_sdio_tx_watchdog_work);
	skb_queue_head_init(&sdio->rxq);
	skb_queue_head_init(&sdio->txq);
	sdio->tx_skb = NULL;
	sdio->tx_watch_last_frames = 0;
	sdio->tx_watch_stall_ticks = 0;
	sdio->tx_recover_fail_streak = 0;
	sdio->tx_reinit_cooldown_until = 0;
	sdio->tx_reinit_in_progress = false;
	mutex_init(&sdio->recovery_lock);
	sdio->rx_stopping = false;
	sdio->tx_stopping = false;

	if (!bootloader_mode) {
		soc = soc_device_match(aic8800_sdio_soc_match);
		if (!soc)
			dev_warn_once(&func->dev,
				"SoC match unavailable, using generic AIC8800 path\n");

		dev_info(&func->dev, "normal mode probe\n");
	} else {
		dev_info(&bound_func->dev,
			 "bootloader probe using SDIO function %u transport\n",
			 func->num);
	}

	sdio_set_drvdata(bound_func, sdio);
	if (func != bound_func)
		sdio_set_drvdata(func, sdio);
	sdio->core.bus_priv = sdio;
	sdio->core.tx_frame = aic8800_sdio_tx_frame;
	sdio->core.tx_command = aic8800_sdio_tx_frame;
	sdio->core.rx_submit = aic8800_sdio_rx_submit;

	ret = aic8800_sdio_io_init(func);
	if (ret)
		goto err_drvdata;

	sdio_claim_host(func);
	ret = sdio_claim_irq(func, aic8800_sdio_irq_handler);
	sdio_release_host(func);
	if (ret)
		goto err_io;

	if (!bootloader_mode) {
		/* The device wants the CCCR interrupt enables written
		 * directly once the runtime firmware is up.
		 */
		sdio_claim_host(func);
		sdio_f0_writeb(func, 0x07, SDIO_CCCR_IENx, &ret);
		sdio_release_host(func);
		if (ret)
			dev_warn(&func->dev,
				"CCCR int enable returned %d\n", ret);
	}

	ret = aic8800_sdio_writeb(func, AIC8800_SDIO_INTR_ENABLE_REG,
				  AIC8800_SDIO_INTR_ENABLE_VAL);
	if (ret)
		goto err_irq;

	if (bootloader_mode) {
		ret = aic8800_protocol_init(&sdio->core);
		if (ret)
			goto err_irq;

		ret = aic8800_protocol_boot(&sdio->core);
		aic8800_protocol_deinit(&sdio->core);
		if (ret)
			goto err_irq;

	sdio_claim_host(func);
	sdio_release_irq(func);
	sdio_release_host(func);
	aic8800_sdio_io_deinit(func);
	sdio_set_drvdata(func, NULL);
	sdio_set_drvdata(bound_func, NULL);
	if (func->card && func->card->host)
		mmc_detect_change(func->card->host, msecs_to_jiffies(100));
	dev_info(&bound_func->dev,
		"firmware started; requested SDIO re-enumeration\n");
	return 0;
	}

	ret = aic8800_core_register(&sdio->core);
	if (ret)
		goto err_irq;

	aic8800_sdio_debugfs_init(sdio);
	schedule_delayed_work(&sdio->tx_watchdog_work,
			      msecs_to_jiffies(500));
	return 0;

err_irq:
	sdio_claim_host(func);
	sdio_release_irq(func);
	sdio_release_host(func);
err_io:
	aic8800_sdio_rx_flush(sdio);
	aic8800_sdio_tx_flush(sdio);
	aic8800_sdio_io_deinit(func);
err_drvdata:
	sdio_set_drvdata(func, NULL);
	if (func != bound_func)
		sdio_set_drvdata(bound_func, NULL);
	return ret;
}

static void aic8800_sdio_remove(struct sdio_func *func)
{
	struct aic8800_sdio *sdio = sdio_get_drvdata(func);

	if (!sdio)
		return;

	sdio_claim_host(func);
	sdio_release_irq(func);
	sdio_release_host(func);
	aic8800_sdio_debugfs_deinit(sdio);
	aic8800_sdio_rx_flush(sdio);
	aic8800_sdio_tx_flush(sdio);
	aic8800_sdio_io_deinit(func);
	sdio->core.bus_priv = NULL;
	sdio->core.tx_frame = NULL;
	sdio->core.tx_command = NULL;
	sdio->core.rx_submit = NULL;
	aic8800_core_unregister(&sdio->core);
	sdio_set_drvdata(func, NULL);
}

static const struct sdio_device_id aic8800_boot_sdio_ids[] = {
	{ SDIO_DEVICE(0xc8a1, 0x0182) },
	{ }
};
MODULE_DEVICE_TABLE(sdio, aic8800_boot_sdio_ids);

static const struct sdio_device_id aic8800_runtime_sdio_ids[] = {
	{ SDIO_DEVICE(0xc8a1, 0x0082) },
	{ }
};
MODULE_DEVICE_TABLE(sdio, aic8800_runtime_sdio_ids);

static struct sdio_driver aic8800_boot_sdio_driver = {
	.name = "aic8800_boot_sdio",
	.id_table = aic8800_boot_sdio_ids,
	.probe = aic8800_sdio_probe,
	.remove = aic8800_sdio_remove,
};

static struct sdio_driver aic8800_runtime_sdio_driver = {
	.name = "aic8800_runtime_sdio",
	.id_table = aic8800_runtime_sdio_ids,
	.probe = aic8800_sdio_probe,
	.remove = aic8800_sdio_remove,
};

static int __init aic8800_sdio_init(void)
{
	int ret;

	ret = sdio_register_driver(&aic8800_runtime_sdio_driver);
	if (ret)
		return ret;
	ret = sdio_register_driver(&aic8800_boot_sdio_driver);
	if (ret)
		sdio_unregister_driver(&aic8800_runtime_sdio_driver);
	return ret;
}

static void __exit aic8800_sdio_exit(void)
{
	sdio_unregister_driver(&aic8800_boot_sdio_driver);
	sdio_unregister_driver(&aic8800_runtime_sdio_driver);
}
module_init(aic8800_sdio_init);
module_exit(aic8800_sdio_exit);

MODULE_LICENSE("GPL");
MODULE_DESCRIPTION("AIC8800 SDIO transport");
