// SPDX-License-Identifier: GPL-2.0-only
// GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: generators/generate_aic8800_upstream.py

#include <linux/errno.h>
#include <linux/delay.h>
#include <linux/etherdevice.h>
#include <linux/if_ether.h>
#include <linux/kernel.h>
#include <linux/mmc/card.h>
#include <linux/mmc/sdio.h>
#include <linux/mmc/sdio_func.h>
#include <linux/netdevice.h>
#include <linux/skbuff.h>
#include <linux/slab.h>
#include <linux/string.h>
#include <linux/types.h>
#include "fw_protocol.h"
#include "sdio_io.h"

u8 aic8800_sdio_crc8(const u8 *buf, size_t len);

u8 aic8800_sdio_crc8(const u8 *buf, size_t len)
{
	/* AIC SDIO header CRC-8 with polynomial X8+X2+X+1 (0x107),
	 * MSB-first within each byte, double-XOR data bit into poly */
	u8 i;
	u8 crc = 0;

	if (!len)
		return 0;

	while (len--) {
		for (i = 0x80; i > 0; i /= 2) {
			if (crc & 0x80) {
				crc *= 2;
				crc ^= 0x07;
			} else {
				crc *= 2;
			}
			if (*buf & i)
				crc ^= 0x07;
		}
		buf++;
	}

	return crc;
}

int aic8800_sdio_io_init(struct sdio_func *func)
{
	u8 val;
	int ret;

	if (!func)
		return -EINVAL;

	sdio_claim_host(func);

	func->card->quirks |= MMC_QUIRK_LENIENT_FN0;

	ret = sdio_set_block_size(func, 512);
	if (ret) {
		sdio_release_host(func);
		return ret;
	}

	ret = sdio_enable_func(func);
	if (ret)
		goto out_release;

	sdio_writeb(func, 0x01, 0x07, &ret);
	if (ret)
		goto out_disable;

	sdio_writeb(func, 0x11, 0x02, &ret);
	if (ret)
		goto out_disable;

	sdio_release_host(func);

	msleep(10);

	sdio_claim_host(func);
	val = sdio_readb(func, 0x01, &ret);
	sdio_release_host(func);
	if (ret)
		goto err_disable;

	if (!(val & 0x10)) {
		dev_err(&func->dev,
			"chip not ready after init (sleep_reg=0x%02x)\n", val);
		ret = -ETIMEDOUT;
		goto err_disable;
	}

	return 0;

err_disable:
	sdio_claim_host(func);
out_disable:
	sdio_disable_func(func);
out_release:
	sdio_release_host(func);
	return ret;
}

void aic8800_sdio_io_deinit(struct sdio_func *func)
{
	if (!func)
		return;

	sdio_claim_host(func);
	sdio_disable_func(func);
	sdio_release_host(func);
}

int aic8800_sdio_tx_write(struct sdio_func *func,
			 const u8 *data, size_t len)
{
	/* TX frame: 4-byte header + payload, padded to 512 blocks
	 * [0-1] LE16 len (total payload bytes)
	 * [2]   type = 0x01 (data)
	 * [3]   CRC8 of bytes 0-2 (8800D80)
	 */
	u8 hdr[4];
	u16 plen = (u16)len;
	size_t block_len;
	int ret;

	if (!func || !data || !len)
		return -EINVAL;

	hdr[0] = plen & 0xFF;
	hdr[1] = (plen >> 8) & 0xFF;
	hdr[2] = 0x01;
	hdr[3] = aic8800_sdio_crc8(hdr, 3);

	block_len = roundup(sizeof(hdr) + len, 512);

	{
		u8 *buf = kzalloc(block_len, GFP_KERNEL);

		if (!buf)
			return -ENOMEM;

		memcpy(buf, hdr, sizeof(hdr));
		memcpy(buf + sizeof(hdr), data, len);

		sdio_claim_host(func);
		ret = sdio_writesb(func, 0x10, buf, block_len);
		sdio_release_host(func);
		kfree(buf);
	}

	if (ret)
		dev_err(&func->dev, "TX write failed: %d\n", ret);

	return ret;
}

int aic8800_sdio_rx_drain(struct aic8800_core *core, int budget)
{
	struct sdio_func *func;
	int frames = 0;
	int ret = 0;

	if (!core || !core->dev)
		return -EINVAL;

	if (!core->protocol)
		return -ENODATA;

	if (budget <= 0)
		budget = 1;

	func = dev_to_sdio_func(core->dev);
	if (!func)
		return -ENODEV;

	while (frames < budget) {
		u8 *frame;
		u8 int_status;
		u32 data_len;
		bool byte_mode;

		/* Read V3 MISC_INT_STATUS_REG to determine data size */
		sdio_claim_host(func);
		ret = sdio_readsb(func, &int_status, 0x04, 1);
		sdio_release_host(func);
		if (ret) {
			if (ret == -ENOMEDIUM)
				break;
			return ret;
		}

		byte_mode = (int_status == 120);
		if (byte_mode) {
			u8 byte_len;

			sdio_claim_host(func);
			ret = sdio_readsb(func, &byte_len,
					   0x05, 1);
			sdio_release_host(func);
			if (ret)
				return ret;

			data_len = byte_len * 4;
		} else {
			data_len = (int_status & 0x7F) * 512;
		}

		if (!data_len || data_len > 2304)
			break;

		frame = kmalloc(data_len, GFP_KERNEL);
		if (!frame)
			return -ENOMEM;

		sdio_claim_host(func);
		ret = sdio_readsb(func, frame, 0x0F, data_len);
		sdio_release_host(func);
		if (ret) {
			kfree(frame);
			return ret;
		}

		ret = aic8800_protocol_rx(core, frame, data_len);
		kfree(frame);
		if (ret < 0)
			core->rx_malformed++;
		frames++;
	}

	if (!frames) {
		core->rx_empty++;
		return -ENODATA;
	}

	core->rx_batches++;
	core->rx_frames += frames;

	return frames;
}
