// SPDX-License-Identifier: GPL-2.0-only
// GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: generators/generate_aic8800_upstream.py

#include <linux/errno.h>
#include <linux/delay.h>
#include <linux/etherdevice.h>
#include <linux/if_ether.h>
#include <linux/kernel.h>
#include <linux/mmc/card.h>
#include <linux/mmc/sdio.h>
#include <linux/mmc/sdio_func.h>
#include <linux/netdevice.h>
#include <linux/skbuff.h>
#include <linux/slab.h>
#include <linux/string.h>
#include <linux/types.h>
#include "sdio_io.h"

u8 aic8800_crc8_ponl_107(const u8 *buf, size_t len);

u8 aic8800_crc8_ponl_107(const u8 *buf, size_t len)
{
	/* Vendor bit-serial CRC-8 with polynomial X8+X2+X+1 (0x107)
	 * MSB-first within each byte, double-XOR data bit into poly */
	u8 i;
	u8 crc = 0;

	if (!len)
		return 0;

	while (len--) {
		for (i = 0x80; i > 0; i /= 2) {
			if (crc & 0x80) {
				crc *= 2;
				crc ^= 0x07;
			} else {
				crc *= 2;
			}
			if (*buf & i)
				crc ^= 0x07;
		}
		buf++;
	}

	return crc;
}

int aic8800_sdio_io_init(struct sdio_func *func)
{
	u8 val;
	int ret;

	if (!func)
		return -EINVAL;

	sdio_claim_host(func);

	func->card->quirks |= MMC_QUIRK_LENIENT_FN0;

	ret = sdio_set_block_size(func, 512);
	if (ret) {
		sdio_release_host(func);
		return ret;
	}

	ret = sdio_enable_func(func);
	if (ret) {
		sdio_release_host(func);
		return ret;
	}

	sdio_release_host(func);

	sdio_claim_host(func);
	ret = sdio_writesb(func, 0x00, "", 1);
	sdio_release_host(func);
	if (ret)
		return ret;

	sdio_claim_host(func);
	ret = sdio_writesb(func, 0x07, "", 1);
	sdio_release_host(func);
	if (ret)
		return ret;

	sdio_claim_host(func);
	ret = sdio_writesb(func, 0x02, "", 1);
	sdio_release_host(func);
	if (ret)
		return ret;

	msleep(10);

	sdio_claim_host(func);
	ret = sdio_readsb(func, &val, 0x01, 1);
	sdio_release_host(func);
	if (ret)
		return ret;

	if (!(val & 0x10)) {
		dev_err(&func->dev,
			"chip not ready after init (sleep_reg=0x%02x)\n", val);
		return -ETIMEDOUT;
	}

	return 0;
}

void aic8800_sdio_io_deinit(struct sdio_func *func)
{
	if (!func)
		return;

	sdio_claim_host(func);
	sdio_disable_func(func);
	sdio_release_host(func);
}

int aic8800_sdio_fw_download(struct sdio_func *func,
			     u32 addr, const u8 *data, size_t len)
{
	int ret;

	if (!func || !data || !len)
		return -EINVAL;

	sdio_claim_host(func);
	ret = sdio_memcpy_toio(func, addr, (void *)data, len);
	sdio_release_host(func);

	if (ret)
		dev_err(&func->dev,
			 "firmware download to 0x%08x failed: %d\n",
			 addr, ret);

	return ret;
}

int aic8800_sdio_start_firmware(struct sdio_func *func, u32 entry)
{
	/* IPC message: 16-byte transport header + 8-byte lmac_msg + 8-byte param
	 * DBG_START_APP_REQ = 0x040D. bootaddr + boottype (both u32 LE) */
	u8  msg[24] = {0};
	u16 payload_len = 20;
	u16 msg_id = 0x040D;
	int ret;

	if (!func || !entry)
		return -EINVAL;

	msg[0] = payload_len & 0xFF;
	msg[1] = ((payload_len >> 8) & 0x0F);
	msg[2] = 0x11;
	msg[3] = aic8800_crc8_ponl_107(msg, 3);
	/* msg[4..7] already 0 (dummy word) */
	msg[8]  = msg_id & 0xFF;
	msg[9]  = (msg_id >> 8) & 0xFF;
	msg[10] = 1;  /* dest = TASK_DBG */
	msg[12] = 100; /* src = DRV_TASK_ID */
	msg[14] = 8;                /* param_len LE */
	msg[16] = entry & 0xFF;     /* bootaddr u32 LE */
	msg[17] = (entry >> 8) & 0xFF;
	msg[18] = (entry >> 16) & 0xFF;
	msg[19] = (entry >> 24) & 0xFF;
	msg[20] = 1;                /* boottype u32 LE = HOST_START_APP_AUTO */
	/* msg[21..23] already 0 */

	sdio_claim_host(func);
	{
		u8 *buf = kzalloc(512, GFP_KERNEL);
		if (!buf) { sdio_release_host(func); return -ENOMEM; }
		memcpy(buf, msg, sizeof(msg));
		ret = sdio_writesb(func, 0x10, buf, 512);
		kfree(buf);
	}
	sdio_release_host(func);
	if (ret) {
		dev_err(&func->dev,
			"START_APP IPC failed: %d\n", ret);
		return ret;
	}

	return 0;
}

int aic8800_sdio_tx_write(struct sdio_func *func,
			 const u8 *data, size_t len)
{
	/* TX frame: 4-byte header + payload, padded to 512 blocks
	 * [0-1] LE16 len (total payload bytes)
	 * [2]   type = 0x01 (data)
	 * [3]   CRC8 of bytes 0-2 (8800D80)
	 */
	u8 hdr[4];
	u16 plen = (u16)len;
	size_t block_len;
	int ret;

	if (!func || !data || !len)
		return -EINVAL;

	hdr[0] = plen & 0xFF;
	hdr[1] = (plen >> 8) & 0xFF;
	hdr[2] = 0x01;
	hdr[3] = aic8800_crc8_ponl_107(hdr, 3);

	block_len = roundup(sizeof(hdr) + len, 512);

	{
		u8 *buf = kzalloc(block_len, GFP_KERNEL);

		if (!buf)
			return -ENOMEM;

		memcpy(buf, hdr, sizeof(hdr));
		memcpy(buf + sizeof(hdr), data, len);

		sdio_claim_host(func);
		ret = sdio_writesb(func, 0x10, buf, block_len);
		sdio_release_host(func);
		kfree(buf);
	}

	if (ret)
		dev_err(&func->dev, "TX write failed: %d\n", ret);

	return ret;
}

int aic8800_sdio_rx_drain(struct aic8800_core *core, int budget)
{
	struct sdio_func *func;
	int frames = 0;
	int ret = 0;

	if (!core || !core->dev || !core->ndev)
		return -EINVAL;

	if (budget <= 0)
		budget = 1;

	func = dev_to_sdio_func(core->dev);
	if (!func)
		return -ENODEV;

	while (frames < budget) {
		struct sk_buff *skb;
		u8 int_status;
		u32 data_len;
		bool byte_mode;

		/* Read V3 MISC_INT_STATUS_REG to determine data size */
		sdio_claim_host(func);
		ret = sdio_readsb(func, &int_status, 0x04, 1);
		sdio_release_host(func);
		if (ret) {
			if (ret == -ENOMEDIUM)
				break;
			return ret;
		}

		byte_mode = (int_status >= 120);
		if (byte_mode) {
			u8 byte_len;

			sdio_claim_host(func);
			ret = sdio_readsb(func, &byte_len,
					   0x05, 1);
			sdio_release_host(func);
			if (ret)
				return ret;

			data_len = byte_len * 4;
		} else {
			data_len = (int_status & 0x7F) * 512;
		}

		if (!data_len || data_len > 2304)
			break;

		skb = netdev_alloc_skb(core->ndev, data_len + NET_IP_ALIGN);
		if (!skb)
			return -ENOMEM;

		skb_reserve(skb, NET_IP_ALIGN);
		sdio_claim_host(func);
		ret = sdio_readsb(func, skb_put(skb, data_len),
				   0x0F, data_len);
		sdio_release_host(func);
		if (ret) {
			dev_kfree_skb_any(skb);
			return ret;
		}

		if (skb->len < ETH_HLEN) {
			core->rx_malformed++;
			core->rx_drop_malformed++;
			core->ndev->stats.rx_dropped++;
			dev_kfree_skb_any(skb);
			frames++;
			continue;
		}

		if (core->rx_submit) {
			ret = core->rx_submit(core, skb);
			if (ret) {
				if (ret == -ENOSPC)
					core->rx_drop_queue_full++;
				core->ndev->stats.rx_dropped++;
				core->rx_errors++;
				dev_kfree_skb_any(skb);
			}
		} else {
			core->ndev->stats.rx_dropped++;
			core->rx_errors++;
			dev_kfree_skb_any(skb);
		}
		frames++;
	}

	if (!frames) {
		core->rx_empty++;
		return -ENODATA;
	}

	core->rx_batches++;
	core->rx_frames += frames;

	return frames;
}
